// Copyright 2026 Damien Stevens and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newDowntimeCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "downtime",
		Short:       "List, get, create, and delete downtime",
		Hidden:      true,
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newDowntimeCreateCmd(flags))
	cmd.AddCommand(newDowntimeDeleteCmd(flags))
	cmd.AddCommand(newDowntimeGetCmd(flags))
	cmd.AddCommand(newDowntimeListCmd(flags))
	cmd.AddCommand(newDowntimeListDowntimecalendarCmd(flags))
	return cmd
}
