// Copyright 2026 Damien Stevens and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newSubscriptionsComponentsJsonListSubscriptionComponentsCmd(flags *rootFlags) *cobra.Command {
	var flagDateField string
	var flagDirection string
	var flagFilter string
	var flagEndDate string
	var flagEndDatetime string
	var flagPricePointIds string
	var flagProductFamilyIds string
	var flagSort string
	var flagStartDate string
	var flagStartDatetime string
	var flagInclude string
	var flagInUse bool

	cmd := &cobra.Command{
		Use:         "list-subscription-components <subscription_id>",
		Aliases:     []string{"get"},
		Short:       "Lists a subscription's applied components.",
		Example:     "  maxio-cli subscriptions components-json list-subscription-components 550e8400-e29b-41d4-a716-446655440000",
		Annotations: map[string]string{"pp:endpoint": "components-json.list-subscription-components", "pp:method": "GET", "pp:path": "/subscriptions/{subscription_id}/components.json", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) == 0 {
				return cmd.Help()
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/subscriptions/{subscription_id}/components.json"
			path = replacePathParam(path, "subscription_id", args[0])
			params := map[string]string{}
			if flagDateField != "" {
				params["date_field"] = formatCLIParamValue(flagDateField)
			}
			if flagDirection != "" {
				params["direction"] = formatCLIParamValue(flagDirection)
			}
			if flagFilter != "" {
				params["filter"] = formatCLIParamValue(flagFilter)
			}
			if flagEndDate != "" {
				params["end_date"] = formatCLIParamValue(flagEndDate)
			}
			if flagEndDatetime != "" {
				params["end_datetime"] = formatCLIParamValue(flagEndDatetime)
			}
			if flagPricePointIds != "" {
				params["price_point_ids"] = formatCLIParamValue(flagPricePointIds)
			}
			if flagProductFamilyIds != "" {
				params["product_family_ids"] = formatCLIParamValue(flagProductFamilyIds)
			}
			if flagSort != "" {
				params["sort"] = formatCLIParamValue(flagSort)
			}
			if flagStartDate != "" {
				params["start_date"] = formatCLIParamValue(flagStartDate)
			}
			if flagStartDatetime != "" {
				params["start_datetime"] = formatCLIParamValue(flagStartDatetime)
			}
			if flagInclude != "" {
				params["include"] = formatCLIParamValue(flagInclude)
			}
			if flagInUse != false {
				params["in_use"] = formatCLIParamValue(flagInUse)
			}
			data, prov, err := resolveReadWithStrategy(cmd.Context(), c, flags, "auto", "components-json", false, path, params, nil, cmd.ErrOrStderr())
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Print provenance to stderr for human-facing output only.
			// Machine-format flags (--json, --csv, --compact, --quiet, --plain,
			// --select) and piped stdout suppress this line; the JSON envelope
			// already carries meta.source for those consumers.
			// SYNC: keep this gate aligned with command_promoted.go.tmpl.
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var countItems []json.RawMessage
				_ = json.Unmarshal(data, &countItems)
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope before passing through flags.
			// --select wins over --compact when both are set; --compact only runs when
			// no explicit fields were requested. Explicit format flags (--csv, --quiet,
			// --plain) opt out of the auto-JSON path so piped consumers that asked for
			// a non-JSON format reach the standard pipeline below.
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			// For all other output modes (table, csv, plain, quiet), use the standard pipeline
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&flagDateField, "date-field", "", "The type of filter you'd like to apply to your search. Use in query `date_field=updated_at`.")
	cmd.Flags().StringVar(&flagDirection, "direction", "", "Controls the order in which results are returned. Use in query `direction=asc`.")
	cmd.Flags().StringVar(&flagFilter, "filter", "", "Filter to use for List Subscription Components operation")
	cmd.Flags().StringVar(&flagEndDate, "end-date", "", "The end date (format YYYY-MM-DD) with which to filter the date_field.")
	cmd.Flags().StringVar(&flagEndDatetime, "end-datetime", "", "The end date and time (format YYYY-MM-DD HH:MM:SS) with which to filter the date_field.")
	cmd.Flags().StringVar(&flagPricePointIds, "price-point-ids", "", "Allows fetching components allocation only if price point id is present. Use in query `price_point_ids=not_null`.")
	cmd.Flags().StringVar(&flagProductFamilyIds, "product-family-ids", "", "Allows fetching components allocation with matching product family id based on provided ids.")
	cmd.Flags().StringVar(&flagSort, "sort", "", "The attribute by which to sort. Use in query `sort=updated_at`.")
	cmd.Flags().StringVar(&flagStartDate, "start-date", "", "The start date (format YYYY-MM-DD) with which to filter the date_field.")
	cmd.Flags().StringVar(&flagStartDatetime, "start-datetime", "", "The start date and time (format YYYY-MM-DD HH:MM:SS) with which to filter the date_field.")
	cmd.Flags().StringVar(&flagInclude, "include", "", "Allows including additional data in the response. Use in query `include=subscription,historic_usages`.")
	cmd.Flags().BoolVar(&flagInUse, "in-use", false, "If in_use is set to true, it returns only components that are currently in use.")

	return cmd
}
