// Copyright 2026 Damien Stevens and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newContactsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "contacts",
		Short:       "Get, create, and update contacts",
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newContactsCreateCmd(flags))
	cmd.AddCommand(newContactsGetCmd(flags))
	cmd.AddCommand(newContactsGetByNumberCmd(flags))
	cmd.AddCommand(newContactsGetContactidCmd(flags))
	cmd.AddCommand(newContactsUpdateCmd(flags))
	cmd.AddCommand(newContactsUpdateOrCreateCmd(flags))
	cmd.AddCommand(newContactsHistoryCmd(flags))
	return cmd
}
