// Copyright 2026 Damien Stevens and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package mcp

import (
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	mcplib "github.com/mark3labs/mcp-go/mcp"
	"github.com/mark3labs/mcp-go/server"
	"n-central-pp-cli/internal/cli"
	"n-central-pp-cli/internal/client"
	"n-central-pp-cli/internal/cliutil"
	"n-central-pp-cli/internal/config"
	"n-central-pp-cli/internal/mcp/cobratree"
	"n-central-pp-cli/internal/store"
)

// RegisterTools registers all API operations as MCP tools.
func RegisterTools(s *server.MCPServer) {
	s.AddTool(
		mcplib.NewTool("access-groups_get",
			mcplib.WithDescription("Retrieve detailed information for an access group by ID. Required: accessGroupId. Returns the OrgUnit."),
			mcplib.WithString("accessGroupId", mcplib.Required(), mcplib.Description("accessGroupId")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/access-groups/{accessGroupId}", true, false, nil, []mcpParamBinding{{PublicName: "accessGroupId", WireName: "accessGroupId", Location: "path"}}, []string{"accessGroupId"}),
	)
	s.AddTool(
		mcplib.NewTool("customers_get",
			mcplib.WithDescription("Retrieve a single customer by ID. Required: customerId. Returns the Customer."),
			mcplib.WithString("customerId", mcplib.Required(), mcplib.Description("customerId")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/customers/{customerId}", true, false, nil, []mcpParamBinding{{PublicName: "customerId", WireName: "customerId", Location: "path"}}, []string{"customerId"}),
	)
	s.AddTool(
		mcplib.NewTool("customers_list",
			mcplib.WithDescription("List all customers across the instance. Optional: pageNumber, pageSize, sortBy (plus 2 more). Returns array of Customer."),
			mcplib.WithNumber("pageNumber", mcplib.Description("Page number (1-based)")),
			mcplib.WithNumber("pageSize", mcplib.Description("Items per page (default 50, -1 for all)")),
			mcplib.WithString("sortBy", mcplib.Description("Field to sort by (e.g. customerName)")),
			mcplib.WithString("sortOrder", mcplib.Description("asc or desc")),
			mcplib.WithString("select", mcplib.Description("Field-selection expression")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/customers", true, false, nil, []mcpParamBinding{{PublicName: "pageNumber", WireName: "pageNumber", Location: "query"}, {PublicName: "pageSize", WireName: "pageSize", Location: "query"}, {PublicName: "sortBy", WireName: "sortBy", Location: "query"}, {PublicName: "sortOrder", WireName: "sortOrder", Location: "query"}, {PublicName: "select", WireName: "select", Location: "query"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("customers_registration-token",
			mcplib.WithDescription("Retrieve the agent registration token for a customer (used to enroll new devices). Required: customerId. Returns the Customer."),
			mcplib.WithString("customerId", mcplib.Required(), mcplib.Description("customerId")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/customers/{customerId}/registration-token", true, false, nil, []mcpParamBinding{{PublicName: "customerId", WireName: "customerId", Location: "path"}}, []string{"customerId"}),
	)
	s.AddTool(
		mcplib.NewTool("device-filters_list",
			mcplib.WithDescription("List saved device filters for the API user. Returns array of OrgUnit."),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/device-filters", true, false, nil, []mcpParamBinding{}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("devices_assets",
			mcplib.WithDescription("Retrieve hardware/software asset inventory for a device. Required: deviceId. Returns the Device."),
			mcplib.WithString("deviceId", mcplib.Required(), mcplib.Description("deviceId")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/devices/{deviceId}/assets", true, false, nil, []mcpParamBinding{{PublicName: "deviceId", WireName: "deviceId", Location: "path"}}, []string{"deviceId"}),
	)
	s.AddTool(
		mcplib.NewTool("devices_get",
			mcplib.WithDescription("Retrieve a single device by ID. Required: deviceId. Returns the Device."),
			mcplib.WithString("deviceId", mcplib.Required(), mcplib.Description("deviceId")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/devices/{deviceId}", true, false, nil, []mcpParamBinding{{PublicName: "deviceId", WireName: "deviceId", Location: "path"}}, []string{"deviceId"}),
	)
	s.AddTool(
		mcplib.NewTool("devices_list",
			mcplib.WithDescription("List all devices visible to the API user, across the org tree. Optional: filterId, pageNumber, pageSize (plus 3 more). Returns array of Device."),
			mcplib.WithNumber("filterId", mcplib.Description("Apply a saved N-central device filter by ID")),
			mcplib.WithNumber("pageNumber", mcplib.Description("Page number (1-based)")),
			mcplib.WithNumber("pageSize", mcplib.Description("Items per page (default 50, -1 for all)")),
			mcplib.WithString("sortBy", mcplib.Description("Field to sort by (e.g. longName, customerName)")),
			mcplib.WithString("sortOrder", mcplib.Description("asc or desc")),
			mcplib.WithString("select", mcplib.Description("Field-selection expression")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/devices", true, false, nil, []mcpParamBinding{{PublicName: "filterId", WireName: "filterId", Location: "query"}, {PublicName: "pageNumber", WireName: "pageNumber", Location: "query"}, {PublicName: "pageSize", WireName: "pageSize", Location: "query"}, {PublicName: "sortBy", WireName: "sortBy", Location: "query"}, {PublicName: "sortOrder", WireName: "sortOrder", Location: "query"}, {PublicName: "select", WireName: "select", Location: "query"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("devices_maintenance",
			mcplib.WithDescription("List patch maintenance windows configured for a device. Required: deviceId. Returns array of Device."),
			mcplib.WithString("deviceId", mcplib.Required(), mcplib.Description("deviceId")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/devices/{deviceId}/maintenance-windows", true, false, nil, []mcpParamBinding{{PublicName: "deviceId", WireName: "deviceId", Location: "path"}}, []string{"deviceId"}),
	)
	s.AddTool(
		mcplib.NewTool("devices_properties",
			mcplib.WithDescription("List custom property values for a device (the backbone of MSP automation/documentation). Required: deviceId. Returns array of Device."),
			mcplib.WithString("deviceId", mcplib.Required(), mcplib.Description("deviceId")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/devices/{deviceId}/custom-properties", true, false, nil, []mcpParamBinding{{PublicName: "deviceId", WireName: "deviceId", Location: "path"}}, []string{"deviceId"}),
	)
	s.AddTool(
		mcplib.NewTool("devices_status",
			mcplib.WithDescription("Retrieve the service-monitoring status (active issues / health) for a device. Required: deviceId. Returns array of ActiveIssue."),
			mcplib.WithString("deviceId", mcplib.Required(), mcplib.Description("deviceId")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/devices/{deviceId}/service-monitor-status", true, false, nil, []mcpParamBinding{{PublicName: "deviceId", WireName: "deviceId", Location: "path"}}, []string{"deviceId"}),
	)
	s.AddTool(
		mcplib.NewTool("devices_tasks",
			mcplib.WithDescription("List scheduled/automation tasks targeting this device. Required: deviceId. Returns array of Device."),
			mcplib.WithString("deviceId", mcplib.Required(), mcplib.Description("deviceId")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/devices/{deviceId}/scheduled-tasks", true, false, nil, []mcpParamBinding{{PublicName: "deviceId", WireName: "deviceId", Location: "path"}}, []string{"deviceId"}),
	)
	s.AddTool(
		mcplib.NewTool("org-units_access-groups",
			mcplib.WithDescription("List access groups for an org unit. Required: orgUnitId. Returns array of OrgUnit."),
			mcplib.WithString("orgUnitId", mcplib.Required(), mcplib.Description("orgUnitId")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/org-units/{orgUnitId}/access-groups", true, false, nil, []mcpParamBinding{{PublicName: "orgUnitId", WireName: "orgUnitId", Location: "path"}}, []string{"orgUnitId"}),
	)
	s.AddTool(
		mcplib.NewTool("org-units_active-issues",
			mcplib.WithDescription("Fetch active monitoring issues for an org unit (the daily NOC triage feed). Required: orgUnitId. Optional: pageNumber, pageSize, sortBy (plus 1 more). Returns array of ActiveIssue."),
			mcplib.WithNumber("pageNumber", mcplib.Description("Page number (1-based)")),
			mcplib.WithNumber("pageSize", mcplib.Description("Items per page (1-1000)")),
			mcplib.WithString("sortBy", mcplib.Description("Field to sort by")),
			mcplib.WithString("sortOrder", mcplib.Description("asc or desc")),
			mcplib.WithString("orgUnitId", mcplib.Required(), mcplib.Description("orgUnitId")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/org-units/{orgUnitId}/active-issues", true, false, nil, []mcpParamBinding{{PublicName: "pageNumber", WireName: "pageNumber", Location: "query"}, {PublicName: "pageSize", WireName: "pageSize", Location: "query"}, {PublicName: "sortBy", WireName: "sortBy", Location: "query"}, {PublicName: "sortOrder", WireName: "sortOrder", Location: "query"}, {PublicName: "orgUnitId", WireName: "orgUnitId", Location: "path"}}, []string{"orgUnitId"}),
	)
	s.AddTool(
		mcplib.NewTool("org-units_children",
			mcplib.WithDescription("List the direct children of an org unit. Required: orgUnitId. Returns array of OrgUnit."),
			mcplib.WithString("orgUnitId", mcplib.Required(), mcplib.Description("orgUnitId")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/org-units/{orgUnitId}/children", true, false, nil, []mcpParamBinding{{PublicName: "orgUnitId", WireName: "orgUnitId", Location: "path"}}, []string{"orgUnitId"}),
	)
	s.AddTool(
		mcplib.NewTool("org-units_devices",
			mcplib.WithDescription("List devices scoped to a specific org unit. Required: orgUnitId. Optional: pageNumber, pageSize. Returns array of Device."),
			mcplib.WithNumber("pageNumber", mcplib.Description("Page number (1-based)")),
			mcplib.WithNumber("pageSize", mcplib.Description("Items per page (default 50, -1 for all)")),
			mcplib.WithString("orgUnitId", mcplib.Required(), mcplib.Description("orgUnitId")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/org-units/{orgUnitId}/devices", true, false, nil, []mcpParamBinding{{PublicName: "pageNumber", WireName: "pageNumber", Location: "query"}, {PublicName: "pageSize", WireName: "pageSize", Location: "query"}, {PublicName: "orgUnitId", WireName: "orgUnitId", Location: "path"}}, []string{"orgUnitId"}),
	)
	s.AddTool(
		mcplib.NewTool("org-units_get",
			mcplib.WithDescription("Retrieve a single org unit by ID. Required: orgUnitId. Returns the OrgUnit."),
			mcplib.WithString("orgUnitId", mcplib.Required(), mcplib.Description("orgUnitId")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/org-units/{orgUnitId}", true, false, nil, []mcpParamBinding{{PublicName: "orgUnitId", WireName: "orgUnitId", Location: "path"}}, []string{"orgUnitId"}),
	)
	s.AddTool(
		mcplib.NewTool("org-units_job-statuses",
			mcplib.WithDescription("Fetch job statuses for an org unit. Required: orgUnitId. Returns array of ActiveIssue."),
			mcplib.WithString("orgUnitId", mcplib.Required(), mcplib.Description("orgUnitId")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/org-units/{orgUnitId}/job-statuses", true, false, nil, []mcpParamBinding{{PublicName: "orgUnitId", WireName: "orgUnitId", Location: "path"}}, []string{"orgUnitId"}),
	)
	s.AddTool(
		mcplib.NewTool("org-units_list",
			mcplib.WithDescription("List all organization units (SO, customer, and site nodes). Optional: pageNumber, pageSize, sortBy (plus 1 more). Returns array of OrgUnit."),
			mcplib.WithNumber("pageNumber", mcplib.Description("Page number (1-based)")),
			mcplib.WithNumber("pageSize", mcplib.Description("Items per page (default 50, -1 for all)")),
			mcplib.WithString("sortBy", mcplib.Description("Field to sort by")),
			mcplib.WithString("sortOrder", mcplib.Description("asc or desc")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/org-units", true, false, nil, []mcpParamBinding{{PublicName: "pageNumber", WireName: "pageNumber", Location: "query"}, {PublicName: "pageSize", WireName: "pageSize", Location: "query"}, {PublicName: "sortBy", WireName: "sortBy", Location: "query"}, {PublicName: "sortOrder", WireName: "sortOrder", Location: "query"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("org-units_registration-token",
			mcplib.WithDescription("Retrieve the agent registration token for an org unit. Required: orgUnitId. Returns the OrgUnit."),
			mcplib.WithString("orgUnitId", mcplib.Required(), mcplib.Description("orgUnitId")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/org-units/{orgUnitId}/registration-token", true, false, nil, []mcpParamBinding{{PublicName: "orgUnitId", WireName: "orgUnitId", Location: "path"}}, []string{"orgUnitId"}),
	)
	s.AddTool(
		mcplib.NewTool("org-units_user-roles",
			mcplib.WithDescription("List user roles defined for an org unit. Required: orgUnitId. Returns array of OrgUnit."),
			mcplib.WithString("orgUnitId", mcplib.Required(), mcplib.Description("orgUnitId")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/org-units/{orgUnitId}/user-roles", true, false, nil, []mcpParamBinding{{PublicName: "orgUnitId", WireName: "orgUnitId", Location: "path"}}, []string{"orgUnitId"}),
	)
	s.AddTool(
		mcplib.NewTool("scheduled-tasks_get",
			mcplib.WithDescription("Retrieve general information for a scheduled task. Required: taskId. Returns the ActiveIssue."),
			mcplib.WithString("taskId", mcplib.Required(), mcplib.Description("taskId")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/scheduled-tasks/{taskId}", true, false, nil, []mcpParamBinding{{PublicName: "taskId", WireName: "taskId", Location: "path"}}, []string{"taskId"}),
	)
	s.AddTool(
		mcplib.NewTool("scheduled-tasks_run",
			mcplib.WithDescription("Create a direct-support scheduled task (run an Automation Policy, Script, or MacScript on a device). Required: name, itemId, taskType, customerId, deviceId. Returns the new ActiveIssue."),
			mcplib.WithString("name", mcplib.Required(), mcplib.Description("Unique task name")),
			mcplib.WithNumber("itemId", mcplib.Required(), mcplib.Description("Remote-execution item ID from the Script/Software Repository (must be API-enabled in N-central)")),
			mcplib.WithString("taskType", mcplib.Required(), mcplib.Description("AutomationPolicy, Script, or MacScript")),
			mcplib.WithNumber("customerId", mcplib.Required(), mcplib.Description("Target customer ID")),
			mcplib.WithNumber("deviceId", mcplib.Required(), mcplib.Description("Target device ID")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/scheduled-tasks/direct", false, false, nil, []mcpParamBinding{{PublicName: "name", WireName: "name", Location: "body"}, {PublicName: "itemId", WireName: "itemId", Location: "body"}, {PublicName: "taskType", WireName: "taskType", Location: "body"}, {PublicName: "customerId", WireName: "customerId", Location: "body"}, {PublicName: "deviceId", WireName: "deviceId", Location: "body"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("scheduled-tasks_status",
			mcplib.WithDescription("Retrieve aggregated status for a scheduled task. Required: taskId. Returns the ActiveIssue."),
			mcplib.WithString("taskId", mcplib.Required(), mcplib.Description("taskId")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/scheduled-tasks/{taskId}/status", true, false, nil, []mcpParamBinding{{PublicName: "taskId", WireName: "taskId", Location: "path"}}, []string{"taskId"}),
	)
	s.AddTool(
		mcplib.NewTool("server_health",
			mcplib.WithDescription("Return the start and current time of the server (lightweight reachability check). Returns the OrgUnit. (public)"),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/health", true, false, nil, []mcpParamBinding{}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("server_info",
			mcplib.WithDescription("Return version information for the N-central API service and systems. Returns the OrgUnit."),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/server-info", true, false, nil, []mcpParamBinding{}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("service-orgs_customers",
			mcplib.WithDescription("List all customers under a service organization. Required: soId. Returns array of Customer."),
			mcplib.WithString("soId", mcplib.Required(), mcplib.Description("soId")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/service-orgs/{soId}/customers", true, false, nil, []mcpParamBinding{{PublicName: "soId", WireName: "soId", Location: "path"}}, []string{"soId"}),
	)
	s.AddTool(
		mcplib.NewTool("service-orgs_get",
			mcplib.WithDescription("Retrieve a single service organization by ID. Required: soId. Returns the ServiceOrg."),
			mcplib.WithString("soId", mcplib.Required(), mcplib.Description("soId")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/service-orgs/{soId}", true, false, nil, []mcpParamBinding{{PublicName: "soId", WireName: "soId", Location: "path"}}, []string{"soId"}),
	)
	s.AddTool(
		mcplib.NewTool("service-orgs_list",
			mcplib.WithDescription("List all service organizations. Optional: pageNumber, pageSize, sortBy (plus 1 more). Returns array of ServiceOrg."),
			mcplib.WithNumber("pageNumber", mcplib.Description("Page number (1-based)")),
			mcplib.WithNumber("pageSize", mcplib.Description("Items per page (default 50, -1 for all)")),
			mcplib.WithString("sortBy", mcplib.Description("Field to sort by")),
			mcplib.WithString("sortOrder", mcplib.Description("asc or desc")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/service-orgs", true, false, nil, []mcpParamBinding{{PublicName: "pageNumber", WireName: "pageNumber", Location: "query"}, {PublicName: "pageSize", WireName: "pageSize", Location: "query"}, {PublicName: "sortBy", WireName: "sortBy", Location: "query"}, {PublicName: "sortOrder", WireName: "sortOrder", Location: "query"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("sites_get",
			mcplib.WithDescription("Retrieve a single site by ID. Required: siteId. Returns the Site."),
			mcplib.WithString("siteId", mcplib.Required(), mcplib.Description("siteId")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/sites/{siteId}", true, false, nil, []mcpParamBinding{{PublicName: "siteId", WireName: "siteId", Location: "path"}}, []string{"siteId"}),
	)
	s.AddTool(
		mcplib.NewTool("sites_list",
			mcplib.WithDescription("List all sites across the instance. Optional: pageNumber, pageSize, sortBy (plus 1 more). Returns array of Site."),
			mcplib.WithNumber("pageNumber", mcplib.Description("Page number (1-based)")),
			mcplib.WithNumber("pageSize", mcplib.Description("Items per page (default 50, -1 for all)")),
			mcplib.WithString("sortBy", mcplib.Description("Field to sort by")),
			mcplib.WithString("sortOrder", mcplib.Description("asc or desc")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/sites", true, false, nil, []mcpParamBinding{{PublicName: "pageNumber", WireName: "pageNumber", Location: "query"}, {PublicName: "pageSize", WireName: "pageSize", Location: "query"}, {PublicName: "sortBy", WireName: "sortBy", Location: "query"}, {PublicName: "sortOrder", WireName: "sortOrder", Location: "query"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("users_list",
			mcplib.WithDescription("List N-central users. Optional: pageNumber, pageSize. Returns array of OrgUnit."),
			mcplib.WithNumber("pageNumber", mcplib.Description("Page number (1-based)")),
			mcplib.WithNumber("pageSize", mcplib.Description("Items per page (default 50, -1 for all)")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/users", true, false, nil, []mcpParamBinding{{PublicName: "pageNumber", WireName: "pageNumber", Location: "query"}, {PublicName: "pageSize", WireName: "pageSize", Location: "query"}}, []string{}),
	)
	// Search tool — faster than iterating list endpoints for finding specific items
	s.AddTool(
		mcplib.NewTool("search",
			mcplib.WithDescription("Full-text search across all synced data. Faster than paginating list endpoints. Requires sync first."),
			mcplib.WithString("query", mcplib.Required(), mcplib.Description("Search query (supports FTS5 syntax: AND, OR, NOT, quotes for phrases)")),
			mcplib.WithNumber("limit", mcplib.Description("Max results (default 25)")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
		),
		handleSearch,
	)
	// SQL tool — ad-hoc analysis on synced data without API calls
	s.AddTool(
		mcplib.NewTool("sql",
			mcplib.WithDescription("Run read-only SQL against local database. Use for ad-hoc analysis, aggregations, and joins across synced resources. Requires sync first."),
			mcplib.WithString("query", mcplib.Required(), mcplib.Description("SQL query (SELECT or WITH...SELECT). Tables match resource names.")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
		),
		handleSQL,
	)

	// Context tool — front-loaded domain knowledge for agents.
	// Call this first to understand the API taxonomy, query patterns, and capabilities.
	s.AddTool(
		mcplib.NewTool("context",
			mcplib.WithDescription("Get API domain context: resource taxonomy, auth requirements, query tips, and unique capabilities. Call this first."),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
		),
		handleContext,
	)

	// Runtime Cobra-tree mirror — exposes every user-facing command that is
	// not already covered by a typed endpoint or framework MCP tool.
	cobratree.RegisterAll(s, cli.RootCmd(), cobratree.SiblingCLIPath)
}

type mcpParamBinding struct {
	PublicName string
	WireName   string
	Location   string
}

// makeAPIHandler creates a generic MCP tool handler for an API endpoint.
func makeAPIHandler(method, pathTemplate string, readOnly bool, binaryResponse bool, headerOverrides map[string]string, bindings []mcpParamBinding, positionalParams []string) server.ToolHandlerFunc {
	return func(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
		c, err := newMCPClient()
		if err != nil {
			return mcplib.NewToolResultError(err.Error()), nil
		}

		// mcp-go v0.47+ made CallToolParams.Arguments an `any` to support
		// non-map payloads; GetArguments() returns the map[string]any shape
		// we rely on here (or an empty map when the payload is something else).
		args := req.GetArguments()

		// positionalParams mixes real URL path params with CLI positional
		// args that map to query params (e.g. `search <query>` -> ?query=);
		// the placeholder check below disambiguates them at runtime.
		path := pathTemplate
		knownArgs := make(map[string]bool, len(bindings))
		pathParams := make(map[string]bool, len(positionalParams))
		params := make(map[string]string)
		bodyArgs := make(map[string]any)
		var headers map[string]string
		if len(headerOverrides) > 0 {
			headers = make(map[string]string, len(headerOverrides)+1)
			for k, v := range headerOverrides {
				headers[k] = v
			}
		}
		if binaryResponse {
			if headers == nil {
				headers = map[string]string{}
			}
			headers[client.BinaryResponseHeader] = "true"
		}
		for _, binding := range bindings {
			knownArgs[binding.PublicName] = true
			v, ok := args[binding.PublicName]
			if !ok {
				continue
			}
			switch binding.Location {
			case "path":
				placeholder := "{" + binding.WireName + "}"
				pathParams[binding.PublicName] = true
				path = strings.Replace(path, placeholder, fmt.Sprintf("%v", v), 1)
			case "body":
				bodyArgs[binding.WireName] = v
			default:
				params[binding.WireName] = fmt.Sprintf("%v", v)
			}
		}
		for _, p := range positionalParams {
			placeholder := "{" + p + "}"
			if !strings.Contains(pathTemplate, placeholder) {
				continue
			}
			pathParams[p] = true
			if v, ok := args[p]; ok {
				path = strings.Replace(path, placeholder, fmt.Sprintf("%v", v), 1)
			}
		}

		for k, v := range args {
			if pathParams[k] || knownArgs[k] {
				continue
			}
			switch method {
			case "POST", "PUT", "PATCH":
				bodyArgs[k] = v
			default:
				params[k] = fmt.Sprintf("%v", v)
			}
		}

		var data json.RawMessage
		switch method {
		case "GET":
			if len(headers) > 0 {
				data, err = c.GetWithHeaders(ctx, path, params, headers)
				break
			}
			data, err = c.Get(ctx, path, params)
		case "POST":
			if len(headers) > 0 {
				if readOnly {
					data, _, err = c.PostQueryWithParamsAndHeaders(ctx, path, params, bodyArgs, headers)
				} else {
					data, _, err = c.PostWithParamsAndHeaders(ctx, path, params, bodyArgs, headers)
				}
				break
			}
			if readOnly {
				data, _, err = c.PostQueryWithParams(ctx, path, params, bodyArgs)
			} else {
				data, _, err = c.PostWithParams(ctx, path, params, bodyArgs)
			}
		case "PUT":
			if len(headers) > 0 {
				data, _, err = c.PutWithParamsAndHeaders(ctx, path, params, bodyArgs, headers)
				break
			}
			data, _, err = c.PutWithParams(ctx, path, params, bodyArgs)
		case "PATCH":
			if len(headers) > 0 {
				data, _, err = c.PatchWithParamsAndHeaders(ctx, path, params, bodyArgs, headers)
				break
			}
			data, _, err = c.PatchWithParams(ctx, path, params, bodyArgs)
		case "DELETE":
			if len(headers) > 0 {
				data, _, err = c.DeleteWithParamsAndHeaders(ctx, path, params, headers)
				break
			}
			data, _, err = c.DeleteWithParams(ctx, path, params)
		default:
			return mcplib.NewToolResultError("unsupported method: " + method), nil
		}

		if err != nil {
			msg := err.Error()
			switch {
			case strings.Contains(msg, "HTTP 409"):
				return mcplib.NewToolResultText("already exists (no-op)"), nil
			case strings.Contains(msg, "HTTP 400") && cliutil.LooksLikeAuthError(msg):
				return mcplib.NewToolResultError("authentication error: " + cliutil.SanitizeErrorBody(msg) +
					"\nhint: the API rejected the request — this usually means auth is missing or invalid." +
					"\n      Set your API key: export NCENTRAL_JWT=<your-key>" +
					"\n      Generate a JSON Web Token for an API-only user in N-central: Administration -> User Management -> Users -> select the API user -> API Access -> GENERATE JSON WEB TOKEN. MFA must be OFF on that user, and watch the password-expiry (default 90 days) which silently invalidates the JWT. Also set N_CENTRAL_BASE_URL to your tenant, e.g. https://yourmsp.ncod.n-able.com/api" +
					"\n      Run 'n-central-pp-cli doctor' to check auth status."), nil
			case strings.Contains(msg, "HTTP 401"):
				return mcplib.NewToolResultError("authentication failed: " + cliutil.SanitizeErrorBody(msg) +
					"\nhint: check your token." +
					"\n      Set it with: export NCENTRAL_JWT=<your-key>" +
					"\n      Generate a JSON Web Token for an API-only user in N-central: Administration -> User Management -> Users -> select the API user -> API Access -> GENERATE JSON WEB TOKEN. MFA must be OFF on that user, and watch the password-expiry (default 90 days) which silently invalidates the JWT. Also set N_CENTRAL_BASE_URL to your tenant, e.g. https://yourmsp.ncod.n-able.com/api" +
					"\n      Run 'n-central-pp-cli doctor' to check auth status."), nil
			case strings.Contains(msg, "HTTP 403"):
				return mcplib.NewToolResultError("permission denied: " + cliutil.SanitizeErrorBody(msg) +
					"\nhint: your credentials are valid but lack access to this resource." +
					"\n      Set it with: export NCENTRAL_JWT=<your-key>" +
					"\n      Generate a JSON Web Token for an API-only user in N-central: Administration -> User Management -> Users -> select the API user -> API Access -> GENERATE JSON WEB TOKEN. MFA must be OFF on that user, and watch the password-expiry (default 90 days) which silently invalidates the JWT. Also set N_CENTRAL_BASE_URL to your tenant, e.g. https://yourmsp.ncod.n-able.com/api" +
					"\n      Run 'n-central-pp-cli doctor' to check auth status."), nil
			case strings.Contains(msg, "HTTP 404"):
				if method == "DELETE" {
					return mcplib.NewToolResultText("already deleted (no-op)"), nil
				}
				return mcplib.NewToolResultError("not found: " + msg), nil
			case strings.Contains(msg, "HTTP 429"):
				return mcplib.NewToolResultError("rate limited: " + msg), nil
			default:
				return mcplib.NewToolResultError(msg), nil
			}
		}

		// For GET responses, wrap bare arrays with count metadata
		if method == "GET" {
			trimmed := strings.TrimSpace(string(data))
			if len(trimmed) > 0 && trimmed[0] == '[' {
				var items []json.RawMessage
				if json.Unmarshal(data, &items) == nil {
					wrapped := map[string]any{
						"count": len(items),
						"items": items,
					}
					out, _ := json.Marshal(wrapped)
					return mcplib.NewToolResultText(string(out)), nil
				}
			}
		}
		if binaryResponse {
			out, _ := json.Marshal(map[string]any{
				"content_encoding": "base64",
				"data_base64":      base64.StdEncoding.EncodeToString(data),
				"byte_count":       len(data),
			})
			return mcplib.NewToolResultText(string(out)), nil
		}
		return mcplib.NewToolResultText(string(data)), nil
	}
}

func newMCPClient() (*client.Client, error) {
	home, _ := os.UserHomeDir()
	cfgPath := filepath.Join(home, ".config", "n-central-pp-cli", "config.toml")
	cfg, err := config.Load(cfgPath)
	if err != nil {
		return nil, fmt.Errorf("loading config: %w", err)
	}
	c := client.New(cfg, 60*time.Second, 0)
	// Agents calling through MCP need fresh data every call. The on-disk
	// response cache survives across MCP server invocations, so a
	// DELETE/PATCH followed by a GET would otherwise return the
	// pre-mutation snapshot for up to the cache TTL. The interactive CLI
	// constructs its own client and is unaffected.
	c.NoCache = true
	return c, nil
}

func dbPath() string {
	home, _ := os.UserHomeDir()
	return filepath.Join(home, ".local", "share", "n-central-pp-cli", "data.db")
}

// Note: MCP tools use their own dbPath() because they are in a separate package (main, not cli).
// The CLI's defaultDBPath() in the cli package uses the same canonical path.

func handleSearch(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	args := req.GetArguments()
	query, ok := args["query"].(string)
	if !ok || query == "" {
		return mcplib.NewToolResultError("query is required"), nil
	}

	limit := 25
	if v, ok := args["limit"].(float64); ok && v > 0 {
		limit = int(v)
	}

	db, err := store.OpenReadOnly(dbPath())
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("opening database: %v", err)), nil
	}
	defer db.Close()

	results, err := db.Search(query, limit)
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("search failed: %v", err)), nil
	}

	data, _ := json.MarshalIndent(results, "", "  ")
	return mcplib.NewToolResultText(string(data)), nil
}

// validateReadOnlyQuery gates the MCP sql tool. The agent contract advertised
// to the host is ReadOnlyHintAnnotation(true); a false annotation on a
// mutating tool lets MCP hosts auto-approve writes and is treated as a real
// bug per the project's agent-native security model.
//
// The gate is an allowlist (SELECT or WITH only) applied AFTER stripping the
// leading whitespace, line comments, block comments, and semicolons that
// SQLite itself ignores before parsing. A naive HasPrefix check on a
// keyword blocklist is bypassable by prefixing the dangerous statement with
// "/* x */" or "-- x\n" — TrimSpace strips outer whitespace but does not
// understand SQL comment syntax. Combined with the empirical fact that
// modernc.org/sqlite's mode=ro does NOT block VACUUM INTO (writes a snapshot
// to a new file) or ATTACH DATABASE (opens a separate writable handle),
// such a bypass produces silent exfiltration to an attacker-chosen path.
//
// SELECT and WITH are the only allowed leading keywords. WITH supports
// SELECT-form CTEs; CTE-wrapped writes ("WITH x AS (...) INSERT ...") are
// caught by OpenReadOnly's mode=ro one layer down. PRAGMA, ATTACH, VACUUM,
// and every other DDL/DML keyword fail at this gate before reaching SQLite.
func validateReadOnlyQuery(query string) error {
	upper := strings.ToUpper(stripLeadingSQLNoise(query))
	if !strings.HasPrefix(upper, "SELECT") && !strings.HasPrefix(upper, "WITH") {
		return fmt.Errorf("only SELECT queries are allowed")
	}
	return nil
}

// stripLeadingSQLNoise removes leading whitespace, SQL line comments
// (-- to end of line), block comments (/* ... */), and statement
// separators (;) from query. SQLite skips these before parsing the first
// keyword, so a security gate that does not strip them mismatches what the
// driver actually executes.
func stripLeadingSQLNoise(query string) string {
	for {
		query = strings.TrimLeft(query, " \t\r\n;")
		switch {
		case strings.HasPrefix(query, "--"):
			if idx := strings.IndexByte(query, '\n'); idx >= 0 {
				query = query[idx+1:]
				continue
			}
			return ""
		case strings.HasPrefix(query, "/*"):
			if idx := strings.Index(query[2:], "*/"); idx >= 0 {
				query = query[2+idx+2:]
				continue
			}
			return ""
		default:
			return query
		}
	}
}

func handleSQL(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	args := req.GetArguments()
	query, ok := args["query"].(string)
	if !ok || query == "" {
		return mcplib.NewToolResultError("query is required"), nil
	}

	if err := validateReadOnlyQuery(query); err != nil {
		return mcplib.NewToolResultError(err.Error()), nil
	}

	db, err := store.OpenReadOnly(dbPath())
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("opening database: %v", err)), nil
	}
	defer db.Close()

	rows, err := db.Query(query)
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("query failed: %v", err)), nil
	}
	defer rows.Close()

	cols, _ := rows.Columns()
	var results []map[string]any
	for rows.Next() {
		values := make([]any, len(cols))
		ptrs := make([]any, len(cols))
		for i := range values {
			ptrs[i] = &values[i]
		}
		if err := rows.Scan(ptrs...); err != nil {
			return mcplib.NewToolResultError(fmt.Sprintf("scanning row: %v", err)), nil
		}
		row := make(map[string]any)
		for i, col := range cols {
			row[col] = values[i]
		}
		results = append(results, row)
	}
	// rows.Next() stops on a mid-iteration error without failing the loop, so
	// skipping rows.Err() would return a truncated result set as success.
	if err := rows.Err(); err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("reading rows: %v", err)), nil
	}

	data, _ := json.MarshalIndent(results, "", "  ")
	return mcplib.NewToolResultText(string(data)), nil
}

func handleContext(_ context.Context, _ mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	ctx := map[string]any{
		"api":         "n-central",
		"description": "Every N-central REST endpoint, plus an offline SQLite mirror of your whole org tree, cross-tenant search",
		"archetype":   "project-management",
		"tool_count":  32,
		// tool_surface tells agents which surface a capability lives on.
		"tool_surface": "MCP exposes typed endpoint tools plus a runtime mirror of user-facing CLI commands. Endpoint tools keep typed schemas; command-mirror tools shell out to the companion n-central-pp-cli binary.",
		"auth": map[string]any{
			"type": "bearer_token",
			"env_vars": []map[string]any{
				{
					"name":        "NCENTRAL_JWT",
					"kind":        "per_call",
					"required":    true,
					"sensitive":   true,
					"description": "Set to your API credential.",
				},
			},
			"instructions": "Generate a JSON Web Token for an API-only user in N-central: Administration -> User Management -> Users -> select the API user -> API Access -> GENERATE JSON WEB TOKEN. MFA must be OFF on that user, and watch the password-expiry (default 90 days) which silently invalidates the JWT. Also set N_CENTRAL_BASE_URL to your tenant, e.g. https://yourmsp.ncod.n-able.com/api",
		},
		"resources": []map[string]any{
			{
				"name":        "access-groups",
				"description": "Access groups (device-type and org-unit-type).",
				"endpoints":   []string{"get"},
				"searchable":  true,
			},
			{
				"name":        "customers",
				"description": "Customers (client organizations) in N-central.",
				"endpoints":   []string{"get", "list", "registration-token"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "device-filters",
				"description": "Saved device filters (reusable as filterId on device list calls).",
				"endpoints":   []string{"list"},
				"syncable":    true,
			},
			{
				"name":        "devices",
				"description": "Devices monitored by N-central (workstations, servers, network devices, probes).",
				"endpoints":   []string{"assets", "get", "list", "maintenance", "properties", "status", "tasks"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "org-units",
				"description": "Organization units — the unified tree of service orgs, customers, and sites.",
				"endpoints":   []string{"access-groups", "active-issues", "children", "devices", "get", "job-statuses", "list", "registration-token", "user-roles"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "scheduled-tasks",
				"description": "Scheduled tasks — run scripts/automation policies on devices and track them.",
				"endpoints":   []string{"get", "run", "status"},
				"searchable":  true,
			},
			{
				"name":        "server",
				"description": "Server info and health.",
				"endpoints":   []string{"health", "info"},
			},
			{
				"name":        "service-orgs",
				"description": "Service Organizations — the top level of the N-central org tree.",
				"endpoints":   []string{"customers", "get", "list"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "sites",
				"description": "Sites — the leaf org-unit level under customers.",
				"endpoints":   []string{"get", "list"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "users",
				"description": "N-central users.",
				"endpoints":   []string{"list"},
				"syncable":    true,
			},
		},
		"query_tips": []string{
			"Pagination uses cursor-based paging. Pass pageNumber parameter for subsequent pages.",
			"Control page size with the pageSize parameter (default 100).",
			"Use the sql tool for ad-hoc analysis on synced data. Run sync first to populate the local database.",
			"Use the search tool for full-text search across all synced resources. Faster than iterating list endpoints.",
			"Prefer sql/search over repeated API calls when the data is already synced.",
		},
		// Command-mirror capabilities are exposed through MCP by shelling out
		// to the companion CLI binary.
		"command_mirror_capabilities": []map[string]string{
			{"name": "Multi-server cross-tenant search", "command": "fanout", "description": "Search every configured N-central server at once — find a device, customer", "rationale": "Unions one offline FTS query across every server's local SQLite mirror", "via": "mcp-command-mirror"},
			{"name": "Custom-property drift/coverage audit", "command": "props audit", "description": "Report which devices or org units are missing a required custom-property value", "rationale": "A local anti-join of devices/org-units against synced custom_properties; the API has no 'who is missing this' endpoint.", "via": "mcp-command-mirror"},
			{"name": "Active-issue triage rollup", "command": "triage", "description": "Group active monitoring issues by customer, device", "rationale": "Joins synced active_issues against the org tree in SQLite and collapses duplicate monitors", "via": "mcp-command-mirror"},
			{"name": "JWT / password-expiry guardian", "command": "guardian", "description": "Validate the access token, warn when the API user's password (and thus the JWT) is about to expire", "rationale": "Combines the real /api/auth/validate endpoint with a locally recorded password-set date to pre-empt the #1 documented", "via": "mcp-command-mirror"},
			{"name": "Maintenance-window gap report", "command": "maint coverage", "description": "List devices and sites with no maintenance window before a reboot/patch wave, so nothing reboots in business hours.", "rationale": "A local anti-join of devices/sites against synced maintenance_windows; the API only returns windows per device", "via": "mcp-command-mirror"},
			{"name": "Cross-tenant device locator", "command": "whereis", "description": "Given a device name fragment, return its full path — server, service org, customer", "rationale": "Resolves the fragment against the joined multi-server org-tree + device + active-issue mirror", "via": "mcp-command-mirror"},
		},
		"playbook": []map[string]string{
			{"topic": "Multi-server cross-tenant search", "insight": "Unions one offline FTS query across every server's local SQLite mirror; no single N-central API call spans multiple servers."},
			{"topic": "Custom-property drift/coverage audit", "insight": "A local anti-join of devices/org-units against synced custom_properties; the API has no 'who is missing this' endpoint."},
			{"topic": "Active-issue triage rollup", "insight": "Joins synced active_issues against the org tree in SQLite and collapses duplicate monitors; no single API call returns a grouped, ranked feed."},
			{"topic": "JWT / password-expiry guardian", "insight": "Combines the real /api/auth/validate endpoint with a locally recorded password-set date to pre-empt the #1 documented N-central API outage."},
			{"topic": "Maintenance-window gap report", "insight": "A local anti-join of devices/sites against synced maintenance_windows; the API only returns windows per device, never the gaps."},
			{"topic": "Cross-tenant device locator", "insight": "Resolves the fragment against the joined multi-server org-tree + device + active-issue mirror; answers 'where is this box' without tenant-by-tenant clicking."},
			{"topic": "Finding stale work", "insight": "Use the stale command or sql query to find items not updated recently. More reliable than scanning list results manually."},
			{"topic": "Load analysis", "insight": "When analyzing team workload, filter by assignee and status. Raw counts without status filtering are misleading."},
			{"topic": "Bulk operations", "insight": "For bulk status changes, prefer update endpoints over delete+create. Most PM APIs track history on updates."},
		},
	}
	data, _ := json.MarshalIndent(ctx, "", "  ")
	return mcplib.NewToolResultText(string(data)), nil
}

// RegisterNovelFeatureTools is kept as a compatibility no-op for older MCP
// mains. New generated mains call RegisterTools only; RegisterTools now
// includes the runtime Cobra-tree mirror.
func RegisterNovelFeatureTools(s *server.MCPServer) {
	_ = s
}
