// Copyright 2026 Damien Stevens and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package mcp

import (
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"math"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"time"

	mcplib "github.com/mark3labs/mcp-go/mcp"
	"github.com/mark3labs/mcp-go/server"
	"tactical-rmm-pp-cli/internal/cli"
	"tactical-rmm-pp-cli/internal/client"
	"tactical-rmm-pp-cli/internal/cliutil"
	"tactical-rmm-pp-cli/internal/config"
	"tactical-rmm-pp-cli/internal/mcp/cobratree"
	"tactical-rmm-pp-cli/internal/store"
)

const (
	mcpToolResultMaxBytes = 60000
	mcpToolResultMaxItems = 50
	// MCP hosts can fan out tool calls faster than a human CLI session.
	// Keep them on the same polite-client limiter path instead of disabling
	// pacing with rate=0; users can still tune human CLI calls with --rate-limit.
	defaultMCPRateLimit = 2
)

// RegisterTools registers all API operations as MCP tools.
func RegisterTools(s *server.MCPServer) {
	// Code-orchestration mode — the full surface is covered by two tools
	// (<api>_search + <api>_execute). Endpoint-mirror tools are suppressed.
	RegisterCodeOrchestrationTools(s)
	// Search tool — faster than iterating list endpoints for finding specific items
	s.AddTool(
		mcplib.NewTool("search",
			mcplib.WithDescription("Full-text search across all synced data. Faster than paginating list endpoints. Requires sync first."),
			mcplib.WithString("query", mcplib.Required(), mcplib.Description("Search query (supports FTS5 syntax: AND, OR, NOT, quotes for phrases)")),
			mcplib.WithNumber("limit", mcplib.Description("Max results (default 25)")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
		),
		handleSearch,
	)
	// SQL tool — ad-hoc analysis on synced data without API calls
	s.AddTool(
		mcplib.NewTool("sql",
			mcplib.WithDescription("Run read-only SQL against local database. Use for ad-hoc analysis, aggregations, and joins across synced resources. Requires sync first."),
			mcplib.WithString("query", mcplib.Required(), mcplib.Description("SQL query (SELECT or WITH...SELECT). Synced records live in resources(resource_type, id, data); filter by resource_type and use json_extract on data, e.g. SELECT json_extract(data,'$.name') FROM resources WHERE resource_type='items'.")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
		),
		handleSQL,
	)

	// Context tool — front-loaded domain knowledge for agents.
	// Call this first to understand the API taxonomy, query patterns, and capabilities.
	s.AddTool(
		mcplib.NewTool("context",
			mcplib.WithDescription("Get API domain context: resource taxonomy, auth requirements, query tips, and unique capabilities. Call this first."),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
		),
		handleContext,
	)

	// Runtime Cobra-tree mirror — exposes every user-facing command that is
	// not already covered by a typed endpoint or framework MCP tool.
	cobratree.RegisterAll(s, cli.RootCmd(), cobratree.SiblingCLIPath)
}

type mcpParamBinding struct {
	PublicName string
	WireName   string
	Location   string
}

func formatMCPParamValue(v any) string {
	switch tv := v.(type) {
	case string:
		return tv
	case bool:
		return strconv.FormatBool(tv)
	case float64:
		if math.IsNaN(tv) || math.IsInf(tv, 0) {
			return strconv.FormatFloat(tv, 'f', -1, 64)
		}
		if math.Trunc(tv) == tv && math.Abs(tv) < 1e15 {
			return strconv.FormatInt(int64(tv), 10)
		}
		return strconv.FormatFloat(tv, 'f', -1, 64)
	case float32:
		f := float64(tv)
		if math.IsNaN(f) || math.IsInf(f, 0) {
			return strconv.FormatFloat(f, 'f', -1, 32)
		}
		if math.Trunc(f) == f && math.Abs(f) < 1e15 {
			return strconv.FormatInt(int64(f), 10)
		}
		return strconv.FormatFloat(f, 'f', -1, 32)
	default:
		return fmt.Sprintf("%v", v)
	}
}

// makeAPIHandler creates a generic MCP tool handler for an API endpoint.
func makeAPIHandler(method, pathTemplate string, readOnly bool, binaryResponse bool, headerOverrides map[string]string, bindings []mcpParamBinding, positionalParams []string) server.ToolHandlerFunc {
	return func(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
		c, err := newMCPClient()
		if err != nil {
			return mcplib.NewToolResultError(err.Error()), nil
		}

		// mcp-go v0.47+ made CallToolParams.Arguments an `any` to support
		// non-map payloads; GetArguments() returns the map[string]any shape
		// we rely on here (or an empty map when the payload is something else).
		args := req.GetArguments()

		// positionalParams mixes real URL path params with CLI positional
		// args that map to query params (e.g. `search <query>` -> ?query=);
		// the placeholder check below disambiguates them at runtime.
		path := pathTemplate
		knownArgs := make(map[string]bool, len(bindings))
		pathParams := make(map[string]bool, len(positionalParams))
		params := make(map[string]string)
		bodyArgs := make(map[string]any)
		var headers map[string]string
		if len(headerOverrides) > 0 {
			headers = make(map[string]string, len(headerOverrides)+1)
			for k, v := range headerOverrides {
				headers[k] = v
			}
		}
		if binaryResponse {
			if headers == nil {
				headers = map[string]string{}
			}
			headers[client.BinaryResponseHeader] = "true"
		}
		for _, binding := range bindings {
			knownArgs[binding.PublicName] = true
			v, ok := args[binding.PublicName]
			if !ok {
				continue
			}
			switch binding.Location {
			case "path":
				placeholder := "{" + binding.WireName + "}"
				pathParams[binding.PublicName] = true
				path = strings.Replace(path, placeholder, formatMCPParamValue(v), 1)
			case "body":
				bodyArgs[binding.WireName] = v
			default:
				params[binding.WireName] = formatMCPParamValue(v)
			}
		}
		for _, p := range positionalParams {
			placeholder := "{" + p + "}"
			if !strings.Contains(pathTemplate, placeholder) {
				continue
			}
			pathParams[p] = true
			if v, ok := args[p]; ok {
				path = strings.Replace(path, placeholder, formatMCPParamValue(v), 1)
			}
		}

		for k, v := range args {
			if pathParams[k] || knownArgs[k] {
				continue
			}
			switch method {
			case "POST", "PUT", "PATCH":
				bodyArgs[k] = v
			default:
				params[k] = formatMCPParamValue(v)
			}
		}

		var data json.RawMessage
		switch method {
		case "GET":
			if len(headers) > 0 {
				data, err = c.GetWithHeaders(ctx, path, params, headers)
				break
			}
			data, err = c.Get(ctx, path, params)
		case "POST":
			if len(headers) > 0 {
				if readOnly {
					data, _, err = c.PostQueryWithParamsAndHeaders(ctx, path, params, bodyArgs, headers)
				} else {
					data, _, err = c.PostWithParamsAndHeaders(ctx, path, params, bodyArgs, headers)
				}
				break
			}
			if readOnly {
				data, _, err = c.PostQueryWithParams(ctx, path, params, bodyArgs)
			} else {
				data, _, err = c.PostWithParams(ctx, path, params, bodyArgs)
			}
		case "PUT":
			if len(headers) > 0 {
				data, _, err = c.PutWithParamsAndHeaders(ctx, path, params, bodyArgs, headers)
				break
			}
			data, _, err = c.PutWithParams(ctx, path, params, bodyArgs)
		case "PATCH":
			if len(headers) > 0 {
				data, _, err = c.PatchWithParamsAndHeaders(ctx, path, params, bodyArgs, headers)
				break
			}
			data, _, err = c.PatchWithParams(ctx, path, params, bodyArgs)
		case "DELETE":
			if len(headers) > 0 {
				data, _, err = c.DeleteWithParamsAndHeaders(ctx, path, params, headers)
				break
			}
			data, _, err = c.DeleteWithParams(ctx, path, params)
		default:
			return mcplib.NewToolResultError("unsupported method: " + method), nil
		}

		if err != nil {
			msg := err.Error()
			switch {
			case strings.Contains(msg, "HTTP 409"):
				return mcplib.NewToolResultText("already exists (no-op)"), nil
			case strings.Contains(msg, "HTTP 400") && cliutil.LooksLikeAuthError(msg):
				return mcplib.NewToolResultError("authentication error: " + cliutil.SanitizeErrorBody(msg) +
					"\nhint: the API rejected the request — this usually means auth is missing or invalid." +
					"\n      Set your API key with: export TRMM_API_KEY=\"your-token-here\"" +
					"\n      Run 'tactical-rmm-cli doctor' to check auth status."), nil
			case strings.Contains(msg, "HTTP 401"):
				return mcplib.NewToolResultError("authentication failed: " + cliutil.SanitizeErrorBody(msg) +
					"\nhint: check your API key." +
					"\n      Set your API key with: export TRMM_API_KEY=\"your-token-here\"" +
					"\n      Run 'tactical-rmm-cli doctor' to check auth status."), nil
			case strings.Contains(msg, "HTTP 403"):
				return mcplib.NewToolResultError("permission denied: " + cliutil.SanitizeErrorBody(msg) +
					"\nhint: your credentials are valid but lack access to this resource. Check that they have the required permissions and match the API's expected auth scheme." +
					"\n      Set your API key with: export TRMM_API_KEY=\"your-token-here\"" +
					"\n      Run 'tactical-rmm-cli doctor' to check auth status."), nil
			case strings.Contains(msg, "HTTP 404"):
				if method == "DELETE" {
					return mcplib.NewToolResultText("already deleted (no-op)"), nil
				}
				return mcplib.NewToolResultError("not found: " + msg), nil
			case strings.Contains(msg, "HTTP 429"):
				return mcplib.NewToolResultError("rate limited: " + msg), nil
			default:
				return mcplib.NewToolResultError(msg), nil
			}
		}

		if binaryResponse {
			out, _ := json.Marshal(map[string]any{
				"content_encoding": "base64",
				"data_base64":      base64.StdEncoding.EncodeToString(data),
				"byte_count":       len(data),
			})
			return mcplib.NewToolResultText(string(out)), nil
		}
		return mcpToolResultText(method, data), nil
	}
}

func mcpToolResultText(method string, data json.RawMessage) *mcplib.CallToolResult {
	trimmed := strings.TrimSpace(string(data))
	if strings.EqualFold(method, "GET") && len(trimmed) > 0 && trimmed[0] == '[' {
		var items []json.RawMessage
		if json.Unmarshal(data, &items) == nil {
			return mcplib.NewToolResultText(string(mcpBoundedListEnvelope("items", items, len(data))))
		}
	}
	if len(data) <= mcpToolResultMaxBytes {
		return mcplib.NewToolResultText(string(data))
	}
	if strings.EqualFold(method, "GET") {
		if out, ok := mcpBoundedSingleArrayObject(data); ok {
			return mcplib.NewToolResultText(string(out))
		}
	}
	return mcplib.NewToolResultText(string(mcpOversizedPreviewEnvelope(data)))
}

func mcpBoundedSingleArrayObject(data json.RawMessage) ([]byte, bool) {
	var obj map[string]json.RawMessage
	if json.Unmarshal(data, &obj) != nil {
		return nil, false
	}
	arrayField := ""
	var items []json.RawMessage
	for key, raw := range obj {
		trimmed := strings.TrimSpace(string(raw))
		if len(trimmed) == 0 || trimmed[0] != '[' {
			continue
		}
		var candidate []json.RawMessage
		if json.Unmarshal(raw, &candidate) != nil {
			continue
		}
		if arrayField != "" {
			return nil, false
		}
		arrayField = key
		items = candidate
	}
	if arrayField == "" {
		return nil, false
	}
	build := func(subset []json.RawMessage) any {
		out := make(map[string]any, len(obj)+6)
		for key, raw := range obj {
			if key == arrayField {
				out[key] = subset
				continue
			}
			out[key] = raw
		}
		if len(subset) < len(items) {
			out["_pp_truncated"] = true
			out["_pp_total_count"] = len(items)
			out["_pp_returned_count"] = len(subset)
			out["_pp_original_bytes"] = len(data)
			out["_pp_max_bytes"] = mcpToolResultMaxBytes
			out["_pp_note"] = "Typed MCP endpoint response exceeded the tool result budget. Narrow the request with limit, offset, filters, search/sql, or a command-mirror tool with --agent/--compact/--select."
		}
		return out
	}
	out := mcpFitJSONItems(items, build)
	if len(out) > mcpToolResultMaxBytes {
		return nil, false
	}
	return out, true
}

func mcpBoundedListEnvelope(field string, items []json.RawMessage, originalBytes int) []byte {
	build := func(subset []json.RawMessage) any {
		out := map[string]any{
			"count": len(items),
			field:   subset,
		}
		if len(subset) < len(items) {
			out["truncated"] = true
			out["returned_count"] = len(subset)
			out["original_bytes"] = originalBytes
			out["max_bytes"] = mcpToolResultMaxBytes
			out["note"] = "Typed MCP endpoint response exceeded the tool result budget. Narrow the request with limit, offset, filters, search/sql, or a command-mirror tool with --agent/--compact/--select."
		}
		return out
	}
	return mcpFitJSONItems(items, build)
}

func mcpFitJSONItems(items []json.RawMessage, build func([]json.RawMessage) any) []byte {
	limit := len(items)
	if limit > mcpToolResultMaxItems {
		limit = mcpToolResultMaxItems
	}
	for n := limit; n >= 0; n-- {
		out, err := json.Marshal(build(items[:n]))
		if err != nil {
			continue
		}
		if len(out) <= mcpToolResultMaxBytes || n == 0 {
			return out
		}
	}
	out, _ := json.Marshal(build(items[:0]))
	return out
}

func mcpOversizedPreviewEnvelope(data json.RawMessage) []byte {
	previewBytes := data
	if len(previewBytes) > 4000 {
		previewBytes = previewBytes[:4000]
	}
	out, _ := json.Marshal(map[string]any{
		"truncated":      true,
		"original_bytes": len(data),
		"max_bytes":      mcpToolResultMaxBytes,
		"preview":        string(previewBytes),
		"note":           "Typed MCP endpoint response exceeded the tool result budget and was not a recognized list envelope. Narrow the request with filters, search/sql, or a command-mirror tool with --agent/--compact/--select.",
	})
	return out
}

func newMCPClient() (*client.Client, error) {
	home, _ := os.UserHomeDir()
	cfgPath := filepath.Join(home, ".config", "tactical-rmm-cli", "config.toml")
	cfg, err := config.Load(cfgPath)
	if err != nil {
		return nil, fmt.Errorf("loading config: %w", err)
	}
	c := client.New(cfg, 60*time.Second, defaultMCPRateLimit)
	// Agents calling through MCP need fresh data every call. The on-disk
	// response cache survives across MCP server invocations, so a
	// DELETE/PATCH followed by a GET would otherwise return the
	// pre-mutation snapshot for up to the cache TTL. The interactive CLI
	// constructs its own client and is unaffected.
	c.NoCache = true
	return c, nil
}

func dbPath() string {
	home, _ := os.UserHomeDir()
	return filepath.Join(home, ".local", "share", "tactical-rmm-cli", "data.db")
}

// Note: MCP tools use their own dbPath() because they are in a separate package (main, not cli).
// The CLI's defaultDBPath() in the cli package uses the same canonical path.

func handleSearch(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	args := req.GetArguments()
	query, ok := args["query"].(string)
	if !ok || query == "" {
		return mcplib.NewToolResultError("query is required"), nil
	}

	limit := 25
	if v, ok := args["limit"].(float64); ok && v > 0 {
		limit = int(v)
	}

	db, err := store.OpenReadOnly(dbPath())
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("opening database: %v", err)), nil
	}
	defer db.Close()

	results, err := db.Search(query, limit)
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("search failed: %v", err)), nil
	}

	return toolResultJSON(results)
}

// validateReadOnlyQuery gates the MCP sql tool. The agent contract advertised
// to the host is ReadOnlyHintAnnotation(true); a false annotation on a
// mutating tool lets MCP hosts auto-approve writes and is treated as a real
// bug per the project's agent-native security model.
//
// The gate rejects multi-statement input, then applies an allowlist (SELECT or
// WITH only) AFTER stripping the leading whitespace, line comments, block
// comments, and semicolons that SQLite itself ignores before parsing. A naive
// HasPrefix check on a keyword blocklist is bypassable by prefixing the
// dangerous statement with "/* x */" or "-- x\n"; a naive leading-keyword
// allowlist is bypassable by appending "; ATTACH DATABASE ...". Combined with
// the empirical fact that modernc.org/sqlite's mode=ro does NOT block VACUUM
// INTO (writes a snapshot to a new file) or ATTACH DATABASE (opens a separate
// writable handle), either bypass produces silent exfiltration to an
// attacker-chosen path.
//
// SELECT and WITH are the only allowed leading keywords. WITH supports
// SELECT-form CTEs; CTE-wrapped writes ("WITH x AS (...) INSERT ...") are
// caught by OpenReadOnly's mode=ro one layer down. PRAGMA, ATTACH, VACUUM,
// and every other DDL/DML keyword fail at this gate before reaching SQLite.
func validateReadOnlyQuery(query string) error {
	stripped := stripLeadingSQLNoise(query)
	if hasTrailingSQLStatement(stripped) {
		return fmt.Errorf("only a single SELECT or WITH statement is allowed")
	}
	upper := strings.ToUpper(stripped)
	if !strings.HasPrefix(upper, "SELECT") && !strings.HasPrefix(upper, "WITH") {
		return fmt.Errorf("only SELECT queries are allowed")
	}
	return nil
}

// stripLeadingSQLNoise removes leading whitespace, SQL line comments
// (-- to end of line), block comments (/* ... */), and statement
// separators (;) from query. SQLite skips these before parsing the first
// keyword, so a security gate that does not strip them mismatches what the
// driver actually executes.
func stripLeadingSQLNoise(query string) string {
	for {
		query = strings.TrimLeft(query, " \t\r\n;")
		switch {
		case strings.HasPrefix(query, "--"):
			if idx := strings.IndexByte(query, '\n'); idx >= 0 {
				query = query[idx+1:]
				continue
			}
			return ""
		case strings.HasPrefix(query, "/*"):
			if idx := strings.Index(query[2:], "*/"); idx >= 0 {
				query = query[2+idx+2:]
				continue
			}
			return ""
		default:
			return query
		}
	}
}

// hasTrailingSQLStatement reports whether query contains a statement
// terminator followed by more executable SQL. A trailing semicolon is allowed;
// a second statement is not. Semicolons inside string literals, quoted
// identifiers, bracket identifiers, and comments are ignored to match SQLite's
// parser shape closely enough for this security gate.
func hasTrailingSQLStatement(query string) bool {
	inSingle := false
	inDouble := false
	inBacktick := false
	inBracket := false
	inLineComment := false
	inBlockComment := false

	for i := 0; i < len(query); i++ {
		ch := query[i]
		next := byte(0)
		if i+1 < len(query) {
			next = query[i+1]
		}

		switch {
		case inLineComment:
			if ch == '\n' {
				inLineComment = false
			}
			continue
		case inBlockComment:
			if ch == '*' && next == '/' {
				inBlockComment = false
				i++
			}
			continue
		case inSingle:
			if ch == '\'' {
				if next == '\'' {
					i++
					continue
				}
				inSingle = false
			}
			continue
		case inDouble:
			if ch == '"' {
				if next == '"' {
					i++
					continue
				}
				inDouble = false
			}
			continue
		case inBacktick:
			if ch == '`' {
				if next == '`' {
					i++
					continue
				}
				inBacktick = false
			}
			continue
		case inBracket:
			if ch == ']' {
				inBracket = false
			}
			continue
		}

		switch {
		case ch == '-' && next == '-':
			inLineComment = true
			i++
		case ch == '/' && next == '*':
			inBlockComment = true
			i++
		case ch == '\'':
			inSingle = true
		case ch == '"':
			inDouble = true
		case ch == '`':
			inBacktick = true
		case ch == '[':
			inBracket = true
		case ch == ';':
			if stripLeadingSQLNoise(query[i+1:]) != "" {
				return true
			}
			return false
		}
	}
	return false
}

func handleSQL(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	args := req.GetArguments()
	query, ok := args["query"].(string)
	if !ok || query == "" {
		return mcplib.NewToolResultError("query is required"), nil
	}

	if err := validateReadOnlyQuery(query); err != nil {
		return mcplib.NewToolResultError(err.Error()), nil
	}

	db, err := store.OpenReadOnly(dbPath())
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("opening database: %v", err)), nil
	}
	defer db.Close()

	rows, err := db.Query(query)
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("query failed: %v", err)), nil
	}
	defer rows.Close()

	cols, err := rows.Columns()
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("reading columns: %v", err)), nil
	}
	var results []map[string]any
	for rows.Next() {
		values := make([]any, len(cols))
		ptrs := make([]any, len(cols))
		for i := range values {
			ptrs[i] = &values[i]
		}
		if err := rows.Scan(ptrs...); err != nil {
			return mcplib.NewToolResultError(fmt.Sprintf("scanning row: %v", err)), nil
		}
		row := make(map[string]any)
		for i, col := range cols {
			row[col] = values[i]
		}
		results = append(results, row)
	}
	// rows.Next() stops on a mid-iteration error without failing the loop, so
	// skipping rows.Err() would return a truncated result set as success.
	if err := rows.Err(); err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("reading rows: %v", err)), nil
	}

	return toolResultJSON(results)
}

// toolResultJSON renders v as the indented JSON body of an MCP text result,
// surfacing a marshal failure as a tool error instead of empty content.
func toolResultJSON(v any) (*mcplib.CallToolResult, error) {
	data, err := json.MarshalIndent(v, "", "  ")
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("encoding result: %v", err)), nil
	}
	return mcplib.NewToolResultText(string(data)), nil
}

func handleContext(_ context.Context, _ mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	ctx := map[string]any{
		"api":         "tactical-rmm",
		"description": "Every Tactical RMM endpoint as a typed command, plus an offline SQLite mirror and cross-entity fleet queries the web UI can't express.",
		"archetype":   "project-management",
		"tool_count":  211,
		// tool_surface tells agents which surface a capability lives on.
		"tool_surface": "MCP exposes typed endpoint tools plus a runtime mirror of user-facing CLI commands. Endpoint tools keep typed schemas; command-mirror tools shell out to the companion tactical-rmm-cli binary.",
		"auth": map[string]any{
			"type": "api_key",
			"env_vars": []map[string]any{
				{
					"name":        "TRMM_API_KEY",
					"kind":        "per_call",
					"required":    true,
					"sensitive":   true,
					"description": "Set to your API credential.",
				},
			},
		},
		"resources": []map[string]any{
			{
				"name":        "accounts",
				"description": "Manage accounts",
				"endpoints":   []string{"accounts", "accounts-apikeys", "accounts-apikeys-2", "accounts-apikeys-3", "accounts-reset2fa", "accounts-resetpw", "accounts-roles", "accounts-roles-2", "accounts-roles-3", "accounts-roles-4", "accounts-roles-5", "accounts-sessions", "accounts-users", "accounts-users-10", "accounts-users-2", "accounts-users-3", "accounts-users-4", "accounts-users-5", "accounts-users-6", "accounts-users-7", "accounts-users-8", "accounts-users-9"},
				"syncable":    true,
			},
			{
				"name":        "agents",
				"description": "Manage agents",
				"endpoints":   []string{"agents", "agents-actions", "agents-agentid", "agents-agentid-2", "agents-agentid-3", "agents-bulkrecovery", "agents-history", "agents-installer", "agents-maintenance", "agents-notes", "agents-notes-2", "agents-notes-3", "agents-notes-4", "agents-notes-5", "agents-scripthistory", "agents-update", "agents-versions"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "alerts",
				"description": "Manage alerts",
				"endpoints":   []string{"alerts", "alerts-bulk", "alerts-endpoint", "alerts-pk", "alerts-pk-2", "alerts-pk-3", "alerts-templates", "alerts-templates-2", "alerts-templates-3", "alerts-templates-4", "alerts-templates-5", "alerts-templates-6"},
				"syncable":    true,
			},
			{
				"name":        "automation",
				"description": "Manage automation",
				"endpoints":   []string{"automation", "automation-checks", "automation-patchpolicy", "automation-patchpolicy-2", "automation-patchpolicy-3", "automation-patchpolicy-4", "automation-patchpolicy-5", "automation-patchpolicy-6", "automation-policies", "automation-policies-2", "automation-policies-3", "automation-policies-4", "automation-policies-5", "automation-policies-6", "automation-policies-7", "automation-policies-8", "automation-policies-9", "automation-tasks", "automation-tasks-2", "automation-tasks-3", "automation-tasks-4"},
				"syncable":    true,
			},
			{
				"name":        "autotasks",
				"description": "Manage autotasks",
				"endpoints":   []string{"autotasks", "autotasks-endpoint", "autotasks-pk", "autotasks-pk-2", "autotasks-pk-3"},
				"syncable":    true,
			},
			{
				"name":        "checks",
				"description": "Manage checks",
				"endpoints":   []string{"checks", "checks-endpoint", "checks-pk", "checks-pk-2", "checks-pk-3"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "clients",
				"description": "Manage clients",
				"endpoints":   []string{"clients", "clients-deployments", "clients-deployments-2", "clients-deployments-3", "clients-deployments-4", "clients-deployments-5", "clients-deployments-6", "clients-endpoint", "clients-pk", "clients-pk-2", "clients-pk-3", "clients-sites", "clients-sites-2", "clients-sites-3", "clients-sites-4", "clients-sites-5"},
				"syncable":    true,
			},
			{
				"name":        "core",
				"description": "Manage core",
				"endpoints":   []string{"core", "core-codesign", "core-codesign-2", "core-codesign-3", "core-codesign-4", "core-customfields", "core-customfields-2", "core-customfields-3", "core-customfields-4", "core-customfields-5", "core-customfields-6", "core-dashinfo", "core-emailtest", "core-keystore", "core-keystore-2", "core-keystore-3", "core-keystore-4", "core-openai", "core-schedules", "core-schedules-2", "core-schedules-3", "core-schedules-4", "core-servermaintenance", "core-settings", "core-settings-2", "core-smstest", "core-status", "core-urlaction", "core-urlaction-2", "core-urlaction-3", "core-urlaction-4", "core-urlaction-5", "core-urlaction-6", "core-v2", "core-version", "core-webtermperms"},
				"syncable":    true,
			},
			{
				"name":        "logs",
				"description": "Manage logs",
				"endpoints":   []string{"logs", "logs-debug", "logs-pendingactions", "logs-pendingactions-2", "logs-pendingactions-3", "logs-pendingactions-4"},
				"syncable":    true,
			},
			{
				"name":        "scripts",
				"description": "Manage scripts",
				"endpoints":   []string{"scripts", "scripts-endpoint", "scripts-pk", "scripts-pk-2", "scripts-pk-3", "scripts-snippets", "scripts-snippets-2", "scripts-snippets-3", "scripts-snippets-4", "scripts-snippets-5"},
				"syncable":    true,
			},
			{
				"name":        "services",
				"description": "Manage services",
				"endpoints":   []string{"services", "services-agentid", "services-agentid-2", "services-agentid-3"},
				"searchable":  true,
			},
			{
				"name":        "software",
				"description": "Manage software",
				"endpoints":   []string{"software", "software-agentid", "software-agentid-2", "software-agentid-3", "software-chocos", "software-endpoint", "software-endpoint-2"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "winupdate",
				"description": "Manage winupdate",
				"endpoints":   []string{"winupdate", "winupdate-pk"},
				"searchable":  true,
			},
		},
		"query_tips": []string{
			"Pagination uses cursor-based paging. Pass after parameter for subsequent pages.",
			"Control page size with the limit parameter (default 100).",
			"Use the sql tool for ad-hoc analysis on synced data. Run sync first to populate the local database.",
			"Use the search tool for full-text search across all synced resources. Faster than iterating list endpoints.",
			"Prefer sql/search over repeated API calls when the data is already synced.",
		},
		// Command-mirror capabilities are exposed through MCP by shelling out
		// to the companion CLI binary.
		"command_mirror_capabilities": []map[string]string{
			{"name": "Fleet health snapshot", "command": "fleet health", "description": "Whole-fleet posture in one command: online/offline/overdue agents, failing checks, pending reboots, outstanding patches, active alerts.", "rationale": "A local join across agents, checks, windows updates and alerts that no single API call returns.", "via": "mcp-command-mirror"},
			{"name": "Attention triage", "command": "triage", "description": "Ranked list of agents needing attention, scored across offline state, failing checks, reboots and patches.", "rationale": "Cross-entity scoring over the local store; the UI shows each signal on a separate screen.", "via": "mcp-command-mirror"},
			{"name": "Stale-agent detection", "command": "agents stale", "description": "Agents whose last check-in exceeds a threshold, with client and site.", "rationale": "Time-windowed aggregation on last_seen joined to client/site.", "via": "mcp-command-mirror"},
			{"name": "Patch posture rollup", "command": "patch posture", "description": "Per-client/site rollup of pending Windows updates and reboots.", "rationale": "Aggregation across agent and client joins.", "via": "mcp-command-mirror"},
			{"name": "Bulk remote run by filter", "command": "agents bulk-run", "description": "Run a script/command across every agent matching a local-store filter (client/site/os/online).", "rationale": "Local filtering plus fan-out execution; the UI runs scripts one agent at a time.", "via": "mcp-command-mirror"},
			{"name": "Check flapping detection", "command": "checks flapping", "description": "Checks that repeatedly flipped pass/fail within a window, from local snapshots.", "rationale": "Needs historical check-status snapshots the API does not retain.", "via": "mcp-command-mirror"},
			{"name": "Alert digest", "command": "alerts digest", "description": "Grouped alert summary by client/severity/type over a time window.", "rationale": "Time-windowed dedup/group the flat alert list cannot produce.", "via": "mcp-command-mirror"},
			{"name": "Fleet what-changed", "command": "since", "description": "What changed across the fleet since a window: new alerts, newly-offline agents.", "rationale": "Time-window diff over synced timestamps.", "via": "mcp-command-mirror"},
			{"name": "Software / vulnerability sweep", "command": "software find", "description": "Which agents have a given software package installed across the fleet.", "rationale": "Cross-agent inventory join; the UI searches per-agent.", "via": "mcp-command-mirror"},
			{"name": "Monitoring coverage gaps", "command": "coverage", "description": "Agents missing checks (unmonitored endpoints).", "rationale": "Anti-join of agents against checks.", "via": "mcp-command-mirror"},
			{"name": "Maintenance-mode sweep", "command": "maintenance set", "description": "Put a filtered cohort of agents into maintenance mode in one command, with a reminder window (re-run with --clear to end it; Tactical RMM has no server-side expiry).", "rationale": "Requires local-store cohort filtering plus fan-out the web UI can't express - no filtered maintenance toggle exists.", "via": "mcp-command-mirror"},
			{"name": "Pending actions backlog", "command": "actions pending", "description": "Queued agent actions across the fleet grouped by agent and age, so stuck dispatches surface. Live fan-out: requires TRMM_API_KEY (agent list comes from the local store).", "rationale": "The pending-actions endpoint is per-agent; the cross-fleet age grouping only exists in the local mirror.", "via": "mcp-command-mirror"},
			{"name": "Check-failure leaderboard", "command": "checks worst", "description": "Failing checks ranked by blast radius - how many agents are red on each check.", "rationale": "A group-by across synced checks and agents that no single API call returns.", "via": "mcp-command-mirror"},
			{"name": "Client posture scorecard", "command": "clients scorecard", "description": "One posture row per client: agent count, online share, failing checks, pending patches, open alerts.", "rationale": "A five-signal join across agents, checks, updates and alerts grouped by client - impossible from the flat API.", "via": "mcp-command-mirror"},
			{"name": "Service-down sweep", "command": "services down", "description": "Agents where a named Windows service is stopped, across the whole fleet. Live fan-out: requires TRMM_API_KEY (agent list comes from the local store).", "rationale": "Cross-agent filter over synced service rows; the web UI only shows services per-agent.", "via": "mcp-command-mirror"},
		},
		"playbook": []map[string]string{
			{"topic": "Fleet health snapshot", "insight": "A local join across agents, checks, windows updates and alerts that no single API call returns."},
			{"topic": "Attention triage", "insight": "Cross-entity scoring over the local store; the UI shows each signal on a separate screen."},
			{"topic": "Stale-agent detection", "insight": "Time-windowed aggregation on last_seen joined to client/site."},
			{"topic": "Patch posture rollup", "insight": "Aggregation across agent and client joins."},
			{"topic": "Bulk remote run by filter", "insight": "Local filtering plus fan-out execution; the UI runs scripts one agent at a time."},
			{"topic": "Check flapping detection", "insight": "Needs historical check-status snapshots the API does not retain."},
			{"topic": "Alert digest", "insight": "Time-windowed dedup/group the flat alert list cannot produce."},
			{"topic": "Fleet what-changed", "insight": "Time-window diff over synced timestamps."},
			{"topic": "Software / vulnerability sweep", "insight": "Cross-agent inventory join; the UI searches per-agent."},
			{"topic": "Monitoring coverage gaps", "insight": "Anti-join of agents against checks."},
			{"topic": "Maintenance-mode sweep", "insight": "Requires local-store cohort filtering plus fan-out the web UI can't express - no filtered maintenance toggle exists."},
			{"topic": "Pending actions backlog", "insight": "The pending-actions endpoint is per-agent; the cross-fleet age grouping only exists in the local mirror."},
			{"topic": "Check-failure leaderboard", "insight": "A group-by across synced checks and agents that no single API call returns."},
			{"topic": "Client posture scorecard", "insight": "A five-signal join across agents, checks, updates and alerts grouped by client - impossible from the flat API."},
			{"topic": "Service-down sweep", "insight": "Cross-agent filter over synced service rows; the web UI only shows services per-agent."},
			{"topic": "Finding stale work", "insight": "Use the stale command or sql query to find items not updated recently. More reliable than scanning list results manually."},
			{"topic": "Load analysis", "insight": "When analyzing team workload, filter by assignee and status. Raw counts without status filtering are misleading."},
			{"topic": "Bulk operations", "insight": "For bulk status changes, prefer update endpoints over delete+create. Most PM APIs track history on updates."},
		},
	}
	return toolResultJSON(ctx)
}

// RegisterNovelFeatureTools is kept as a compatibility no-op for older MCP
// mains. New generated mains call RegisterTools only; RegisterTools now
// includes the runtime Cobra-tree mirror.
func RegisterNovelFeatureTools(s *server.MCPServer) {
	_ = s
}
