// Copyright 2026 Damien Stevens and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package mcp

import (
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"math"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"time"

	mcplib "github.com/mark3labs/mcp-go/mcp"
	"github.com/mark3labs/mcp-go/server"
	"salesbuildr-pp-cli/internal/cli"
	"salesbuildr-pp-cli/internal/client"
	"salesbuildr-pp-cli/internal/cliutil"
	"salesbuildr-pp-cli/internal/config"
	"salesbuildr-pp-cli/internal/mcp/cobratree"
	"salesbuildr-pp-cli/internal/store"
)

const (
	mcpToolResultMaxBytes = 60000
	mcpToolResultMaxItems = 50
	// MCP hosts can fan out tool calls faster than a human CLI session.
	// Keep them on the same polite-client limiter path instead of disabling
	// pacing with rate=0; users can still tune human CLI calls with --rate-limit.
	defaultMCPRateLimit = 2
)

// RegisterTools registers all API operations as MCP tools.
func RegisterTools(s *server.MCPServer) {
	// Code-orchestration mode — the full surface is covered by two tools
	// (<api>_search + <api>_execute). Endpoint-mirror tools are suppressed.
	RegisterCodeOrchestrationTools(s)
	// Search tool — faster than iterating list endpoints for finding specific items
	s.AddTool(
		mcplib.NewTool("search",
			mcplib.WithDescription("Full-text search across all synced data. Faster than paginating list endpoints. Requires sync first."),
			mcplib.WithString("query", mcplib.Required(), mcplib.Description("Search query (supports FTS5 syntax: AND, OR, NOT, quotes for phrases)")),
			mcplib.WithNumber("limit", mcplib.Description("Max results (default 25)")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
		),
		handleSearch,
	)
	// SQL tool — ad-hoc analysis on synced data without API calls
	s.AddTool(
		mcplib.NewTool("sql",
			mcplib.WithDescription("Run read-only SQL against local database. Use for ad-hoc analysis, aggregations, and joins across synced resources. Requires sync first."),
			mcplib.WithString("query", mcplib.Required(), mcplib.Description("SQL query (SELECT or WITH...SELECT). Synced records live in resources(resource_type, id, data); filter by resource_type and use json_extract on data, e.g. SELECT json_extract(data,'$.name') FROM resources WHERE resource_type='items'.")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
		),
		handleSQL,
	)

	// Context tool — front-loaded domain knowledge for agents.
	// Call this first to understand the API taxonomy, query patterns, and capabilities.
	s.AddTool(
		mcplib.NewTool("context",
			mcplib.WithDescription("Get API domain context: resource taxonomy, auth requirements, query tips, and unique capabilities. Call this first."),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
		),
		handleContext,
	)

	// Runtime Cobra-tree mirror — exposes every user-facing command that is
	// not already covered by a typed endpoint or framework MCP tool.
	cobratree.RegisterAll(s, cli.RootCmd(), cobratree.SiblingCLIPath)
}

type mcpParamBinding struct {
	PublicName string
	WireName   string
	Location   string
	BodyPath   []string
}

func formatMCPParamValue(v any) string {
	switch tv := v.(type) {
	case string:
		return tv
	case bool:
		return strconv.FormatBool(tv)
	case float64:
		if math.IsNaN(tv) || math.IsInf(tv, 0) {
			return strconv.FormatFloat(tv, 'f', -1, 64)
		}
		if math.Trunc(tv) == tv && math.Abs(tv) < 1e15 {
			return strconv.FormatInt(int64(tv), 10)
		}
		return strconv.FormatFloat(tv, 'f', -1, 64)
	case float32:
		f := float64(tv)
		if math.IsNaN(f) || math.IsInf(f, 0) {
			return strconv.FormatFloat(f, 'f', -1, 32)
		}
		if math.Trunc(f) == f && math.Abs(f) < 1e15 {
			return strconv.FormatInt(int64(f), 10)
		}
		return strconv.FormatFloat(f, 'f', -1, 32)
	default:
		return fmt.Sprintf("%v", v)
	}
}
func setNestedBodyArg(body map[string]any, path []string, value any) {
	if len(path) == 0 {
		return
	}
	if len(path) == 1 {
		body[path[0]] = value
		return
	}
	current := body
	for _, key := range path[:len(path)-1] {
		next, ok := current[key].(map[string]any)
		if !ok {
			next = map[string]any{}
			current[key] = next
		}
		current = next
	}
	current[path[len(path)-1]] = value
}

// makeAPIHandler creates a generic MCP tool handler for an API endpoint.
func makeAPIHandler(method, pathTemplate string, readOnly bool, binaryResponse bool, headerOverrides map[string]string, bindings []mcpParamBinding, positionalParams []string) server.ToolHandlerFunc {
	return func(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
		c, err := newMCPClient()
		if err != nil {
			return mcplib.NewToolResultError(err.Error()), nil
		}

		// mcp-go v0.47+ made CallToolParams.Arguments an `any` to support
		// non-map payloads; GetArguments() returns the map[string]any shape
		// we rely on here (or an empty map when the payload is something else).
		args := req.GetArguments()

		// positionalParams mixes real URL path params with CLI positional
		// args that map to query params (e.g. `search <query>` -> ?query=);
		// the placeholder check below disambiguates them at runtime.
		path := pathTemplate
		knownArgs := make(map[string]bool, len(bindings))
		pathParams := make(map[string]bool, len(positionalParams))
		params := make(map[string]string)
		bodyArgs := make(map[string]any)
		var headers map[string]string
		if len(headerOverrides) > 0 {
			headers = make(map[string]string, len(headerOverrides)+1)
			for k, v := range headerOverrides {
				headers[k] = v
			}
		}
		if binaryResponse {
			if headers == nil {
				headers = map[string]string{}
			}
			headers[client.BinaryResponseHeader] = "true"
		}
		for _, binding := range bindings {
			knownArgs[binding.PublicName] = true
			v, ok := args[binding.PublicName]
			if !ok {
				continue
			}
			switch binding.Location {
			case "path":
				placeholder := "{" + binding.WireName + "}"
				pathParams[binding.PublicName] = true
				path = strings.Replace(path, placeholder, formatMCPParamValue(v), 1)
			case "body":
				if len(binding.BodyPath) > 0 {
					setNestedBodyArg(bodyArgs, binding.BodyPath, v)
				} else {
					bodyArgs[binding.WireName] = v
				}
			default:
				params[binding.WireName] = formatMCPParamValue(v)
			}
		}
		for _, p := range positionalParams {
			placeholder := "{" + p + "}"
			if !strings.Contains(pathTemplate, placeholder) {
				continue
			}
			pathParams[p] = true
			if v, ok := args[p]; ok {
				path = strings.Replace(path, placeholder, formatMCPParamValue(v), 1)
			}
		}

		for k, v := range args {
			if pathParams[k] || knownArgs[k] {
				continue
			}
			switch method {
			case "POST", "PUT", "PATCH":
				bodyArgs[k] = v
			default:
				params[k] = formatMCPParamValue(v)
			}
		}

		var data json.RawMessage
		switch method {
		case "GET":
			if len(headers) > 0 {
				data, err = c.GetWithHeaders(ctx, path, params, headers)
				break
			}
			data, err = c.Get(ctx, path, params)
		case "POST":
			if len(headers) > 0 {
				if readOnly {
					data, _, err = c.PostQueryWithParamsAndHeaders(ctx, path, params, bodyArgs, headers)
				} else {
					data, _, err = c.PostWithParamsAndHeaders(ctx, path, params, bodyArgs, headers)
				}
				break
			}
			if readOnly {
				data, _, err = c.PostQueryWithParams(ctx, path, params, bodyArgs)
			} else {
				data, _, err = c.PostWithParams(ctx, path, params, bodyArgs)
			}
		case "PUT":
			if len(headers) > 0 {
				data, _, err = c.PutWithParamsAndHeaders(ctx, path, params, bodyArgs, headers)
				break
			}
			data, _, err = c.PutWithParams(ctx, path, params, bodyArgs)
		case "PATCH":
			if len(headers) > 0 {
				data, _, err = c.PatchWithParamsAndHeaders(ctx, path, params, bodyArgs, headers)
				break
			}
			data, _, err = c.PatchWithParams(ctx, path, params, bodyArgs)
		case "DELETE":
			if len(headers) > 0 {
				data, _, err = c.DeleteWithParamsAndHeaders(ctx, path, params, headers)
				break
			}
			data, _, err = c.DeleteWithParams(ctx, path, params)
		default:
			return mcplib.NewToolResultError("unsupported method: " + method), nil
		}

		if err != nil {
			msg := err.Error()
			switch {
			case strings.Contains(msg, "HTTP 409"):
				return mcplib.NewToolResultText("already exists (no-op)"), nil
			case strings.Contains(msg, "HTTP 400") && cliutil.LooksLikeAuthError(msg):
				return mcplib.NewToolResultError("authentication error: " + cliutil.SanitizeErrorBody(msg) +
					"\nhint: the API rejected the request — this usually means auth is missing or invalid." +
					"\n      Set your API key with: export SALESBUILDR_API_KEY=\"your-token-here\"" +
					"\n      Run 'salesbuildr-cli doctor' to check auth status."), nil
			case strings.Contains(msg, "HTTP 401"):
				return mcplib.NewToolResultError("authentication failed: " + cliutil.SanitizeErrorBody(msg) +
					"\nhint: check your API key." +
					"\n      Set your API key with: export SALESBUILDR_API_KEY=\"your-token-here\"" +
					"\n      Run 'salesbuildr-cli doctor' to check auth status."), nil
			case strings.Contains(msg, "HTTP 403"):
				return mcplib.NewToolResultError("permission denied: " + cliutil.SanitizeErrorBody(msg) +
					"\nhint: your credentials are valid but lack access to this resource. Check that they have the required permissions and match the API's expected auth scheme." +
					"\n      Set your API key with: export SALESBUILDR_API_KEY=\"your-token-here\"" +
					"\n      Run 'salesbuildr-cli doctor' to check auth status."), nil
			case strings.Contains(msg, "HTTP 404"):
				if method == "DELETE" {
					return mcplib.NewToolResultText("already deleted (no-op)"), nil
				}
				return mcplib.NewToolResultError("not found: " + msg), nil
			case strings.Contains(msg, "HTTP 429"):
				return mcplib.NewToolResultError("rate limited: " + msg), nil
			default:
				return mcplib.NewToolResultError(msg), nil
			}
		}

		if binaryResponse {
			out, _ := json.Marshal(map[string]any{
				"content_encoding": "base64",
				"data_base64":      base64.StdEncoding.EncodeToString(data),
				"byte_count":       len(data),
			})
			return mcplib.NewToolResultText(string(out)), nil
		}
		return mcpToolResultText(method, data), nil
	}
}

func mcpToolResultText(method string, data json.RawMessage) *mcplib.CallToolResult {
	trimmed := strings.TrimSpace(string(data))
	if strings.EqualFold(method, "GET") && len(trimmed) > 0 && trimmed[0] == '[' {
		var items []json.RawMessage
		if json.Unmarshal(data, &items) == nil {
			return mcplib.NewToolResultText(string(mcpBoundedListEnvelope("items", items, len(data))))
		}
	}
	if len(data) <= mcpToolResultMaxBytes {
		return mcplib.NewToolResultText(string(data))
	}
	if strings.EqualFold(method, "GET") {
		if out, ok := mcpBoundedSingleArrayObject(data); ok {
			return mcplib.NewToolResultText(string(out))
		}
	}
	return mcplib.NewToolResultText(string(mcpOversizedPreviewEnvelope(data)))
}

func mcpBoundedSingleArrayObject(data json.RawMessage) ([]byte, bool) {
	var obj map[string]json.RawMessage
	if json.Unmarshal(data, &obj) != nil {
		return nil, false
	}
	arrayField := ""
	var items []json.RawMessage
	for key, raw := range obj {
		trimmed := strings.TrimSpace(string(raw))
		if len(trimmed) == 0 || trimmed[0] != '[' {
			continue
		}
		var candidate []json.RawMessage
		if json.Unmarshal(raw, &candidate) != nil {
			continue
		}
		if arrayField != "" {
			return nil, false
		}
		arrayField = key
		items = candidate
	}
	if arrayField == "" {
		return nil, false
	}
	build := func(subset []json.RawMessage) any {
		out := make(map[string]any, len(obj)+6)
		for key, raw := range obj {
			if key == arrayField {
				out[key] = subset
				continue
			}
			out[key] = raw
		}
		if len(subset) < len(items) {
			out["_pp_truncated"] = true
			out["_pp_total_count"] = len(items)
			out["_pp_returned_count"] = len(subset)
			out["_pp_original_bytes"] = len(data)
			out["_pp_max_bytes"] = mcpToolResultMaxBytes
			out["_pp_note"] = "Typed MCP endpoint response exceeded the tool result budget. Narrow the request with limit, offset, filters, search/sql, or a command-mirror tool with --agent/--compact/--select."
		}
		return out
	}
	out := mcpFitJSONItems(items, build)
	if len(out) > mcpToolResultMaxBytes {
		return nil, false
	}
	return out, true
}

func mcpBoundedListEnvelope(field string, items []json.RawMessage, originalBytes int) []byte {
	build := func(subset []json.RawMessage) any {
		out := map[string]any{
			"count": len(items),
			field:   subset,
		}
		if len(subset) < len(items) {
			out["truncated"] = true
			out["returned_count"] = len(subset)
			out["original_bytes"] = originalBytes
			out["max_bytes"] = mcpToolResultMaxBytes
			out["note"] = "Typed MCP endpoint response exceeded the tool result budget. Narrow the request with limit, offset, filters, search/sql, or a command-mirror tool with --agent/--compact/--select."
		}
		return out
	}
	return mcpFitJSONItems(items, build)
}

func mcpFitJSONItems(items []json.RawMessage, build func([]json.RawMessage) any) []byte {
	limit := len(items)
	if limit > mcpToolResultMaxItems {
		limit = mcpToolResultMaxItems
	}
	for n := limit; n >= 0; n-- {
		out, err := json.Marshal(build(items[:n]))
		if err != nil {
			continue
		}
		if len(out) <= mcpToolResultMaxBytes || n == 0 {
			return out
		}
	}
	out, _ := json.Marshal(build(items[:0]))
	return out
}

func mcpOversizedPreviewEnvelope(data json.RawMessage) []byte {
	previewBytes := data
	if len(previewBytes) > 4000 {
		previewBytes = previewBytes[:4000]
	}
	out, _ := json.Marshal(map[string]any{
		"truncated":      true,
		"original_bytes": len(data),
		"max_bytes":      mcpToolResultMaxBytes,
		"preview":        string(previewBytes),
		"note":           "Typed MCP endpoint response exceeded the tool result budget and was not a recognized list envelope. Narrow the request with filters, search/sql, or a command-mirror tool with --agent/--compact/--select.",
	})
	return out
}

func newMCPClient() (*client.Client, error) {
	home, _ := os.UserHomeDir()
	cfgPath := filepath.Join(home, ".config", "salesbuildr-cli", "config.toml")
	cfg, err := config.Load(cfgPath)
	if err != nil {
		return nil, fmt.Errorf("loading config: %w", err)
	}
	c := client.New(cfg, 60*time.Second, defaultMCPRateLimit)
	// Agents calling through MCP need fresh data every call. The on-disk
	// response cache survives across MCP server invocations, so a
	// DELETE/PATCH followed by a GET would otherwise return the
	// pre-mutation snapshot for up to the cache TTL. The interactive CLI
	// constructs its own client and is unaffected.
	c.NoCache = true
	return c, nil
}

func dbPath() string {
	home, _ := os.UserHomeDir()
	return filepath.Join(home, ".local", "share", "salesbuildr-cli", "data.db")
}

// Note: MCP tools use their own dbPath() because they are in a separate package (main, not cli).
// The CLI's defaultDBPath() in the cli package uses the same canonical path.

func handleSearch(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	args := req.GetArguments()
	query, ok := args["query"].(string)
	if !ok || query == "" {
		return mcplib.NewToolResultError("query is required"), nil
	}

	limit := 25
	if v, ok := args["limit"].(float64); ok && v > 0 {
		limit = int(v)
	}

	db, err := store.OpenReadOnly(dbPath())
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("opening database: %v", err)), nil
	}
	defer db.Close()

	results, err := db.Search(query, limit)
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("search failed: %v", err)), nil
	}

	return toolResultJSON(results)
}

// validateReadOnlyQuery gates the MCP sql tool. The agent contract advertised
// to the host is ReadOnlyHintAnnotation(true); a false annotation on a
// mutating tool lets MCP hosts auto-approve writes and is treated as a real
// bug per the project's agent-native security model.
//
// The gate rejects multi-statement input, then applies an allowlist (SELECT or
// WITH only) AFTER stripping the leading whitespace, line comments, block
// comments, and semicolons that SQLite itself ignores before parsing. A naive
// HasPrefix check on a keyword blocklist is bypassable by prefixing the
// dangerous statement with "/* x */" or "-- x\n"; a naive leading-keyword
// allowlist is bypassable by appending "; ATTACH DATABASE ...". Combined with
// the empirical fact that modernc.org/sqlite's mode=ro does NOT block VACUUM
// INTO (writes a snapshot to a new file) or ATTACH DATABASE (opens a separate
// writable handle), either bypass produces silent exfiltration to an
// attacker-chosen path.
//
// SELECT and WITH are the only allowed leading keywords. WITH supports
// SELECT-form CTEs; CTE-wrapped writes ("WITH x AS (...) INSERT ...") are
// caught by OpenReadOnly's mode=ro one layer down. PRAGMA, ATTACH, VACUUM,
// and every other DDL/DML keyword fail at this gate before reaching SQLite.
func validateReadOnlyQuery(query string) error {
	stripped := stripLeadingSQLNoise(query)
	if hasTrailingSQLStatement(stripped) {
		return fmt.Errorf("only a single SELECT or WITH statement is allowed")
	}
	upper := strings.ToUpper(stripped)
	if !strings.HasPrefix(upper, "SELECT") && !strings.HasPrefix(upper, "WITH") {
		return fmt.Errorf("only SELECT queries are allowed")
	}
	return nil
}

// stripLeadingSQLNoise removes leading whitespace, SQL line comments
// (-- to end of line), block comments (/* ... */), and statement
// separators (;) from query. SQLite skips these before parsing the first
// keyword, so a security gate that does not strip them mismatches what the
// driver actually executes.
func stripLeadingSQLNoise(query string) string {
	for {
		query = strings.TrimLeft(query, " \t\r\n;")
		switch {
		case strings.HasPrefix(query, "--"):
			if idx := strings.IndexByte(query, '\n'); idx >= 0 {
				query = query[idx+1:]
				continue
			}
			return ""
		case strings.HasPrefix(query, "/*"):
			if idx := strings.Index(query[2:], "*/"); idx >= 0 {
				query = query[2+idx+2:]
				continue
			}
			return ""
		default:
			return query
		}
	}
}

// hasTrailingSQLStatement reports whether query contains a statement
// terminator followed by more executable SQL. A trailing semicolon is allowed;
// a second statement is not. Semicolons inside string literals, quoted
// identifiers, bracket identifiers, and comments are ignored to match SQLite's
// parser shape closely enough for this security gate.
func hasTrailingSQLStatement(query string) bool {
	inSingle := false
	inDouble := false
	inBacktick := false
	inBracket := false
	inLineComment := false
	inBlockComment := false

	for i := 0; i < len(query); i++ {
		ch := query[i]
		next := byte(0)
		if i+1 < len(query) {
			next = query[i+1]
		}

		switch {
		case inLineComment:
			if ch == '\n' {
				inLineComment = false
			}
			continue
		case inBlockComment:
			if ch == '*' && next == '/' {
				inBlockComment = false
				i++
			}
			continue
		case inSingle:
			if ch == '\'' {
				if next == '\'' {
					i++
					continue
				}
				inSingle = false
			}
			continue
		case inDouble:
			if ch == '"' {
				if next == '"' {
					i++
					continue
				}
				inDouble = false
			}
			continue
		case inBacktick:
			if ch == '`' {
				if next == '`' {
					i++
					continue
				}
				inBacktick = false
			}
			continue
		case inBracket:
			if ch == ']' {
				inBracket = false
			}
			continue
		}

		switch {
		case ch == '-' && next == '-':
			inLineComment = true
			i++
		case ch == '/' && next == '*':
			inBlockComment = true
			i++
		case ch == '\'':
			inSingle = true
		case ch == '"':
			inDouble = true
		case ch == '`':
			inBacktick = true
		case ch == '[':
			inBracket = true
		case ch == ';':
			if stripLeadingSQLNoise(query[i+1:]) != "" {
				return true
			}
			return false
		}
	}
	return false
}

func handleSQL(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	args := req.GetArguments()
	query, ok := args["query"].(string)
	if !ok || query == "" {
		return mcplib.NewToolResultError("query is required"), nil
	}

	if err := validateReadOnlyQuery(query); err != nil {
		return mcplib.NewToolResultError(err.Error()), nil
	}

	db, err := store.OpenReadOnly(dbPath())
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("opening database: %v", err)), nil
	}
	defer db.Close()

	rows, err := db.Query(query)
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("query failed: %v", err)), nil
	}
	defer rows.Close()

	cols, err := rows.Columns()
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("reading columns: %v", err)), nil
	}
	var results []map[string]any
	for rows.Next() {
		values := make([]any, len(cols))
		ptrs := make([]any, len(cols))
		for i := range values {
			ptrs[i] = &values[i]
		}
		if err := rows.Scan(ptrs...); err != nil {
			return mcplib.NewToolResultError(fmt.Sprintf("scanning row: %v", err)), nil
		}
		row := make(map[string]any)
		for i, col := range cols {
			row[col] = values[i]
		}
		results = append(results, row)
	}
	// rows.Next() stops on a mid-iteration error without failing the loop, so
	// skipping rows.Err() would return a truncated result set as success.
	if err := rows.Err(); err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("reading rows: %v", err)), nil
	}

	return toolResultJSON(results)
}

// toolResultJSON renders v as the indented JSON body of an MCP text result,
// surfacing a marshal failure as a tool error instead of empty content.
func toolResultJSON(v any) (*mcplib.CallToolResult, error) {
	data, err := json.MarshalIndent(v, "", "  ")
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("encoding result: %v", err)), nil
	}
	return mcplib.NewToolResultText(string(data)), nil
}

func handleContext(_ context.Context, _ mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	ctx := map[string]any{
		"api":         "salesbuildr",
		"description": "Every Salesbuildr resource as a scriptable command, plus offline margin and pipeline analytics.",
		"archetype":   "crm",
		"tool_count":  66,
		// tool_surface tells agents which surface a capability lives on.
		"tool_surface": "MCP exposes typed endpoint tools plus a runtime mirror of user-facing CLI commands. Endpoint tools keep typed schemas; command-mirror tools shell out to the companion salesbuildr-cli binary.",
		"auth": map[string]any{
			"type": "api_key",
			"env_vars": []map[string]any{
				{
					"name":        "SALESBUILDR_API_KEY",
					"kind":        "per_call",
					"required":    true,
					"sensitive":   true,
					"description": "Set to your API credential.",
				},
			},
		},
		"resources": []map[string]any{
			{
				"name":        "category",
				"description": "Manage category",
				"endpoints":   []string{"public-get-all-categories", "public-get-all-categories-as-tree"},
				"syncable":    true,
			},
			{
				"name":        "company",
				"description": "Manage company",
				"endpoints":   []string{"public-create", "public-delete", "public-delete-by-external-identifier", "public-get", "public-get-by-external-identifier", "public-get-list", "public-update", "public-upsert"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "contact",
				"description": "Manage contact",
				"endpoints":   []string{"company-public-create", "company-public-delete", "company-public-delete-by-id", "company-public-get", "company-public-get-by-external-identifier", "company-public-get-list", "company-public-undelete-by-ext-id", "company-public-update", "company-public-upsert", "company-public-upsert-by-email"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "contract",
				"description": "Manage contract",
				"endpoints":   []string{"public-get-items"},
				"searchable":  true,
			},
			{
				"name":        "field",
				"description": "Manage field",
				"endpoints":   []string{"public-get-values", "public-update-values"},
				"searchable":  true,
			},
			{
				"name":        "opportunity",
				"description": "Manage opportunity",
				"endpoints":   []string{"public-get-by-id", "public-get-opportunities", "public-lose", "public-upsert", "public-win"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "pricing-book",
				"description": "Manage pricing book",
				"endpoints":   []string{"public-create", "public-get", "public-get-all", "public-update"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "product",
				"description": "Manage product",
				"endpoints":   []string{"public-create", "public-create-batch", "public-delete", "public-delete-by-external-identifier", "public-get", "public-get-by-external-identifier", "public-get-id", "public-update", "public-upsert-by-external-identifier"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "quote",
				"description": "Manage quote",
				"endpoints":   []string{"public-create-approved", "public-create-draft", "public-get", "public-get-approved", "public-get-id"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "quote-discount-group",
				"description": "Manage quote discount group",
				"endpoints":   []string{"discount-group-public-create", "discount-group-public-get-all", "discount-group-public-get-by-id", "discount-group-public-update"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "quote-template",
				"description": "Manage quote template",
				"endpoints":   []string{"public-create", "public-get-by-id", "public-list", "public-update", "public-validate-template"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "quote-widget-template",
				"description": "Manage quote widget template",
				"endpoints":   []string{"public-create", "public-get-by-id", "public-list", "public-update", "public-validate-widget"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "sync-state",
				"description": "Manage sync state",
				"endpoints":   []string{"sync-public-put"},
				"searchable":  true,
			},
		},
		"query_tips": []string{
			"Pagination uses cursor-based paging. Pass after parameter for subsequent pages.",
			"Control page size with the limit parameter (default 100).",
			"Use the sql tool for ad-hoc analysis on synced data. Run sync first to populate the local database.",
			"Use the search tool for full-text search across all synced resources. Faster than iterating list endpoints.",
			"Prefer sql/search over repeated API calls when the data is already synced.",
		},
		// Command-mirror capabilities are exposed through MCP by shelling out
		// to the companion CLI binary.
		"command_mirror_capabilities": []map[string]string{
			{"name": "Stale-quote radar", "command": "quote stale", "description": "Surface quotes that have been sent or approved but are aging past a cutoff, with the dollar value still at risk.", "rationale": "Joins the local quotes and quote-items tables and filters on lifecycle timestamps — no single SalesBuildr API call returns aging quotes with their at-risk value.", "via": "mcp-command-mirror"},
			{"name": "Low-margin line radar", "command": "quote thin", "description": "Find every quote line item across all open quotes whose markup falls below a floor.", "rationale": "Scans the local quote-items store (cost/price/markup) across every quote at once; the API only returns line items one quote at a time.", "via": "mcp-command-mirror"},
			{"name": "Quote funnel", "command": "quote funnel", "description": "See stage-by-stage conversion of the quote lifecycle — count and dollar value at draft, sent, approved, declined, and expired.", "rationale": "Group-by over the local quotes lifecycle-state column with value rollups — the API returns quotes one state at a time and never the funnel.", "via": "mcp-command-mirror"},
			{"name": "Price-drift radar", "command": "pricing drift", "description": "Flag per-company pricing-book prices that have diverged from the master catalog price or cost.", "rationale": "Joins pricing-book products against catalog products on price and cost — the two resources only exist together in the local store.", "via": "mcp-command-mirror"},
			{"name": "Pipeline velocity", "command": "opportunity velocity", "description": "Aggregate sales-cycle duration and time-in-stage across the opportunity pipeline.", "rationale": "Aggregates salesCycleDurationDays and stage timestamps across all opportunities; the API exposes these per-opportunity but offers no aggregate view.", "via": "mcp-command-mirror"},
			{"name": "Win-rate breakdown", "command": "opportunity winrate", "description": "Compute won/lost ratios grouped by owner, stage, or category.", "rationale": "Groups synced opportunities on closedAt and status for conversion math the API never aggregates.", "via": "mcp-command-mirror"},
			{"name": "Product velocity", "command": "product velocity", "description": "Rank catalog products by how often they appear across quote line items and the total value quoted — your de-facto bestsellers.", "rationale": "Joins local quote-items to products and aggregates frequency and value — a cross-resource join no single API call expresses.", "via": "mcp-command-mirror"},
			{"name": "PSA reconcile by external id", "command": "reconcile-psa", "description": "Find rows across companies, contacts, products, and opportunities whose external identifier is missing — the records that silently miss a PSA sync.", "rationale": "Scans the externalIdentifier column across four local tables at once — the API is single-resource and has no by-ext completeness view.", "via": "mcp-command-mirror"},
			{"name": "Recurring-revenue forecast", "command": "opportunity mrr-forecast", "description": "Weight open-pipeline monthly revenue and profit by probability, churn-adjusted.", "rationale": "Sums monthlyRevenue and monthlyProfit times probability across the local opportunity store — pure local arithmetic over synced rows.", "via": "mcp-command-mirror"},
			{"name": "Company whitespace", "command": "company whitespace", "description": "Show catalog products a company has never been quoted — the cross-sell gaps.", "rationale": "Set-difference between the catalog and every product ever in that company's quote items; no API call expresses this.", "via": "mcp-command-mirror"},
		},
		"playbook": []map[string]string{
			{"topic": "Stale-quote radar", "insight": "Joins the local quotes and quote-items tables and filters on lifecycle timestamps — no single SalesBuildr API call returns aging quotes with their at-risk value."},
			{"topic": "Low-margin line radar", "insight": "Scans the local quote-items store (cost/price/markup) across every quote at once; the API only returns line items one quote at a time."},
			{"topic": "Quote funnel", "insight": "Group-by over the local quotes lifecycle-state column with value rollups — the API returns quotes one state at a time and never the funnel."},
			{"topic": "Price-drift radar", "insight": "Joins pricing-book products against catalog products on price and cost — the two resources only exist together in the local store."},
			{"topic": "Pipeline velocity", "insight": "Aggregates salesCycleDurationDays and stage timestamps across all opportunities; the API exposes these per-opportunity but offers no aggregate view."},
			{"topic": "Win-rate breakdown", "insight": "Groups synced opportunities on closedAt and status for conversion math the API never aggregates."},
			{"topic": "Product velocity", "insight": "Joins local quote-items to products and aggregates frequency and value — a cross-resource join no single API call expresses."},
			{"topic": "PSA reconcile by external id", "insight": "Scans the externalIdentifier column across four local tables at once — the API is single-resource and has no by-ext completeness view."},
			{"topic": "Recurring-revenue forecast", "insight": "Sums monthlyRevenue and monthlyProfit times probability across the local opportunity store — pure local arithmetic over synced rows."},
			{"topic": "Company whitespace", "insight": "Set-difference between the catalog and every product ever in that company's quote items; no API call expresses this."},
			{"topic": "Contact lookup", "insight": "Use search for finding contacts by name/email. List endpoints return unsorted results and require pagination for large datasets."},
			{"topic": "Activity tracking", "insight": "When checking deal activity, sync first and query locally. CRM APIs often throttle activity-log endpoints heavily."},
		},
	}
	return toolResultJSON(ctx)
}

// RegisterNovelFeatureTools is kept as a compatibility no-op for older MCP
// mains. New generated mains call RegisterTools only; RegisterTools now
// includes the runtime Cobra-tree mirror.
func RegisterNovelFeatureTools(s *server.MCPServer) {
	_ = s
}
