// Copyright 2026 Damien Stevens and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newCratesCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "crates",
		Short:       "Get, create, and update crates",
		Hidden:      true,
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newCratesCreateCmd(flags))
	cmd.AddCommand(newCratesGetCmd(flags))
	cmd.AddCommand(newCratesUpdateCmd(flags))
	return cmd
}
