// Copyright 2026 Damien Stevens and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newPulseCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "pulse",
		Short:       "This resource collection represents VCSP Pulse integration support.",
		Hidden:      true,
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newPulseCopyLicenseCmd(flags))
	cmd.AddCommand(newPulseCreateCompanyByTenantCmd(flags))
	cmd.AddCommand(newPulseCreateLicenseCmd(flags))
	cmd.AddCommand(newPulseCreateTenantByCompanyCmd(flags))
	cmd.AddCommand(newPulseDeleteLicenseCmd(flags))
	cmd.AddCommand(newPulseDownloadLicenseCmd(flags))
	cmd.AddCommand(newPulseGetConfigurationCmd(flags))
	cmd.AddCommand(newPulseGetLicenseCmd(flags))
	cmd.AddCommand(newPulseGetLicenseContractsCmd(flags))
	cmd.AddCommand(newPulseGetLicenseProductsCmd(flags))
	cmd.AddCommand(newPulseGetLicensesCmd(flags))
	cmd.AddCommand(newPulseGetTenantCmd(flags))
	cmd.AddCommand(newPulseGetTenantsCmd(flags))
	cmd.AddCommand(newPulseInstallLicenseCmd(flags))
	cmd.AddCommand(newPulsePatchConfigurationCmd(flags))
	cmd.AddCommand(newPulsePatchLicenseCmd(flags))
	cmd.AddCommand(newPulsePatchTenantCmd(flags))
	cmd.AddCommand(newPulseRevokeLicenseCmd(flags))
	cmd.AddCommand(newPulseSyncDataCmd(flags))
	return cmd
}
