// Copyright 2026 Damien Stevens and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newInventoryCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "inventory",
		Short:       "Get and create inventory",
		Hidden:      true,
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newInventoryGetPolookupsCmd(flags))
	cmd.AddCommand(newInventoryGetPricingLevelsCmd(flags))
	cmd.AddCommand(newInventoryGetProductCategoriesLookupCmd(flags))
	cmd.AddCommand(newInventoryGetProductDefaultCostCmd(flags))
	cmd.AddCommand(newInventoryGetProductWeightedCostCmd(flags))
	cmd.AddCommand(newInventoryGetProductsInStockCmd(flags))
	cmd.AddCommand(newInventoryGetProductsListSearchSelectCmd(flags))
	cmd.AddCommand(newInventoryGetSupplierLookupsCmd(flags))
	cmd.AddCommand(newInventoryGetWarehouseLookupsCmd(flags))
	cmd.AddCommand(newInventoryPostProductCategoriesCmd(flags))
	return cmd
}
