// Copyright 2026 Damien Stevens and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"os"

	"github.com/spf13/cobra"
	"kaseya-bms-pp-cli/internal/cliutil"
)

func newKaseyaOnePostK1CentralizedConfigurationsCmd(flags *rootFlags) *cobra.Command {
	var bodyActionEventType string
	var bodyAppClientIdentifier string
	var bodyEventEventId string
	var bodyEventEventType string
	var bodyEventIsAccessGroupsEnabled bool
	var bodyEventIsAutomaticUserDeprovisioningEnabled bool
	var bodyEventIsAutomaticUserProvisioningEnabled bool
	var bodyEventIsLogInWithKaseyaOneEnabled bool
	var bodyEventIsRequireLogInWithKaseyaOneEnabled bool
	var bodyEventKaseyaOneOrganizationId string
	var bodyEventSalesforceId string
	var bodyEventSourceInstanceId string
	var bodyEventSourceProduct string
	var bodyEventTimestamp int
	var bodyEventType string
	var bodyId string
	var bodyKaseyaOneOrganizationId string
	var bodyTargetProducts string
	var stdinBody bool

	cmd := &cobra.Command{
		Use:         "post-k1-centralized-configurations",
		Short:       "Post k1 centralized configurations",
		Example:     "  kaseya-bms-cli kaseya-one post-k1-centralized-configurations",
		Annotations: map[string]string{"pp:endpoint": "kaseya-one.post-k1-centralized-configurations", "pp:method": "POST", "pp:path": "/v2/kaseya-one/centralized-configuration/notification"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if !stdinBody {
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/v2/kaseya-one/centralized-configuration/notification"
			params := map[string]string{}
			var body map[string]any
			if stdinBody {
				stdinData, err := io.ReadAll(os.Stdin)
				if err != nil {
					return fmt.Errorf("reading stdin: %w", err)
				}
				var jsonBody map[string]any
				if err := json.Unmarshal(stdinData, &jsonBody); err != nil {
					return fmt.Errorf("parsing stdin JSON: %w", err)
				}
				body = jsonBody
			} else {
				body = map[string]any{}
				if bodyActionEventType != "" {
					body["ActionEventType"] = bodyActionEventType
				}
				if bodyAppClientIdentifier != "" {
					body["AppClientIdentifier"] = bodyAppClientIdentifier
				}
				{
					nestedEvent := map[string]any{}
					if bodyEventEventId != "" {
						nestedEvent["eventId"] = bodyEventEventId
					}
					if bodyEventEventType != "" {
						nestedEvent["event_type"] = bodyEventEventType
					}
					if cmd.Flags().Changed("event-is-access-groups-enabled") {
						nestedEvent["isAccessGroupsEnabled"] = bodyEventIsAccessGroupsEnabled
					}
					if cmd.Flags().Changed("event-is-automatic-user-deprovisioning-enabled") {
						nestedEvent["isAutomaticUserDeprovisioningEnabled"] = bodyEventIsAutomaticUserDeprovisioningEnabled
					}
					if cmd.Flags().Changed("event-is-automatic-user-provisioning-enabled") {
						nestedEvent["isAutomaticUserProvisioningEnabled"] = bodyEventIsAutomaticUserProvisioningEnabled
					}
					if cmd.Flags().Changed("event-is-log-in-with-kaseya-one-enabled") {
						nestedEvent["isLogInWithKaseyaOneEnabled"] = bodyEventIsLogInWithKaseyaOneEnabled
					}
					if cmd.Flags().Changed("event-is-require-log-in-with-kaseya-one-enabled") {
						nestedEvent["isRequireLogInWithKaseyaOneEnabled"] = bodyEventIsRequireLogInWithKaseyaOneEnabled
					}
					if bodyEventKaseyaOneOrganizationId != "" {
						nestedEvent["kaseyaOneOrganizationId"] = bodyEventKaseyaOneOrganizationId
					}
					if bodyEventSalesforceId != "" {
						nestedEvent["salesforceId"] = bodyEventSalesforceId
					}
					if bodyEventSourceInstanceId != "" {
						nestedEvent["sourceInstanceId"] = bodyEventSourceInstanceId
					}
					if bodyEventSourceProduct != "" {
						nestedEvent["source_product"] = bodyEventSourceProduct
					}
					if bodyEventTimestamp != 0 {
						nestedEvent["timestamp"] = bodyEventTimestamp
					}
					if len(nestedEvent) > 0 {
						body["Event"] = nestedEvent
					}
				}
				if bodyEventType != "" {
					body["EventType"] = bodyEventType
				}
				if bodyId != "" {
					body["Id"] = bodyId
				}
				if bodyKaseyaOneOrganizationId != "" {
					body["KaseyaOneOrganizationId"] = bodyKaseyaOneOrganizationId
				}
				if bodyTargetProducts != "" {
					body["TargetProducts"] = cliutil.SplitCSV(bodyTargetProducts)
				}
			}
			data, statusCode, err := c.PostWithParams(cmd.Context(), path, params, body)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Inspect the mutate response body for a partial-failure-shaped
			// field (e.g. Google Ads `partialFailureError`). Several Google
			// APIs return 200 OK with a partial-failure field when some
			// operations in the batch failed; ignoring it silently swallows
			// real failures. Detection runs before output-mode selection so
			// the exit code is consistent regardless of how stdout is
			// rendered. --dry-run short-circuits because no real request
			// was sent.
			var partialFailure *partialFailureReport
			if !flags.dryRun && statusCode >= 200 && statusCode < 300 {
				partialFailure = detectPartialFailure(data)
				if partialFailure != nil {
					fmt.Fprintf(os.Stderr, "warning: partial failure detected in %s response: %s\n", "kaseya-one", partialFailure.Message)
					if len(partialFailure.ResourceNames) > 0 {
						fmt.Fprintf(os.Stderr, "         succeeded: %d operation(s)\n", len(partialFailure.ResourceNames))
					}
				}
			}
			if !flags.dryRun && statusCode >= 200 && statusCode < 300 && (partialFailure == nil || flags.allowPartialFailure) {
				writeMutationResponseToStore(cmd.Context(), "kaseya-one", data, "")
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				// Check if response contains an array (directly or wrapped in "data")
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
					} else {
						if partialFailure != nil && !flags.allowPartialFailure {
							return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "kaseya-one", partialFailure.Message))
						}
						return nil
					}
				} else {
					var wrapped struct {
						Data []map[string]any `json:"data"`
					}
					if json.Unmarshal(data, &wrapped) == nil && len(wrapped.Data) > 0 {
						if err := printAutoTable(cmd.OutOrStdout(), wrapped.Data); err != nil {
							fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
						} else {
							if partialFailure != nil && !flags.allowPartialFailure {
								return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "kaseya-one", partialFailure.Message))
							}
							return nil
						}
					}
				}
			}
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				if flags.quiet {
					if partialFailure != nil && !flags.allowPartialFailure {
						return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "kaseya-one", partialFailure.Message))
					}
					return nil
				}
				envelope := map[string]any{
					"action":   "post",
					"resource": "kaseya-one",
					"path":     path,
					"status":   statusCode,
					"success":  statusCode >= 200 && statusCode < 300 && (partialFailure == nil || flags.allowPartialFailure),
				}
				if partialFailure != nil {
					envelope["partial_failure"] = partialFailure
				}
				if flags.dryRun {
					envelope["dry_run"] = true
					envelope["status"] = 0
					envelope["success"] = false
				}
				// Verify-mode synthetic envelope detection runs against RAW data
				// (before --compact/--select filtering) so the sentinel field is
				// guaranteed to be visible even if the operator passes a filter
				// flag that would otherwise strip it. Surfaces a top-level
				// verify_noop signal + flips success to false. Mirrors the dry_run
				// shape above.
				if len(data) > 0 {
					var rawParsed any
					if err := json.Unmarshal(data, &rawParsed); err == nil {
						if m, ok := rawParsed.(map[string]any); ok {
							if v, ok := m["__pp_verify_synthetic__"].(bool); ok && v {
								envelope["verify_noop"] = true
								envelope["success"] = false
							}
						}
					}
				}
				// Apply --compact and --select to the API response before wrapping.
				// --select wins when both are set: explicit field choice trumps the
				// generic high-gravity allow-list. Otherwise --compact still applies
				// when --agent is on but the user did not name fields.
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				if len(filtered) > 0 {
					var parsed any
					if err := json.Unmarshal(filtered, &parsed); err == nil {
						envelope["data"] = parsed
					}
				}
				envelopeJSON, err := json.Marshal(envelope)
				if err != nil {
					return err
				}
				if perr := printOutput(cmd.OutOrStdout(), json.RawMessage(envelopeJSON), true); perr != nil {
					return perr
				}
				if partialFailure != nil && !flags.allowPartialFailure {
					return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "kaseya-one", partialFailure.Message))
				}
				return nil
			}
			// Fall-through for mutate paths that did not hit the table or
			// asJSON branches: --quiet, --csv, --plain, and default terminal
			// raw output. printOutputWithFlags renders the body, then the
			// typed partial-failure exit fires unless --allow-partial-failure
			// downgrades it. Without this guard a partial failure would exit
			// 0 for these output modes — the exact silent-swallow regression
			// the surrounding patch is preventing for asJSON / piped output.
			if perr := printOutputWithFlags(cmd.OutOrStdout(), data, flags); perr != nil {
				return perr
			}
			if partialFailure != nil && !flags.allowPartialFailure {
				return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "kaseya-one", partialFailure.Message))
			}
			return nil
		},
	}
	cmd.Flags().StringVar(&bodyActionEventType, "action-event-type", "", "Action event type")
	cmd.Flags().StringVar(&bodyAppClientIdentifier, "app-client-identifier", "", "App client identifier")
	cmd.Flags().StringVar(&bodyEventEventId, "event-event-id", "", "Event id")
	cmd.Flags().StringVar(&bodyEventEventType, "event-event-type", "", "Event type")
	cmd.Flags().BoolVar(&bodyEventIsAccessGroupsEnabled, "event-is-access-groups-enabled", false, "Is access groups enabled")
	cmd.Flags().BoolVar(&bodyEventIsAutomaticUserDeprovisioningEnabled, "event-is-automatic-user-deprovisioning-enabled", false, "Is automatic user deprovisioning enabled")
	cmd.Flags().BoolVar(&bodyEventIsAutomaticUserProvisioningEnabled, "event-is-automatic-user-provisioning-enabled", false, "Is automatic user provisioning enabled")
	cmd.Flags().BoolVar(&bodyEventIsLogInWithKaseyaOneEnabled, "event-is-log-in-with-kaseya-one-enabled", false, "Is log in with kaseya one enabled")
	cmd.Flags().BoolVar(&bodyEventIsRequireLogInWithKaseyaOneEnabled, "event-is-require-log-in-with-kaseya-one-enabled", false, "Is require log in with kaseya one enabled")
	cmd.Flags().StringVar(&bodyEventKaseyaOneOrganizationId, "event-kaseya-one-organization-id", "", "Kaseya one organization id")
	cmd.Flags().StringVar(&bodyEventSalesforceId, "event-salesforce-id", "", "Salesforce id")
	cmd.Flags().StringVar(&bodyEventSourceInstanceId, "event-source-instance-id", "", "Source instance id")
	cmd.Flags().StringVar(&bodyEventSourceProduct, "event-source-product", "", "Source product")
	cmd.Flags().IntVar(&bodyEventTimestamp, "event-timestamp", 0, "Timestamp")
	cmd.Flags().StringVar(&bodyEventType, "event-type", "", "Event type")
	cmd.Flags().StringVar(&bodyId, "id", "", "Id")
	cmd.Flags().StringVar(&bodyKaseyaOneOrganizationId, "kaseya-one-organization-id", "", "Kaseya one organization id")
	cmd.Flags().StringVar(&bodyTargetProducts, "target-products", "", "Target products")
	cmd.Flags().BoolVar(&stdinBody, "stdin", false, "Read request body as JSON from stdin")

	return cmd
}
