// Copyright 2026 Damien Stevens and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newTimelogsPromotedCmd(flags *rootFlags) *cobra.Command {
	var flagFilterTimeEntrySourceId string
	var flagFilterTicketId string
	var flagFilterProjectId string
	var flagFilterUserId string
	var flagFilterAccountId string
	var flagFilterIsPosted bool
	var flagFilterIsApproved bool
	var flagFilterIsBilled bool
	var flagFilterIsBillable bool
	var flagFilterStartDateFrom string
	var flagFilterStartDateTo string
	var flagFilterCreatedOnFrom string
	var flagFilterCreatedOnTo string
	var flagFilterModifiedOnFrom string
	var flagFilterModifiedOnTo string
	var flagSort string
	var flagExclude string
	var flagPageSize int
	var flagPageNumber int
	var flagAll bool

	cmd := &cobra.Command{
		Use:         "timelogs",
		Short:       "Get all time logs",
		Long:        "Get all time logs",
		Example:     "  kaseya-bms-cli timelogs",
		Annotations: map[string]string{"pp:endpoint": "timelogs.get-all-time-logs", "pp:method": "GET", "pp:path": "/v2/timelogs", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/v2/timelogs"
			data, prov, err := resolvePaginatedReadWithStrategy(cmd.Context(), c, flags, "auto", "timelogs", path, map[string]string{
				"Filter.TimeEntrySourceId": formatCLIParamValue(flagFilterTimeEntrySourceId),
				"Filter.TicketId":          formatCLIParamValue(flagFilterTicketId),
				"Filter.ProjectId":         formatCLIParamValue(flagFilterProjectId),
				"Filter.UserId":            formatCLIParamValue(flagFilterUserId),
				"Filter.AccountId":         formatCLIParamValue(flagFilterAccountId),
				"Filter.IsPosted":          formatCLIParamValue(flagFilterIsPosted),
				"Filter.IsApproved":        formatCLIParamValue(flagFilterIsApproved),
				"Filter.IsBilled":          formatCLIParamValue(flagFilterIsBilled),
				"Filter.IsBillable":        formatCLIParamValue(flagFilterIsBillable),
				"Filter.StartDateFrom":     formatCLIParamValue(flagFilterStartDateFrom),
				"Filter.StartDateTo":       formatCLIParamValue(flagFilterStartDateTo),
				"Filter.CreatedOnFrom":     formatCLIParamValue(flagFilterCreatedOnFrom),
				"Filter.CreatedOnTo":       formatCLIParamValue(flagFilterCreatedOnTo),
				"Filter.ModifiedOnFrom":    formatCLIParamValue(flagFilterModifiedOnFrom),
				"Filter.ModifiedOnTo":      formatCLIParamValue(flagFilterModifiedOnTo),
				"Sort":                     formatCLIParamValue(flagSort),
				"Exclude":                  formatCLIParamValue(flagExclude),
				"PageSize":                 formatCLIParamValue(flagPageSize),
				"PageNumber":               formatCLIParamValue(flagPageNumber),
			}, nil, flagAll, "PageNumber", "page", "PageSize", "", "", cmd.ErrOrStderr())
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Print provenance to stderr for human-facing output only.
			// Machine-format flags (--json, --csv, --compact, --quiet, --plain,
			// --select) and piped stdout suppress this line; the JSON envelope
			// already carries meta.source for those consumers.
			// SYNC: keep this gate aligned with command_endpoint.go.tmpl.
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var countItems []json.RawMessage
				if json.Unmarshal(data, &countItems) != nil {
					// Single object, not an array
					countItems = []json.RawMessage{data}
				}
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope. --select wins over
			// --compact when both are set; --compact only runs when no explicit
			// fields were requested. Explicit format flags (--csv, --quiet, --plain)
			// opt out of the auto-JSON path so piped consumers that asked for a
			// non-JSON format reach the standard pipeline below.
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&flagFilterTimeEntrySourceId, "filter-time-entry-source-id", "", "Filter time entry source id")
	cmd.Flags().StringVar(&flagFilterTicketId, "filter-ticket-id", "", "Filter ticket id")
	cmd.Flags().StringVar(&flagFilterProjectId, "filter-project-id", "", "Filter project id")
	cmd.Flags().StringVar(&flagFilterUserId, "filter-user-id", "", "Filter user id")
	cmd.Flags().StringVar(&flagFilterAccountId, "filter-account-id", "", "Filter account id")
	cmd.Flags().BoolVar(&flagFilterIsPosted, "filter-is-posted", false, "Filter is posted")
	cmd.Flags().BoolVar(&flagFilterIsApproved, "filter-is-approved", false, "Filter is approved")
	cmd.Flags().BoolVar(&flagFilterIsBilled, "filter-is-billed", false, "Filter is billed")
	cmd.Flags().BoolVar(&flagFilterIsBillable, "filter-is-billable", false, "Filter is billable")
	cmd.Flags().StringVar(&flagFilterStartDateFrom, "filter-start-date-from", "", "Filter start date from")
	cmd.Flags().StringVar(&flagFilterStartDateTo, "filter-start-date-to", "", "Filter start date to")
	cmd.Flags().StringVar(&flagFilterCreatedOnFrom, "filter-created-on-from", "", "Filter created on from")
	cmd.Flags().StringVar(&flagFilterCreatedOnTo, "filter-created-on-to", "", "Filter created on to")
	cmd.Flags().StringVar(&flagFilterModifiedOnFrom, "filter-modified-on-from", "", "Filter modified on from")
	cmd.Flags().StringVar(&flagFilterModifiedOnTo, "filter-modified-on-to", "", "Filter modified on to")
	cmd.Flags().StringVar(&flagSort, "sort", "", "Sort")
	cmd.Flags().StringVar(&flagExclude, "exclude", "", "Exclude")
	cmd.Flags().IntVar(&flagPageSize, "page-size", 0, "Page size")
	cmd.Flags().IntVar(&flagPageNumber, "page-number", 0, "Page number")
	cmd.Flags().BoolVar(&flagAll, "all", false, "Fetch all pages")

	// Wire sibling endpoints and sub-resources as subcommands

	return cmd
}
