// Copyright 2026 Damien Stevens and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newRmmMappingsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "mappings",
		Short:       "Get, create, and delete mappings for rmm",
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newRmmMappingsCreateCmd(flags))
	cmd.AddCommand(newRmmMappingsDeleteCmd(flags))
	cmd.AddCommand(newRmmMappingsGetCmd(flags))
	cmd.AddCommand(newRmmMappingsGetRmmCmd(flags))
	return cmd
}
