// Copyright 2026 Abhi Saini and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newComputersGetInventorySoftwareSearchByNameCmd(flags *rootFlags) *cobra.Command {
	var flagQ string
	var flagSearchMode string

	cmd := &cobra.Command{
		Use:         "get-inventory-software-search-by-name",
		Short:       "Get inventory software search by name",
		Example:     "  immybot-pp-cli computers get-inventory-software-search-by-name",
		Annotations: map[string]string{"pp:endpoint": "computers.get-inventory-software-search-by-name", "pp:method": "GET", "pp:path": "/api/v1/computers/inventory-software/search-by-name", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if cmd.Flags().Changed("search-mode") {
				allowedSearchMode := []string{"Contains", "Regex", "Traditional"}
				validSearchMode := false
				for _, v := range allowedSearchMode {
					if flagSearchMode == v {
						validSearchMode = true
						break
					}
				}
				if !validSearchMode {
					return fmt.Errorf("invalid value %q for --%s: must be one of %v", flagSearchMode, "search-mode", allowedSearchMode)
				}
			}
			path := "/api/v1/computers/inventory-software/search-by-name"
			c, err := flags.newClient()
			if err != nil {
				return err
			}
			params := map[string]string{}
			if flagQ != "" {
				params["q"] = formatCLIParamValue(flagQ)
			}
			if flagSearchMode != "" {
				params["searchMode"] = formatCLIParamValue(flagSearchMode)
			}
			data, prov, err := resolveReadWithStrategyAndResponsePath(cmd.Context(), c, flags, "auto", "computers", true, path, params, nil, "", cmd.ErrOrStderr())
			if err != nil {
				return classifyAPIError(cmd.OutOrStdout(), err, flags)
			}
			outputData := data
			// Print provenance to stderr for human-facing output only.
			// Machine-format flags (--json, --csv, --compact, --quiet, --plain,
			// --select) and piped stdout suppress this line; the JSON envelope
			// already carries meta.source for those consumers.
			// SYNC: keep this gate aligned with command_promoted.go.tmpl.
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var countItems []json.RawMessage
				_ = json.Unmarshal(outputData, &countItems)
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope before passing through flags.
			// --select wins over --compact when both are set; --compact only runs when
			// no explicit fields were requested. Explicit format flags (--csv, --quiet,
			// --plain) opt out of the auto-JSON path so piped consumers that asked for
			// a non-JSON format reach the standard pipeline below.
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered, map[string]bool{"capturedDisplayVersion": true, "computers": true, "displayName": true, "displayVersion": true, "upgradeCode": true})
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				wrapped, wrapErr = wrapPlatformStructuredOutput(wrapped, flags, "results", true)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			// For all other output modes (table, csv, plain, quiet), use the standard pipeline
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(outputData, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			formatData := data
			if flags.csv || flags.plain {
				formatData = outputData
			}
			return printOutputWithFlagsMeta(cmd.OutOrStdout(), formatData, flags, map[string]any{"source": "live"}, map[string]bool{"capturedDisplayVersion": true, "computers": true, "displayName": true, "displayVersion": true, "upgradeCode": true})
		},
	}
	cmd.Flags().StringVar(&flagQ, "q", "", "Q")
	cmd.Flags().StringVar(&flagSearchMode, "search-mode", "", "The string or integer value may be used. Contains = 0, Regex = 1, Traditional = 2 (one of: Contains, Regex, Traditional)")

	return cmd
}
