// Copyright 2026 Servosity Inc. and msp-skills contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newMaintenanceActionsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "maintenance-actions",
		Short:       "Get and create maintenance actions",
		Annotations: map[string]string{"mcp:read-only": "true", "pp:parent-group": "true", "pp:api-resource": "true", "pp:typed-exit-codes": "0,2"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newMaintenanceActionsCreateLatestActionForComputersCmd(flags))
	cmd.AddCommand(newMaintenanceActionsCreateLatestActionForTenantsCmd(flags))
	cmd.AddCommand(newMaintenanceActionsGetComputerByComputerIdNeedsAttentionCmd(flags))
	cmd.AddCommand(newMaintenanceActionsGetDxCmd(flags))
	cmd.AddCommand(newMaintenanceActionsGetDxForComputerByComputerIdCmd(flags))
	cmd.AddCommand(newMaintenanceActionsGetLatestForComputerByComputerIdCmd(flags))
	cmd.AddCommand(newMaintenanceActionsGetLatestForTenantByTenantIdCmd(flags))
	cmd.AddCommand(newMaintenanceActionsGetLatestNonCompliantActionsForTenantByTenantIdCmd(flags))
	cmd.AddCommand(newMaintenanceActionsGetMaintenanceItemCmd(flags))
	cmd.AddCommand(newMaintenanceActionsGetVersionCmd(flags))
	cmd.AddCommand(newMaintenanceActionsLogsCmd(flags))
	return cmd
}
