// Copyright 2026 Servosity Inc. and msp-skills contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newRolesCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "roles",
		Short:       "List, get, create, update, and delete roles",
		Annotations: map[string]string{"mcp:read-only": "true", "pp:parent-group": "true", "pp:api-resource": "true", "pp:typed-exit-codes": "0,2"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newRolesCreateCmd(flags))
	cmd.AddCommand(newRolesDeleteByIdCmd(flags))
	cmd.AddCommand(newRolesGetByIdCmd(flags))
	cmd.AddCommand(newRolesGetPermissionsCmd(flags))
	cmd.AddCommand(newRolesListCmd(flags))
	cmd.AddCommand(newRolesUpdateByIdCmd(flags))
	cmd.AddCommand(newRolesAssignmentsCmd(flags))
	cmd.AddCommand(newRolesCloneCmd(flags))
	return cmd
}
