// Copyright 2026 Damien Stevens and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newNewTicketFormsProcessFormCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "process-form",
		Short:       "Create process form for new ticket forms",
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newNewTicketFormsProcessFormCreateCmd(flags))
	return cmd
}
