// Copyright 2026 Damien Stevens and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newExclusionsGetCmd(flags *rootFlags) *cobra.Command {
	var flagUpdatedAtGt string
	var flagUpdatedAtLt string
	var flagCreatedAtLt string
	var flagSkip string
	var flagSortOrder string
	var flagCreatedAtLte string
	var flagPathExclusionTypes string
	var flagIds string
	var flagIncludeParents string
	var flagUserIds string
	var flagUpdatedAtBetween string
	var flagCreatedAtGte string
	var flagModes string
	var flagOsTypes string
	var flagUpdatedAtLte string
	var flagDescriptionContains string
	var flagSiteIds string
	var flagSortBy string
	var flagGroupIds string
	var flagLimit string
	var flagIncludeChildren string
	var flagQuery string
	var flagAccountIds string
	var flagCursor string
	var flagUpdatedAtGte string
	var flagTypes string
	var flagUnified string
	var flagSource string
	var flagValueContains string
	var flagCreatedAtBetween string
	var flagTenant string
	var flagSkipCount string
	var flagRecommendations string
	var flagValue string
	var flagCountOnly string
	var flagType string
	var flagUserContains string
	var flagCreatedAtGt string
	var flagAll bool

	cmd := &cobra.Command{
		Use:         "get",
		Aliases:     []string{"list"},
		Short:       "Get a list of all the Exclusions that match the filter.",
		Example:     "  sentinelone-cli exclusions get",
		Annotations: map[string]string{"pp:endpoint": "exclusions.get", "pp:method": "GET", "pp:path": "/exclusions", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/exclusions"
			data, prov, err := resolvePaginatedReadWithStrategy(cmd.Context(), c, flags, "auto", "exclusions", path, map[string]string{
				"updatedAt__gt":         formatCLIParamValue(flagUpdatedAtGt),
				"updatedAt__lt":         formatCLIParamValue(flagUpdatedAtLt),
				"createdAt__lt":         formatCLIParamValue(flagCreatedAtLt),
				"skip":                  formatCLIParamValue(flagSkip),
				"sortOrder":             formatCLIParamValue(flagSortOrder),
				"createdAt__lte":        formatCLIParamValue(flagCreatedAtLte),
				"pathExclusionTypes":    formatCLIParamValue(flagPathExclusionTypes),
				"ids":                   formatCLIParamValue(flagIds),
				"includeParents":        formatCLIParamValue(flagIncludeParents),
				"userIds":               formatCLIParamValue(flagUserIds),
				"updatedAt__between":    formatCLIParamValue(flagUpdatedAtBetween),
				"createdAt__gte":        formatCLIParamValue(flagCreatedAtGte),
				"modes":                 formatCLIParamValue(flagModes),
				"osTypes":               formatCLIParamValue(flagOsTypes),
				"updatedAt__lte":        formatCLIParamValue(flagUpdatedAtLte),
				"description__contains": formatCLIParamValue(flagDescriptionContains),
				"siteIds":               formatCLIParamValue(flagSiteIds),
				"sortBy":                formatCLIParamValue(flagSortBy),
				"groupIds":              formatCLIParamValue(flagGroupIds),
				"limit":                 formatCLIParamValue(flagLimit),
				"includeChildren":       formatCLIParamValue(flagIncludeChildren),
				"query":                 formatCLIParamValue(flagQuery),
				"accountIds":            formatCLIParamValue(flagAccountIds),
				"cursor":                formatCLIParamValue(flagCursor),
				"updatedAt__gte":        formatCLIParamValue(flagUpdatedAtGte),
				"types":                 formatCLIParamValue(flagTypes),
				"unified":               formatCLIParamValue(flagUnified),
				"source":                formatCLIParamValue(flagSource),
				"value__contains":       formatCLIParamValue(flagValueContains),
				"createdAt__between":    formatCLIParamValue(flagCreatedAtBetween),
				"tenant":                formatCLIParamValue(flagTenant),
				"skipCount":             formatCLIParamValue(flagSkipCount),
				"recommendations":       formatCLIParamValue(flagRecommendations),
				"value":                 formatCLIParamValue(flagValue),
				"countOnly":             formatCLIParamValue(flagCountOnly),
				"type":                  formatCLIParamValue(flagType),
				"user__contains":        formatCLIParamValue(flagUserContains),
				"createdAt__gt":         formatCLIParamValue(flagCreatedAtGt),
			}, nil, flagAll, "cursor", "cursor", "limit", "", "", cmd.ErrOrStderr())
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Print provenance to stderr for human-facing output only.
			// Machine-format flags (--json, --csv, --compact, --quiet, --plain,
			// --select) and piped stdout suppress this line; the JSON envelope
			// already carries meta.source for those consumers.
			// SYNC: keep this gate aligned with command_promoted.go.tmpl.
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var countItems []json.RawMessage
				_ = json.Unmarshal(data, &countItems)
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope before passing through flags.
			// --select wins over --compact when both are set; --compact only runs when
			// no explicit fields were requested. Explicit format flags (--csv, --quiet,
			// --plain) opt out of the auto-JSON path so piped consumers that asked for
			// a non-JSON format reach the standard pipeline below.
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			// For all other output modes (table, csv, plain, quiet), use the standard pipeline
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&flagUpdatedAtGt, "updated-at-gt", "", "Updated after this timestamp. Example: '2018-02-27T04:49:26.257525Z'.")
	cmd.Flags().StringVar(&flagUpdatedAtLt, "updated-at-lt", "", "Updated before this timestamp. Example: '2018-02-27T04:49:26.257525Z'.")
	cmd.Flags().StringVar(&flagCreatedAtLt, "created-at-lt", "", "Created before this timestamp. Example: '2018-02-27T04:49:26.257525Z'.")
	cmd.Flags().StringVar(&flagSkip, "skip", "", "Skip first number of items (0-1000). To iterate over more than 1000 items, use 'cursor'. Example: '150'.")
	cmd.Flags().StringVar(&flagSortOrder, "sort-order", "", "Sort direction. Example: 'asc'.")
	cmd.Flags().StringVar(&flagCreatedAtLte, "created-at-lte", "", "Created before or at this timestamp. Example: '2018-02-27T04:49:26.257525Z'.")
	cmd.Flags().StringVar(&flagPathExclusionTypes, "path-exclusion-types", "", "List of excluded paths in an exclusion (Path exclusions only). Example: 'file'.")
	cmd.Flags().StringVar(&flagIds, "ids", "", "List of IDs to filter by. Example: '225494730938493804,225494730938493915'.")
	cmd.Flags().StringVar(&flagIncludeParents, "include-parents", "", "Return filters from parent scope levels (Default: false)")
	cmd.Flags().StringVar(&flagUserIds, "user-ids", "", "List of user ids to filter by. Example: '225494730938493804,225494730938493915'.")
	cmd.Flags().StringVar(&flagUpdatedAtBetween, "updated-at-between", "", "Date range for update time (format: <from_timestamp>-<to_timestamp>, inclusive). Example: '1514978890136-1514978650130'.")
	cmd.Flags().StringVar(&flagCreatedAtGte, "created-at-gte", "", "Created after or at this timestamp. Example: '2018-02-27T04:49:26.257525Z'.")
	cmd.Flags().StringVar(&flagModes, "modes", "", "List of modes to filter by (Path exclusions only). Example: 'suppress'.")
	cmd.Flags().StringVar(&flagOsTypes, "os-types", "", "List of Os types to filter by. Example: 'macos'.")
	cmd.Flags().StringVar(&flagUpdatedAtLte, "updated-at-lte", "", "Updated before or at this timestamp. Example: '2018-02-27T04:49:26.257525Z'.")
	cmd.Flags().StringVar(&flagDescriptionContains, "description-contains", "", "Free-text filter by description")
	cmd.Flags().StringVar(&flagSiteIds, "site-ids", "", "List of Site IDs to filter by. Example: '225494730938493804,225494730938493915'.")
	cmd.Flags().StringVar(&flagSortBy, "sort-by", "", "The column to sort the results by. Example: 'id'.")
	cmd.Flags().StringVar(&flagGroupIds, "group-ids", "", "List of Group IDs to filter by. Example: '225494730938493804,225494730938493915'.")
	cmd.Flags().StringVar(&flagLimit, "limit", "", "Limit number of returned items (1-1000). Example: '10'.")
	cmd.Flags().StringVar(&flagIncludeChildren, "include-children", "", "Return filters from children scope levels (Default: false)")
	cmd.Flags().StringVar(&flagQuery, "query", "", "A free-text search term, will match applicable attributes")
	cmd.Flags().StringVar(&flagAccountIds, "account-ids", "", "List of Account IDs to filter by. Example: '225494730938493804,225494730938493915'.")
	cmd.Flags().StringVar(&flagCursor, "cursor", "", "Cursor position returned by the last request. Use to iterate over more than 1000 items.")
	cmd.Flags().StringVar(&flagUpdatedAtGte, "updated-at-gte", "", "Updated after or at this timestamp. Example: '2018-02-27T04:49:26.257525Z'.")
	cmd.Flags().StringVar(&flagTypes, "types", "", "Type in. Example: 'path'.")
	cmd.Flags().StringVar(&flagUnified, "unified", "", "Unified")
	cmd.Flags().StringVar(&flagSource, "source", "", "List sources to filter by. Example: 'user'.")
	cmd.Flags().StringVar(&flagValueContains, "value-contains", "", "Free-text filter by value")
	cmd.Flags().StringVar(&flagCreatedAtBetween, "created-at-between", "", "Date range for creation time (format: <from_timestamp>-<to_timestamp>, inclusive).")
	cmd.Flags().StringVar(&flagTenant, "tenant", "", "Indicates a Global (tenant) scope request")
	cmd.Flags().StringVar(&flagSkipCount, "skip-count", "", "If true, total number of items will not be calculated, which speeds up execution time.")
	cmd.Flags().StringVar(&flagRecommendations, "recommendations", "", "List of recommendations to filter by. Example: 'Not recommended'.")
	cmd.Flags().StringVar(&flagValue, "value", "", "Value")
	cmd.Flags().StringVar(&flagCountOnly, "count-only", "", "If true, only total number of items will be returned, without any of the actual objects.")
	cmd.Flags().StringVar(&flagType, "type", "", "Type. Example: 'path'.")
	cmd.Flags().StringVar(&flagUserContains, "user-contains", "", "Free-text filter by user name")
	cmd.Flags().StringVar(&flagCreatedAtGt, "created-at-gt", "", "Created after this timestamp. Example: '2018-02-27T04:49:26.257525Z'.")
	cmd.Flags().BoolVar(&flagAll, "all", false, "Fetch all pages")

	return cmd
}
