// Copyright 2026 Damien Stevens and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newFirewallControlSetLocationCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "set-location",
		Short:       "Create set location for firewall control",
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newFirewallControlSetLocationByCategoryCmd(flags))
	return cmd
}
