// Copyright 2026 Damien Stevens and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newLocationsGetCmd(flags *rootFlags) *cobra.Command {
	var flagRegistryKeyContains string
	var flagIpAddressContains string
	var flagSkip string
	var flagSortOrder string
	var flagHasFirewallRules string
	var flagCreatorContains string
	var flagIds string
	var flagDescriptionContains string
	var flagScopeNameContains string
	var flagNameContains string
	var flagSiteIds string
	var flagSortBy string
	var flagGroupIds string
	var flagLimit string
	var flagAccountIds string
	var flagHostnameContains string
	var flagCursor string
	var flagSkipCount string
	var flagScopes string
	var flagCountOnly string
	var flagAll bool

	cmd := &cobra.Command{
		Use:         "get",
		Aliases:     []string{"list"},
		Short:       "Get the locations of Agents in a given scope that match the filter.",
		Example:     "  sentinelone-cli locations get",
		Annotations: map[string]string{"pp:endpoint": "locations.get", "pp:method": "GET", "pp:path": "/locations", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/locations"
			data, prov, err := resolvePaginatedReadWithStrategy(cmd.Context(), c, flags, "auto", "locations", path, map[string]string{
				"registryKey__contains": formatCLIParamValue(flagRegistryKeyContains),
				"ipAddress__contains":   formatCLIParamValue(flagIpAddressContains),
				"skip":                  formatCLIParamValue(flagSkip),
				"sortOrder":             formatCLIParamValue(flagSortOrder),
				"hasFirewallRules":      formatCLIParamValue(flagHasFirewallRules),
				"creator__contains":     formatCLIParamValue(flagCreatorContains),
				"ids":                   formatCLIParamValue(flagIds),
				"description__contains": formatCLIParamValue(flagDescriptionContains),
				"scopeName__contains":   formatCLIParamValue(flagScopeNameContains),
				"name__contains":        formatCLIParamValue(flagNameContains),
				"siteIds":               formatCLIParamValue(flagSiteIds),
				"sortBy":                formatCLIParamValue(flagSortBy),
				"groupIds":              formatCLIParamValue(flagGroupIds),
				"limit":                 formatCLIParamValue(flagLimit),
				"accountIds":            formatCLIParamValue(flagAccountIds),
				"hostname__contains":    formatCLIParamValue(flagHostnameContains),
				"cursor":                formatCLIParamValue(flagCursor),
				"skipCount":             formatCLIParamValue(flagSkipCount),
				"scopes":                formatCLIParamValue(flagScopes),
				"countOnly":             formatCLIParamValue(flagCountOnly),
			}, nil, flagAll, "cursor", "cursor", "limit", "", "", cmd.ErrOrStderr())
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Print provenance to stderr for human-facing output only.
			// Machine-format flags (--json, --csv, --compact, --quiet, --plain,
			// --select) and piped stdout suppress this line; the JSON envelope
			// already carries meta.source for those consumers.
			// SYNC: keep this gate aligned with command_promoted.go.tmpl.
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var countItems []json.RawMessage
				_ = json.Unmarshal(data, &countItems)
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope before passing through flags.
			// --select wins over --compact when both are set; --compact only runs when
			// no explicit fields were requested. Explicit format flags (--csv, --quiet,
			// --plain) opt out of the auto-JSON path so piped consumers that asked for
			// a non-JSON format reach the standard pipeline below.
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			// For all other output modes (table, csv, plain, quiet), use the standard pipeline
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&flagRegistryKeyContains, "registry-key-contains", "", "Free-text filter by registry key (supports multiple values). Example: 'systemsoftware,sentinel'.")
	cmd.Flags().StringVar(&flagIpAddressContains, "ip-address-contains", "", "Free-text filter by IP address (supports multiple values). Example: '29.213.22.17'.")
	cmd.Flags().StringVar(&flagSkip, "skip", "", "Skip first number of items (0-1000). To iterate over more than 1000 items, use 'cursor'. Example: '150'.")
	cmd.Flags().StringVar(&flagSortOrder, "sort-order", "", "Sort direction. Example: 'asc'.")
	cmd.Flags().StringVar(&flagHasFirewallRules, "has-firewall-rules", "", "Filter by locations with/without firewall rules associated to them")
	cmd.Flags().StringVar(&flagCreatorContains, "creator-contains", "", "Free-text filter by creator of the location (supports multiple values). Example: 'max,mike'.")
	cmd.Flags().StringVar(&flagIds, "ids", "", "Filter results by location IDs. Example: '225494730938493804,225494730938493915'.")
	cmd.Flags().StringVar(&flagDescriptionContains, "description-contains", "", "Free-text filter by description (supports multiple values). Example: 'out of office'.")
	cmd.Flags().StringVar(&flagScopeNameContains, "scope-name-contains", "", "Free-text filter by scope name (supports multiple values). Example: 'my_group,my_site'.")
	cmd.Flags().StringVar(&flagNameContains, "name-contains", "", "Free-text filter by location name (supports multiple values). Example: 'office'.")
	cmd.Flags().StringVar(&flagSiteIds, "site-ids", "", "List of Site IDs to filter by. Example: '225494730938493804,225494730938493915'.")
	cmd.Flags().StringVar(&flagSortBy, "sort-by", "", "The column to sort the results by. Example: 'id'.")
	cmd.Flags().StringVar(&flagGroupIds, "group-ids", "", "List of Group IDs to filter by. Example: '225494730938493804,225494730938493915'.")
	cmd.Flags().StringVar(&flagLimit, "limit", "", "Limit number of returned items (1-1000). Example: '10'.")
	cmd.Flags().StringVar(&flagAccountIds, "account-ids", "", "List of Account IDs to filter by. Example: '225494730938493804,225494730938493915'.")
	cmd.Flags().StringVar(&flagHostnameContains, "hostname-contains", "", "Free-text filter by hostname (supports multiple values). Example: 'sentinelone.com,localhost'.")
	cmd.Flags().StringVar(&flagCursor, "cursor", "", "Cursor position returned by the last request. Use to iterate over more than 1000 items.")
	cmd.Flags().StringVar(&flagSkipCount, "skip-count", "", "If true, total number of items will not be calculated, which speeds up execution time.")
	cmd.Flags().StringVar(&flagScopes, "scopes", "", "Filter results by scope. Example: 'group'.")
	cmd.Flags().StringVar(&flagCountOnly, "count-only", "", "If true, only total number of items will be returned, without any of the actual objects.")
	cmd.Flags().BoolVar(&flagAll, "all", false, "Fetch all pages")

	return cmd
}
