// Copyright 2026 Damien Stevens and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newThreatsExploreGetEventsCmd(flags *rootFlags) *cobra.Command {
	var flagSortBy string
	var flagEventId string
	var flagEventSubTypes string
	var flagLimit string
	var flagSkipCount string
	var flagSkip string
	var flagSortOrder string
	var flagEventTypes string
	var flagProcessNameLike string
	var flagCountOnly string
	var flagCursor string
	var flagAll bool

	cmd := &cobra.Command{
		Use:         "get-events <threat_id>",
		Aliases:     []string{"get"},
		Short:       "Get all threat events.",
		Example:     "  sentinelone-cli threats explore get-events 550e8400-e29b-41d4-a716-446655440000",
		Annotations: map[string]string{"pp:endpoint": "explore.get-events", "pp:method": "GET", "pp:path": "/threats/{threat_id}/explore/events", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) == 0 {
				return cmd.Help()
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/threats/{threat_id}/explore/events"
			path = replacePathParam(path, "threat_id", args[0])
			data, prov, err := resolvePaginatedReadWithStrategy(cmd.Context(), c, flags, "auto", "explore", path, map[string]string{
				"sortBy":            formatCLIParamValue(flagSortBy),
				"eventId":           formatCLIParamValue(flagEventId),
				"eventSubTypes":     formatCLIParamValue(flagEventSubTypes),
				"limit":             formatCLIParamValue(flagLimit),
				"skipCount":         formatCLIParamValue(flagSkipCount),
				"skip":              formatCLIParamValue(flagSkip),
				"sortOrder":         formatCLIParamValue(flagSortOrder),
				"eventTypes":        formatCLIParamValue(flagEventTypes),
				"processName__like": formatCLIParamValue(flagProcessNameLike),
				"countOnly":         formatCLIParamValue(flagCountOnly),
				"cursor":            formatCLIParamValue(flagCursor),
			}, nil, flagAll, "cursor", "cursor", "limit", "", "", cmd.ErrOrStderr())
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Print provenance to stderr for human-facing output only.
			// Machine-format flags (--json, --csv, --compact, --quiet, --plain,
			// --select) and piped stdout suppress this line; the JSON envelope
			// already carries meta.source for those consumers.
			// SYNC: keep this gate aligned with command_promoted.go.tmpl.
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var countItems []json.RawMessage
				_ = json.Unmarshal(data, &countItems)
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope before passing through flags.
			// --select wins over --compact when both are set; --compact only runs when
			// no explicit fields were requested. Explicit format flags (--csv, --quiet,
			// --plain) opt out of the auto-JSON path so piped consumers that asked for
			// a non-JSON format reach the standard pipeline below.
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			// For all other output modes (table, csv, plain, quiet), use the standard pipeline
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&flagSortBy, "sort-by", "", "The column to sort the results by. Example: 'id'.")
	cmd.Flags().StringVar(&flagEventId, "event-id", "", "Filter by a specific process key and its children")
	cmd.Flags().StringVar(&flagEventSubTypes, "event-sub-types", "", "Filter events by sub-type. Example: 'PROCESSCREATION'.")
	cmd.Flags().StringVar(&flagLimit, "limit", "", "Limit number of returned items (1-1000). Example: '10'.")
	cmd.Flags().StringVar(&flagSkipCount, "skip-count", "", "If true, total number of items will not be calculated, which speeds up execution time.")
	cmd.Flags().StringVar(&flagSkip, "skip", "", "Skip first number of items (0-1000). To iterate over more than 1000 items, use 'cursor'. Example: '150'.")
	cmd.Flags().StringVar(&flagSortOrder, "sort-order", "", "Sort direction. Example: 'asc'.")
	cmd.Flags().StringVar(&flagEventTypes, "event-types", "", "Filter events by type. Example: 'events'.")
	cmd.Flags().StringVar(&flagProcessNameLike, "process-name-like", "", "Filter by process name (substring)")
	cmd.Flags().StringVar(&flagCountOnly, "count-only", "", "If true, only total number of items will be returned, without any of the actual objects.")
	cmd.Flags().StringVar(&flagCursor, "cursor", "", "Cursor position returned by the last request. Use to iterate over more than 1000 items.")
	cmd.Flags().BoolVar(&flagAll, "all", false, "Fetch all pages")

	return cmd
}
