// Copyright 2026 Damien Stevens and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newAppResellerResourceAccountV1UserDetailApiGetGetCmd(flags *rootFlags) *cobra.Command {
	var flagContext string
	var flagCompanyId string

	cmd := &cobra.Command{
		Use:         "resource-account-v1-user-detail-api-get-get <userId>",
		Short:       "Get a single user details",
		Example:     "  appdirect-cli app-reseller resource-account-v1-user-detail-api-get-get 550e8400-e29b-41d4-a716-446655440000 --context RESELLER --company-id 550e8400-e29b-41d4-a716-446655440000",
		Annotations: map[string]string{"pp:endpoint": "app-reseller.resource-account-v1-user-detail-api-get-get", "pp:method": "GET", "pp:path": "/appReseller/v1/users/{userId}", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			// Bare invocation of a command with required input prints help
			// instead of pflag's terse "required flag not set" error. Optional-
			// only read commands fall through so a bare call still executes.
			if cmd.Flags().NFlag() == 0 && len(args) == 0 && !flags.dryRun {
				return cmd.Help()
			}
			if len(args) == 0 {
				return cmd.Help()
			}
			if !cmd.Flags().Changed("context") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "context")
			}
			if !cmd.Flags().Changed("company-id") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "company-id")
			}
			if cmd.Flags().Changed("context") {
				allowedContext := []string{"RESELLER", "RESELLER_MANAGER"}
				validContext := false
				for _, v := range allowedContext {
					if flagContext == v {
						validContext = true
						break
					}
				}
				if !validContext {
					return fmt.Errorf("invalid value %q for --%s: must be one of %v", flagContext, "context", allowedContext)
				}
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/appReseller/v1/users/{userId}"
			path = replacePathParam(path, "userId", args[0])
			params := map[string]string{}
			if flagContext != "" {
				params["context"] = formatCLIParamValue(flagContext)
			}
			if flagCompanyId != "" {
				params["companyId"] = formatCLIParamValue(flagCompanyId)
			}
			data, prov, err := resolveReadWithStrategy(cmd.Context(), c, flags, "auto", "app-reseller", false, path, params, nil, cmd.ErrOrStderr())
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Print provenance to stderr for human-facing output only.
			// Machine-format flags (--json, --csv, --compact, --quiet, --plain,
			// --select) and piped stdout suppress this line; the JSON envelope
			// already carries meta.source for those consumers.
			// SYNC: keep this gate aligned with command_promoted.go.tmpl.
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var countItems []json.RawMessage
				_ = json.Unmarshal(data, &countItems)
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope before passing through flags.
			// --select wins over --compact when both are set; --compact only runs when
			// no explicit fields were requested. Explicit format flags (--csv, --quiet,
			// --plain) opt out of the auto-JSON path so piped consumers that asked for
			// a non-JSON format reach the standard pipeline below.
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			// For all other output modes (table, csv, plain, quiet), use the standard pipeline
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&flagContext, "context", "", "Context (one of: RESELLER, RESELLER_MANAGER)")
	cmd.Flags().StringVar(&flagCompanyId, "company-id", "", "User's company ID (some user details depend on the specified company)")

	return cmd
}
