// Copyright 2026 Damien Stevens and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"cipp-pp-cli/internal/cliutil"
	"github.com/spf13/cobra"
)

func newEditUserPromotedCmd(flags *rootFlags) *cobra.Command {
	var bodyAddToGroups string
	var bodyAddedAliases string
	var bodyAutopassword bool
	var bodyCopyFrom string
	var bodyDisplayName string
	var bodyDomain string
	var bodyMustChangePass bool
	var bodyPostExecution string
	var bodyRemoveFromGroups string
	var bodyScheduledDate string
	var bodyScheduledEnabled bool
	var bodyBusinessPhones string
	var bodyCity string
	var bodyCompanyName string
	var bodyCountry string
	var bodyCustomData string
	var bodyDefaultAttributes string
	var bodyDepartment string
	var bodyGivenName string
	var bodyId string
	var bodyJobTitle string
	var bodyLicenses string
	var bodyMailNickname string
	var bodyMobilePhone string
	var bodyOtherMails string
	var bodyPassword string
	var bodyPostalCode string
	var bodyPrimDomainValue string
	var bodyReference string
	var bodyRemoveLicenses bool
	var bodySetManagerLabel string
	var bodySetManagerValue string
	var bodySetSponsorLabel string
	var bodySetSponsorValue string
	var bodySherweb bool
	var bodySherwebLicenseValue string
	var bodyState string
	var bodyStreetAddress string
	var bodySurname string
	var bodyTenantFilter string
	var bodyUsageLocationValue string
	var bodyUserPrincipalName string
	var bodyUserTemplateLabel string
	var bodyUserTemplateValue string
	var bodyUsername string

	cmd := &cobra.Command{
		Use:   "edit-user",
		Short: "Edit user",
		Long:  "Edit user",
		// TODO: replace placeholder example values before relying on this for live dogfood.
		Example:     "  cipp-cli edit-user --tenant-filter example-value",
		Annotations: map[string]string{"pp:endpoint": "edit-user.update", "pp:method": "PATCH", "pp:path": "/EditUser"},
		RunE: func(cmd *cobra.Command, args []string) error {
			// Bare invocation of a command with a required flag/body prints help
			// instead of pflag's terse "required flag not set" error. Optional-
			// only reads fall through so a bare call still executes; positional
			// commands keep their existing usageErr (exit 2 + JSON envelope).
			if cmd.Flags().NFlag() == 0 && len(args) == 0 && !flags.dryRun {
				return cmd.Help()
			}
			if !cmd.Flags().Changed("tenant-filter") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "tenant-filter")
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/EditUser"
			params := map[string]string{}
			// HasStore + non-GET falls through to a live API call here
			// rather than through resolveRead (GET-only internally); a
			// body-aware cached read helper is filed as #425 for when a
			// second store-backed POST-search consumer ships.
			body := map[string]any{}
			if bodyAddToGroups != "" {
				body["AddToGroups"] = cliutil.SplitCSV(bodyAddToGroups)
			}
			if bodyAddedAliases != "" {
				body["AddedAliases"] = bodyAddedAliases
			}
			if cmd.Flags().Changed("autopassword") {
				body["Autopassword"] = bodyAutopassword
			}
			if bodyCopyFrom != "" {
				body["CopyFrom"] = bodyCopyFrom
			}
			if bodyDisplayName != "" {
				body["DisplayName"] = bodyDisplayName
			}
			if bodyDomain != "" {
				body["Domain"] = bodyDomain
			}
			if cmd.Flags().Changed("must-change-pass") {
				body["MustChangePass"] = bodyMustChangePass
			}
			if bodyPostExecution != "" {
				body["PostExecution"] = bodyPostExecution
			}
			if bodyRemoveFromGroups != "" {
				body["RemoveFromGroups"] = cliutil.SplitCSV(bodyRemoveFromGroups)
			}
			{
				nestedScheduled := map[string]any{}
				if bodyScheduledDate != "" {
					nestedScheduled["date"] = bodyScheduledDate
				}
				if cmd.Flags().Changed("scheduled-enabled") {
					nestedScheduled["enabled"] = bodyScheduledEnabled
				}
				if len(nestedScheduled) > 0 {
					body["Scheduled"] = nestedScheduled
				}
			}
			if bodyBusinessPhones != "" {
				body["businessPhones"] = bodyBusinessPhones
			}
			if bodyCity != "" {
				body["city"] = bodyCity
			}
			if bodyCompanyName != "" {
				body["companyName"] = bodyCompanyName
			}
			if bodyCountry != "" {
				body["country"] = bodyCountry
			}
			if bodyCustomData != "" {
				body["customData"] = bodyCustomData
			}
			if bodyDefaultAttributes != "" {
				body["defaultAttributes"] = bodyDefaultAttributes
			}
			if bodyDepartment != "" {
				body["department"] = bodyDepartment
			}
			if bodyGivenName != "" {
				body["givenName"] = bodyGivenName
			}
			if bodyId != "" {
				body["id"] = bodyId
			}
			if bodyJobTitle != "" {
				body["jobTitle"] = bodyJobTitle
			}
			if bodyLicenses != "" {
				body["licenses"] = cliutil.SplitCSV(bodyLicenses)
			}
			if bodyMailNickname != "" {
				body["mailNickname"] = bodyMailNickname
			}
			if bodyMobilePhone != "" {
				body["mobilePhone"] = bodyMobilePhone
			}
			if bodyOtherMails != "" {
				body["otherMails"] = bodyOtherMails
			}
			if bodyPassword != "" {
				body["password"] = bodyPassword
			}
			if bodyPostalCode != "" {
				body["postalCode"] = bodyPostalCode
			}
			{
				nestedPrimDomain := map[string]any{}
				if bodyPrimDomainValue != "" {
					nestedPrimDomain["value"] = bodyPrimDomainValue
				}
				if len(nestedPrimDomain) > 0 {
					body["primDomain"] = nestedPrimDomain
				}
			}
			if bodyReference != "" {
				body["reference"] = bodyReference
			}
			if cmd.Flags().Changed("remove-licenses") {
				body["removeLicenses"] = bodyRemoveLicenses
			}
			{
				nestedSetManager := map[string]any{}
				if bodySetManagerLabel != "" {
					nestedSetManager["label"] = bodySetManagerLabel
				}
				if bodySetManagerValue != "" {
					nestedSetManager["value"] = bodySetManagerValue
				}
				if len(nestedSetManager) > 0 {
					body["setManager"] = nestedSetManager
				}
			}
			{
				nestedSetSponsor := map[string]any{}
				if bodySetSponsorLabel != "" {
					nestedSetSponsor["label"] = bodySetSponsorLabel
				}
				if bodySetSponsorValue != "" {
					nestedSetSponsor["value"] = bodySetSponsorValue
				}
				if len(nestedSetSponsor) > 0 {
					body["setSponsor"] = nestedSetSponsor
				}
			}
			if cmd.Flags().Changed("sherweb") {
				body["sherweb"] = bodySherweb
			}
			{
				nestedSherwebLicense := map[string]any{}
				if bodySherwebLicenseValue != "" {
					nestedSherwebLicense["value"] = bodySherwebLicenseValue
				}
				if len(nestedSherwebLicense) > 0 {
					body["sherwebLicense"] = nestedSherwebLicense
				}
			}
			if bodyState != "" {
				body["state"] = bodyState
			}
			if bodyStreetAddress != "" {
				body["streetAddress"] = bodyStreetAddress
			}
			if bodySurname != "" {
				body["surname"] = bodySurname
			}
			if bodyTenantFilter != "" {
				body["tenantFilter"] = bodyTenantFilter
			}
			{
				nestedUsageLocation := map[string]any{}
				if bodyUsageLocationValue != "" {
					nestedUsageLocation["value"] = bodyUsageLocationValue
				}
				if len(nestedUsageLocation) > 0 {
					body["usageLocation"] = nestedUsageLocation
				}
			}
			if bodyUserPrincipalName != "" {
				body["userPrincipalName"] = bodyUserPrincipalName
			}
			{
				nestedUserTemplate := map[string]any{}
				if bodyUserTemplateLabel != "" {
					nestedUserTemplate["label"] = bodyUserTemplateLabel
				}
				if bodyUserTemplateValue != "" {
					nestedUserTemplate["value"] = bodyUserTemplateValue
				}
				if len(nestedUserTemplate) > 0 {
					body["userTemplate"] = nestedUserTemplate
				}
			}
			if bodyUsername != "" {
				body["username"] = bodyUsername
			}
			data, statusCode, err := c.PatchWithParams(cmd.Context(), path, params, body)

			if err != nil {
				return classifyAPIError(err, flags)
			}
			prov := attachFreshness(DataProvenance{Source: "live"}, flags)
			var partialFailure *partialFailureReport
			if !flags.dryRun && statusCode >= 200 && statusCode < 300 {
				partialFailure = detectPartialFailure(data)
			}
			if !flags.dryRun && statusCode >= 200 && statusCode < 300 && (partialFailure == nil || flags.allowPartialFailure) {
				writeMutationResponseToStore(cmd.Context(), "edit-user", data, "Results")
			}
			// Print provenance to stderr for human-facing output only.
			// Machine-format flags (--json, --csv, --compact, --quiet, --plain,
			// --select) and piped stdout suppress this line; the JSON envelope
			// already carries meta.source for those consumers.
			// SYNC: keep this gate aligned with command_endpoint.go.tmpl.
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var countItems []json.RawMessage
				if json.Unmarshal(data, &countItems) != nil {
					// Single object, not an array
					countItems = []json.RawMessage{data}
				}
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope. --select wins over
			// --compact when both are set; --compact only runs when no explicit
			// fields were requested. Explicit format flags (--csv, --quiet, --plain)
			// opt out of the auto-JSON path so piped consumers that asked for a
			// non-JSON format reach the standard pipeline below.
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&bodyAddToGroups, "add-to-groups", "", "Add to groups")
	cmd.Flags().StringVar(&bodyAddedAliases, "added-aliases", "", "Added aliases")
	cmd.Flags().BoolVar(&bodyAutopassword, "autopassword", false, "Autopassword")
	cmd.Flags().StringVar(&bodyCopyFrom, "copy-from", "", "Copy from")
	cmd.Flags().StringVar(&bodyDisplayName, "display-name", "", "Display name")
	cmd.Flags().StringVar(&bodyDomain, "domain", "", "Domain")
	cmd.Flags().BoolVar(&bodyMustChangePass, "must-change-pass", false, "Must change pass")
	cmd.Flags().StringVar(&bodyPostExecution, "post-execution", "", "Post execution")
	cmd.Flags().StringVar(&bodyRemoveFromGroups, "remove-from-groups", "", "Remove from groups")
	cmd.Flags().StringVar(&bodyScheduledDate, "scheduled-date", "", "Date")
	cmd.Flags().BoolVar(&bodyScheduledEnabled, "scheduled-enabled", false, "Enabled")
	cmd.Flags().StringVar(&bodyBusinessPhones, "business-phones", "", "Business phones")
	cmd.Flags().StringVar(&bodyCity, "city", "", "City")
	cmd.Flags().StringVar(&bodyCompanyName, "company-name", "", "Company name")
	cmd.Flags().StringVar(&bodyCountry, "country", "", "Country")
	cmd.Flags().StringVar(&bodyCustomData, "custom-data", "", "Custom data")
	cmd.Flags().StringVar(&bodyDefaultAttributes, "default-attributes", "", "Default attributes")
	cmd.Flags().StringVar(&bodyDepartment, "department", "", "Department")
	cmd.Flags().StringVar(&bodyGivenName, "given-name", "", "Given name")
	cmd.Flags().StringVar(&bodyId, "id", "", "Id")
	cmd.Flags().StringVar(&bodyJobTitle, "job-title", "", "Job title")
	cmd.Flags().StringVar(&bodyLicenses, "licenses", "", "Licenses")
	cmd.Flags().StringVar(&bodyMailNickname, "mail-nickname", "", "Mail nickname")
	cmd.Flags().StringVar(&bodyMobilePhone, "mobile-phone", "", "Mobile phone")
	cmd.Flags().StringVar(&bodyOtherMails, "other-mails", "", "Other mails")
	cmd.Flags().StringVar(&bodyPassword, "password", "", "Password")
	cmd.Flags().StringVar(&bodyPostalCode, "postal-code", "", "Postal code")
	cmd.Flags().StringVar(&bodyPrimDomainValue, "prim-domain-value", "", "Value")
	cmd.Flags().StringVar(&bodyReference, "reference", "", "Reference")
	cmd.Flags().BoolVar(&bodyRemoveLicenses, "remove-licenses", false, "Remove licenses")
	cmd.Flags().StringVar(&bodySetManagerLabel, "set-manager-label", "", "Label")
	cmd.Flags().StringVar(&bodySetManagerValue, "set-manager-value", "", "Value")
	cmd.Flags().StringVar(&bodySetSponsorLabel, "set-sponsor-label", "", "Label")
	cmd.Flags().StringVar(&bodySetSponsorValue, "set-sponsor-value", "", "Value")
	cmd.Flags().BoolVar(&bodySherweb, "sherweb", false, "Sherweb")
	cmd.Flags().StringVar(&bodySherwebLicenseValue, "sherweb-license-value", "", "Value")
	cmd.Flags().StringVar(&bodyState, "state", "", "State")
	cmd.Flags().StringVar(&bodyStreetAddress, "street-address", "", "Street address")
	cmd.Flags().StringVar(&bodySurname, "surname", "", "Surname")
	cmd.Flags().StringVar(&bodyTenantFilter, "tenant-filter", "", "Tenant filter")
	cmd.Flags().StringVar(&bodyUsageLocationValue, "usage-location-value", "", "Value")
	cmd.Flags().StringVar(&bodyUserPrincipalName, "user-principal-name", "", "User principal name")
	cmd.Flags().StringVar(&bodyUserTemplateLabel, "user-template-label", "", "Label")
	cmd.Flags().StringVar(&bodyUserTemplateValue, "user-template-value", "", "Value")
	cmd.Flags().StringVar(&bodyUsername, "username", "", "Username")

	// Wire sibling endpoints and sub-resources as subcommands

	return cmd
}
