// Copyright 2026 Damien Stevens and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newIncidentsNotesCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "notes",
		Short:       "List, create, update, and delete notes for incidents",
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newIncidentsNotesCreateIncidentCmd(flags))
	cmd.AddCommand(newIncidentsNotesDeleteIncidentCmd(flags))
	cmd.AddCommand(newIncidentsNotesListIncidentCmd(flags))
	cmd.AddCommand(newIncidentsNotesUpdateIncidentCmd(flags))
	return cmd
}
