// Copyright 2026 Damien Stevens and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"os"

	"github.com/spf13/cobra"
	"pagerduty-pp-cli/internal/cliutil"
)

func newPagerdutyAnalyticsGetMetricsPdAdvanceUsageFeaturesCmd(flags *rootFlags) *cobra.Command {
	var bodyFiltersCreatedAtEnd string
	var bodyFiltersCreatedAtStart string
	var bodyFiltersEscalationPolicyIds string
	var bodyFiltersIncidentCreatedAtEnd string
	var bodyFiltersIncidentCreatedAtStart string
	var bodyFiltersMajor bool
	var bodyFiltersMinAckowledgements int
	var bodyFiltersMinManualEscalations int
	var bodyFiltersMinTimeoutEscalations int
	var bodyFiltersPriorityIds string
	var bodyFiltersPriorityNames string
	var bodyFiltersServiceIds string
	var bodyFiltersTeamIds string
	var bodyFiltersUrgency string
	var bodyTimeZone string
	var stdinBody bool

	cmd := &cobra.Command{
		Use:         "get-metrics-pd-advance-usage-features",
		Short:       "Provides aggregated metrics for the usage of PD Advance. <!",
		Example:     "  pagerduty-cli pagerduty-analytics get-metrics-pd-advance-usage-features",
		Annotations: map[string]string{"pp:endpoint": "pagerduty-analytics.get-metrics-pd-advance-usage-features", "pp:method": "POST", "pp:path": "/analytics/metrics/pd_advance_usage/features"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if !stdinBody {
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/analytics/metrics/pd_advance_usage/features"
			params := map[string]string{}
			var body map[string]any
			if stdinBody {
				stdinData, err := io.ReadAll(os.Stdin)
				if err != nil {
					return fmt.Errorf("reading stdin: %w", err)
				}
				var jsonBody map[string]any
				if err := json.Unmarshal(stdinData, &jsonBody); err != nil {
					return fmt.Errorf("parsing stdin JSON: %w", err)
				}
				body = jsonBody
			} else {
				body = map[string]any{}
				{
					nestedFilters := map[string]any{}
					if bodyFiltersCreatedAtEnd != "" {
						nestedFilters["created_at_end"] = bodyFiltersCreatedAtEnd
					}
					if bodyFiltersCreatedAtStart != "" {
						nestedFilters["created_at_start"] = bodyFiltersCreatedAtStart
					}
					if bodyFiltersEscalationPolicyIds != "" {
						nestedFilters["escalation_policy_ids"] = cliutil.SplitCSV(bodyFiltersEscalationPolicyIds)
					}
					if bodyFiltersIncidentCreatedAtEnd != "" {
						nestedFilters["incident_created_at_end"] = bodyFiltersIncidentCreatedAtEnd
					}
					if bodyFiltersIncidentCreatedAtStart != "" {
						nestedFilters["incident_created_at_start"] = bodyFiltersIncidentCreatedAtStart
					}
					if cmd.Flags().Changed("filters-major") {
						nestedFilters["major"] = bodyFiltersMajor
					}
					if bodyFiltersMinAckowledgements != 0 {
						nestedFilters["min_ackowledgements"] = bodyFiltersMinAckowledgements
					}
					if bodyFiltersMinManualEscalations != 0 {
						nestedFilters["min_manual_escalations"] = bodyFiltersMinManualEscalations
					}
					if bodyFiltersMinTimeoutEscalations != 0 {
						nestedFilters["min_timeout_escalations"] = bodyFiltersMinTimeoutEscalations
					}
					if bodyFiltersPriorityIds != "" {
						nestedFilters["priority_ids"] = cliutil.SplitCSV(bodyFiltersPriorityIds)
					}
					if bodyFiltersPriorityNames != "" {
						nestedFilters["priority_names"] = cliutil.SplitCSV(bodyFiltersPriorityNames)
					}
					if bodyFiltersServiceIds != "" {
						nestedFilters["service_ids"] = cliutil.SplitCSV(bodyFiltersServiceIds)
					}
					if bodyFiltersTeamIds != "" {
						nestedFilters["team_ids"] = cliutil.SplitCSV(bodyFiltersTeamIds)
					}
					if bodyFiltersUrgency != "" {
						nestedFilters["urgency"] = bodyFiltersUrgency
					}
					if len(nestedFilters) > 0 {
						body["filters"] = nestedFilters
					}
				}
				if bodyTimeZone != "" {
					body["time_zone"] = bodyTimeZone
				}
			}
			data, statusCode, err := c.PostWithParams(cmd.Context(), path, params, body)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Inspect the mutate response body for a partial-failure-shaped
			// field (e.g. Google Ads `partialFailureError`). Several Google
			// APIs return 200 OK with a partial-failure field when some
			// operations in the batch failed; ignoring it silently swallows
			// real failures. Detection runs before output-mode selection so
			// the exit code is consistent regardless of how stdout is
			// rendered. --dry-run short-circuits because no real request
			// was sent.
			var partialFailure *partialFailureReport
			if !flags.dryRun && statusCode >= 200 && statusCode < 300 {
				partialFailure = detectPartialFailure(data)
				if partialFailure != nil {
					fmt.Fprintf(os.Stderr, "warning: partial failure detected in %s response: %s\n", "pagerduty-analytics", partialFailure.Message)
					if len(partialFailure.ResourceNames) > 0 {
						fmt.Fprintf(os.Stderr, "         succeeded: %d operation(s)\n", len(partialFailure.ResourceNames))
					}
				}
			}
			if !flags.dryRun && statusCode >= 200 && statusCode < 300 && (partialFailure == nil || flags.allowPartialFailure) {
				writeMutationResponseToStore(cmd.Context(), "pagerduty-analytics", data, "")
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				// Check if response contains an array (directly or wrapped in "data")
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
					} else {
						if partialFailure != nil && !flags.allowPartialFailure {
							return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "pagerduty-analytics", partialFailure.Message))
						}
						return nil
					}
				} else {
					var wrapped struct {
						Data []map[string]any `json:"data"`
					}
					if json.Unmarshal(data, &wrapped) == nil && len(wrapped.Data) > 0 {
						if err := printAutoTable(cmd.OutOrStdout(), wrapped.Data); err != nil {
							fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
						} else {
							if partialFailure != nil && !flags.allowPartialFailure {
								return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "pagerduty-analytics", partialFailure.Message))
							}
							return nil
						}
					}
				}
			}
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				if flags.quiet {
					if partialFailure != nil && !flags.allowPartialFailure {
						return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "pagerduty-analytics", partialFailure.Message))
					}
					return nil
				}
				envelope := map[string]any{
					"action":   "post",
					"resource": "pagerduty-analytics",
					"path":     path,
					"status":   statusCode,
					"success":  statusCode >= 200 && statusCode < 300 && (partialFailure == nil || flags.allowPartialFailure),
				}
				if partialFailure != nil {
					envelope["partial_failure"] = partialFailure
				}
				if flags.dryRun {
					envelope["dry_run"] = true
					envelope["status"] = 0
					envelope["success"] = false
				}
				// Verify-mode synthetic envelope detection runs against RAW data
				// (before --compact/--select filtering) so the sentinel field is
				// guaranteed to be visible even if the operator passes a filter
				// flag that would otherwise strip it. Surfaces a top-level
				// verify_noop signal + flips success to false. Mirrors the dry_run
				// shape above.
				if len(data) > 0 {
					var rawParsed any
					if err := json.Unmarshal(data, &rawParsed); err == nil {
						if m, ok := rawParsed.(map[string]any); ok {
							if v, ok := m["__pp_verify_synthetic__"].(bool); ok && v {
								envelope["verify_noop"] = true
								envelope["success"] = false
							}
						}
					}
				}
				// Apply --compact and --select to the API response before wrapping.
				// --select wins when both are set: explicit field choice trumps the
				// generic high-gravity allow-list. Otherwise --compact still applies
				// when --agent is on but the user did not name fields.
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				if len(filtered) > 0 {
					var parsed any
					if err := json.Unmarshal(filtered, &parsed); err == nil {
						envelope["data"] = parsed
					}
				}
				envelopeJSON, err := json.Marshal(envelope)
				if err != nil {
					return err
				}
				if perr := printOutput(cmd.OutOrStdout(), json.RawMessage(envelopeJSON), true); perr != nil {
					return perr
				}
				if partialFailure != nil && !flags.allowPartialFailure {
					return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "pagerduty-analytics", partialFailure.Message))
				}
				return nil
			}
			// Fall-through for mutate paths that did not hit the table or
			// asJSON branches: --quiet, --csv, --plain, and default terminal
			// raw output. printOutputWithFlags renders the body, then the
			// typed partial-failure exit fires unless --allow-partial-failure
			// downgrades it. Without this guard a partial failure would exit
			// 0 for these output modes — the exact silent-swallow regression
			// the surrounding patch is preventing for asJSON / piped output.
			if perr := printOutputWithFlags(cmd.OutOrStdout(), data, flags); perr != nil {
				return perr
			}
			if partialFailure != nil && !flags.allowPartialFailure {
				return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "pagerduty-analytics", partialFailure.Message))
			}
			return nil
		},
	}
	cmd.Flags().StringVar(&bodyFiltersCreatedAtEnd, "filters-created-at-end", "", "Accepts an ISO8601 DateTime string.")
	cmd.Flags().StringVar(&bodyFiltersCreatedAtStart, "filters-created-at-start", "", "Accepts an ISO8601 DateTime string.")
	cmd.Flags().StringVar(&bodyFiltersEscalationPolicyIds, "filters-escalation-policy-ids", "", "An array of escalation policy IDs. Only incidents related to these escalation policies will be included in the results.")
	cmd.Flags().StringVar(&bodyFiltersIncidentCreatedAtEnd, "filters-incident-created-at-end", "", "Accepts an ISO8601 DateTime string.")
	cmd.Flags().StringVar(&bodyFiltersIncidentCreatedAtStart, "filters-incident-created-at-start", "", "Accepts an ISO8601 DateTime string.")
	cmd.Flags().BoolVar(&bodyFiltersMajor, "filters-major", false, "A boolean flag including whether results should contain *only* [major incidents](https://support.pagerduty.")
	cmd.Flags().IntVar(&bodyFiltersMinAckowledgements, "filters-min-ackowledgements", 0, "An integer that sets the requirement for the minimum number of acknowledgements to occur on an incident.")
	cmd.Flags().IntVar(&bodyFiltersMinManualEscalations, "filters-min-manual-escalations", 0, "An integer that sets the requirement for the minimum number of manual escalations to occur on an incident.")
	cmd.Flags().IntVar(&bodyFiltersMinTimeoutEscalations, "filters-min-timeout-escalations", 0, "An integer that sets the requirement for the minimum number of timeout escalations to occur on an incident.")
	cmd.Flags().StringVar(&bodyFiltersPriorityIds, "filters-priority-ids", "", "An array of priority IDs. Only incidents with these priorities will be included in the results.")
	cmd.Flags().StringVar(&bodyFiltersPriorityNames, "filters-priority-names", "", "An array of user-defined priority names. Only incidents with these priorities will be included in the results.")
	cmd.Flags().StringVar(&bodyFiltersServiceIds, "filters-service-ids", "", "An array of service IDs. Only incidents related to these services will be included in the results.")
	cmd.Flags().StringVar(&bodyFiltersTeamIds, "filters-team-ids", "", "An array of team IDs. Only incidents related to these teams will be included in the results.")
	cmd.Flags().StringVar(&bodyFiltersUrgency, "filters-urgency", "", "Any incidents whose urgency does not match the provided string will be omitted from the results.")
	cmd.Flags().StringVar(&bodyTimeZone, "time-zone", "", "The time zone to use for the results and grouping. Must be in tzdata format.")
	cmd.Flags().BoolVar(&stdinBody, "stdin", false, "Read request body as JSON from stdin")

	return cmd
}
