// Copyright 2026 Damien Stevens and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newSchedulesGetV3Cmd(flags *rootFlags) *cobra.Command {
	var flagSince string
	var flagUntil string
	var flagTimeZone string
	var flagOverflow bool
	var flagInclude string

	cmd := &cobra.Command{
		Use:         "get-v3 <id>",
		Short:       "<!",
		Example:     "  pagerduty-cli schedules get-v3 PSJUKNI",
		Annotations: map[string]string{"pp:endpoint": "schedules.get-v3", "pp:method": "GET", "pp:path": "/v3/schedules/{id}", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) == 0 {
				return cmd.Help()
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/v3/schedules/{id}"
			path = replacePathParam(path, "id", args[0])
			params := map[string]string{}
			if flagSince != "" {
				params["since"] = formatCLIParamValue(flagSince)
			}
			if flagUntil != "" {
				params["until"] = formatCLIParamValue(flagUntil)
			}
			if flagTimeZone != "" {
				params["time_zone"] = formatCLIParamValue(flagTimeZone)
			}
			if flagOverflow != false {
				params["overflow"] = formatCLIParamValue(flagOverflow)
			}
			if flagInclude != "" {
				params["include[]"] = formatCLIParamValue(flagInclude)
			}
			data, prov, err := resolveReadWithStrategy(cmd.Context(), c, flags, "auto", "schedules", false, path, params, nil, cmd.ErrOrStderr())
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Print provenance to stderr for human-facing output only.
			// Machine-format flags (--json, --csv, --compact, --quiet, --plain,
			// --select) and piped stdout suppress this line; the JSON envelope
			// already carries meta.source for those consumers.
			// SYNC: keep this gate aligned with command_promoted.go.tmpl.
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var countItems []json.RawMessage
				_ = json.Unmarshal(data, &countItems)
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope before passing through flags.
			// --select wins over --compact when both are set; --compact only runs when
			// no explicit fields were requested. Explicit format flags (--csv, --quiet,
			// --plain) opt out of the auto-JSON path so piped consumers that asked for
			// a non-JSON format reach the standard pipeline below.
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			// For all other output modes (table, csv, plain, quiet), use the standard pipeline
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&flagSince, "since", "", "Start of time range (ISO 8601)")
	cmd.Flags().StringVar(&flagUntil, "until", "", "End of time range (ISO 8601)")
	cmd.Flags().StringVar(&flagTimeZone, "time-zone", "", "IANA timezone identifier for rendering shift times. Defaults to the schedule's configured time zone.")
	cmd.Flags().BoolVar(&flagOverflow, "overflow", false, "Include shifts that extend beyond the requested time range boundaries")
	cmd.Flags().StringVar(&flagInclude, "include", "", "Additional data to include in the schedule response: - `final_schedule`: computed on-call assignments for the time range")

	return cmd
}
