// Copyright 2026 Damien Stevens and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newSchedulesOverridesListScheduleCmd(flags *rootFlags) *cobra.Command {
	var flagSince string
	var flagUntil string
	var flagEditable bool
	var flagOverflow bool

	cmd := &cobra.Command{
		Use:         "list-schedule <id>",
		Short:       "List overrides for a given time range. A Schedule determines the time periods that users are On-Call.",
		Example:     "  pagerduty-cli schedules overrides list-schedule P2LJD7G --since 2026-04-01T00:00:00Z --until 2026-05-30T00:00:00Z",
		Annotations: map[string]string{"pp:endpoint": "overrides.list-schedule", "pp:method": "GET", "pp:path": "/schedules/{id}/overrides", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			// Bare invocation of a command with required input prints help
			// instead of pflag's terse "required flag not set" error. Optional-
			// only read commands fall through so a bare call still executes.
			if cmd.Flags().NFlag() == 0 && len(args) == 0 && !flags.dryRun {
				return cmd.Help()
			}
			if len(args) == 0 {
				return cmd.Help()
			}
			if !cmd.Flags().Changed("since") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "since")
			}
			if !cmd.Flags().Changed("until") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "until")
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/schedules/{id}/overrides"
			path = replacePathParam(path, "id", args[0])
			params := map[string]string{}
			if flagSince != "" {
				params["since"] = formatCLIParamValue(flagSince)
			}
			if flagUntil != "" {
				params["until"] = formatCLIParamValue(flagUntil)
			}
			if flagEditable != false {
				params["editable"] = formatCLIParamValue(flagEditable)
			}
			if flagOverflow != false {
				params["overflow"] = formatCLIParamValue(flagOverflow)
			}
			data, prov, err := resolveReadWithStrategy(cmd.Context(), c, flags, "auto", "overrides", false, path, params, nil, cmd.ErrOrStderr())
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Print provenance to stderr for human-facing output only.
			// Machine-format flags (--json, --csv, --compact, --quiet, --plain,
			// --select) and piped stdout suppress this line; the JSON envelope
			// already carries meta.source for those consumers.
			// SYNC: keep this gate aligned with command_promoted.go.tmpl.
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var countItems []json.RawMessage
				_ = json.Unmarshal(data, &countItems)
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope before passing through flags.
			// --select wins over --compact when both are set; --compact only runs when
			// no explicit fields were requested. Explicit format flags (--csv, --quiet,
			// --plain) opt out of the auto-JSON path so piped consumers that asked for
			// a non-JSON format reach the standard pipeline below.
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			// For all other output modes (table, csv, plain, quiet), use the standard pipeline
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&flagSince, "since", "", "The start of the date range over which you want to search.")
	cmd.Flags().StringVar(&flagUntil, "until", "", "The end of the date range over which you want to search.")
	cmd.Flags().BoolVar(&flagEditable, "editable", false, "When this parameter is present, only editable overrides will be returned.")
	cmd.Flags().BoolVar(&flagOverflow, "overflow", false, "Any on-call schedule entries that pass the date range bounds will be truncated at the bounds")

	return cmd
}
