// Copyright 2026 Damien Stevens and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newTeamsEscalationPoliciesCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "escalation-policies",
		Short:       "Escalation policies define which user should be alerted at which time.",
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newTeamsEscalationPoliciesDeleteTeamEscalationPolicyCmd(flags))
	cmd.AddCommand(newTeamsEscalationPoliciesUpdateTeamEscalationPolicyCmd(flags))
	return cmd
}
