// Copyright 2026 Damien Stevens and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newUsersNotificationSubscriptionsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "notification-subscriptions",
		Short:       "Manage notification subscriptions",
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newUsersNotificationSubscriptionsCreateUserCmd(flags))
	cmd.AddCommand(newUsersNotificationSubscriptionsGetUserCmd(flags))
	cmd.AddCommand(newUsersNotificationSubscriptionsUnsubscribeUserCmd(flags))
	return cmd
}
