// Copyright 2026 Damien Stevens and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"os"

	"github.com/spf13/cobra"
)

func newAlertsPostCmd(flags *rootFlags) *cobra.Command {
	var bodyAdditionalInfo string
	var bodyAlertCategoryID string
	var bodyCode int
	var bodyCustomerID string
	var bodyDeviceGuid string
	var bodyFolderID string
	var bodyMessageTemplate string
	var bodySeverity string
	var bodySnoozedEndDate string
	var bodyThresholdValue1 string
	var bodyThresholdValue2 string
	var bodyThresholdValue3 string
	var bodyThresholdValue4 string
	var bodyThresholdValue5 string
	var bodyTicketID string
	var bodyTitle string
	var stdinBody bool

	cmd := &cobra.Command{
		Use:         "post",
		Aliases:     []string{"create"},
		Short:       "Creates a new alert. Requires the device's global unique identifier (GUID).",
		Example:     "  atera-cli alerts post --device-guid 00000000-0000-0000-0000-000000000000",
		Annotations: map[string]string{"pp:endpoint": "alerts.post", "pp:method": "POST", "pp:path": "/alerts"},
		RunE: func(cmd *cobra.Command, args []string) error {
			// Bare invocation of a command with required input prints help
			// instead of pflag's terse "required flag not set" error. Optional-
			// only read commands fall through so a bare call still executes.
			if cmd.Flags().NFlag() == 0 && len(args) == 0 && !flags.dryRun {
				return cmd.Help()
			}
			if !stdinBody {
				if !cmd.Flags().Changed("customer-id") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "customer-id")
				}
				if !cmd.Flags().Changed("device-guid") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "device-guid")
				}
				if !cmd.Flags().Changed("title") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "title")
				}
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/alerts"
			params := map[string]string{}
			var body map[string]any
			if stdinBody {
				stdinData, err := io.ReadAll(os.Stdin)
				if err != nil {
					return fmt.Errorf("reading stdin: %w", err)
				}
				var jsonBody map[string]any
				if err := json.Unmarshal(stdinData, &jsonBody); err != nil {
					return fmt.Errorf("parsing stdin JSON: %w", err)
				}
				body = jsonBody
			} else {
				body = map[string]any{}
				if bodyAdditionalInfo != "" {
					body["AdditionalInfo"] = bodyAdditionalInfo
				}
				if bodyAlertCategoryID != "" {
					body["AlertCategoryID"] = bodyAlertCategoryID
				}
				if bodyCode != 0 {
					body["Code"] = bodyCode
				}
				if bodyCustomerID != "" {
					body["CustomerID"] = bodyCustomerID
				}
				if bodyDeviceGuid != "" {
					body["DeviceGuid"] = bodyDeviceGuid
				}
				if bodyFolderID != "" {
					body["FolderID"] = bodyFolderID
				}
				if bodyMessageTemplate != "" {
					body["MessageTemplate"] = bodyMessageTemplate
				}
				if bodySeverity != "" {
					body["Severity"] = bodySeverity
				}
				if bodySnoozedEndDate != "" {
					body["SnoozedEndDate"] = bodySnoozedEndDate
				}
				if bodyThresholdValue1 != "" {
					body["ThresholdValue1"] = bodyThresholdValue1
				}
				if bodyThresholdValue2 != "" {
					body["ThresholdValue2"] = bodyThresholdValue2
				}
				if bodyThresholdValue3 != "" {
					body["ThresholdValue3"] = bodyThresholdValue3
				}
				if bodyThresholdValue4 != "" {
					body["ThresholdValue4"] = bodyThresholdValue4
				}
				if bodyThresholdValue5 != "" {
					body["ThresholdValue5"] = bodyThresholdValue5
				}
				if bodyTicketID != "" {
					body["TicketID"] = bodyTicketID
				}
				if bodyTitle != "" {
					body["Title"] = bodyTitle
				}
			}
			data, statusCode, err := c.PostWithParams(cmd.Context(), path, params, body)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Inspect the mutate response body for a partial-failure-shaped
			// field (e.g. Google Ads `partialFailureError`). Several Google
			// APIs return 200 OK with a partial-failure field when some
			// operations in the batch failed; ignoring it silently swallows
			// real failures. Detection runs before output-mode selection so
			// the exit code is consistent regardless of how stdout is
			// rendered. --dry-run short-circuits because no real request
			// was sent.
			var partialFailure *partialFailureReport
			if !flags.dryRun && statusCode >= 200 && statusCode < 300 {
				partialFailure = detectPartialFailure(data)
				if partialFailure != nil {
					fmt.Fprintf(os.Stderr, "warning: partial failure detected in %s response: %s\n", "alerts", partialFailure.Message)
					if len(partialFailure.ResourceNames) > 0 {
						fmt.Fprintf(os.Stderr, "         succeeded: %d operation(s)\n", len(partialFailure.ResourceNames))
					}
				}
			}
			if !flags.dryRun && statusCode >= 200 && statusCode < 300 && (partialFailure == nil || flags.allowPartialFailure) {
				writeMutationResponseToStore(cmd.Context(), "alerts", data, "")
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				// Check if response contains an array (directly or wrapped in "data")
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
					} else {
						if partialFailure != nil && !flags.allowPartialFailure {
							return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "alerts", partialFailure.Message))
						}
						return nil
					}
				} else {
					var wrapped struct {
						Data []map[string]any `json:"data"`
					}
					if json.Unmarshal(data, &wrapped) == nil && len(wrapped.Data) > 0 {
						if err := printAutoTable(cmd.OutOrStdout(), wrapped.Data); err != nil {
							fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
						} else {
							if partialFailure != nil && !flags.allowPartialFailure {
								return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "alerts", partialFailure.Message))
							}
							return nil
						}
					}
				}
			}
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				if flags.quiet {
					if partialFailure != nil && !flags.allowPartialFailure {
						return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "alerts", partialFailure.Message))
					}
					return nil
				}
				envelope := map[string]any{
					"action":   "post",
					"resource": "alerts",
					"path":     path,
					"status":   statusCode,
					"success":  statusCode >= 200 && statusCode < 300 && (partialFailure == nil || flags.allowPartialFailure),
				}
				if partialFailure != nil {
					envelope["partial_failure"] = partialFailure
				}
				if flags.dryRun {
					envelope["dry_run"] = true
					envelope["status"] = 0
					envelope["success"] = false
				}
				// Verify-mode synthetic envelope detection runs against RAW data
				// (before --compact/--select filtering) so the sentinel field is
				// guaranteed to be visible even if the operator passes a filter
				// flag that would otherwise strip it. Surfaces a top-level
				// verify_noop signal + flips success to false. Mirrors the dry_run
				// shape above.
				if len(data) > 0 {
					var rawParsed any
					if err := json.Unmarshal(data, &rawParsed); err == nil {
						if m, ok := rawParsed.(map[string]any); ok {
							if v, ok := m["__pp_verify_synthetic__"].(bool); ok && v {
								envelope["verify_noop"] = true
								envelope["success"] = false
							}
						}
					}
				}
				// Apply --compact and --select to the API response before wrapping.
				// --select wins when both are set: explicit field choice trumps the
				// generic high-gravity allow-list. Otherwise --compact still applies
				// when --agent is on but the user did not name fields.
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				if len(filtered) > 0 {
					var parsed any
					if err := json.Unmarshal(filtered, &parsed); err == nil {
						envelope["data"] = parsed
					}
				}
				envelopeJSON, err := json.Marshal(envelope)
				if err != nil {
					return err
				}
				if perr := printOutput(cmd.OutOrStdout(), json.RawMessage(envelopeJSON), true); perr != nil {
					return perr
				}
				if partialFailure != nil && !flags.allowPartialFailure {
					return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "alerts", partialFailure.Message))
				}
				return nil
			}
			// Fall-through for mutate paths that did not hit the table or
			// asJSON branches: --quiet, --csv, --plain, and default terminal
			// raw output. printOutputWithFlags renders the body, then the
			// typed partial-failure exit fires unless --allow-partial-failure
			// downgrades it. Without this guard a partial failure would exit
			// 0 for these output modes — the exact silent-swallow regression
			// the surrounding patch is preventing for asJSON / piped output.
			if perr := printOutputWithFlags(cmd.OutOrStdout(), data, flags); perr != nil {
				return perr
			}
			if partialFailure != nil && !flags.allowPartialFailure {
				return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "alerts", partialFailure.Message))
			}
			return nil
		},
	}
	cmd.Flags().StringVar(&bodyAdditionalInfo, "additional-info", "", "Additional info")
	cmd.Flags().StringVar(&bodyAlertCategoryID, "alert-category-id", "", "Alert category id")
	cmd.Flags().IntVar(&bodyCode, "code", 0, "Code")
	cmd.Flags().StringVar(&bodyCustomerID, "customer-id", "", "Customer id")
	cmd.Flags().StringVar(&bodyDeviceGuid, "device-guid", "", "Device guid")
	cmd.Flags().StringVar(&bodyFolderID, "folder-id", "", "Folder id")
	cmd.Flags().StringVar(&bodyMessageTemplate, "message-template", "", "Message template")
	cmd.Flags().StringVar(&bodySeverity, "severity", "", "Severity")
	cmd.Flags().StringVar(&bodySnoozedEndDate, "snoozed-end-date", "", "Snoozed end date")
	cmd.Flags().StringVar(&bodyThresholdValue1, "threshold-value1", "", "Threshold value1")
	cmd.Flags().StringVar(&bodyThresholdValue2, "threshold-value2", "", "Threshold value2")
	cmd.Flags().StringVar(&bodyThresholdValue3, "threshold-value3", "", "Threshold value3")
	cmd.Flags().StringVar(&bodyThresholdValue4, "threshold-value4", "", "Threshold value4")
	cmd.Flags().StringVar(&bodyThresholdValue5, "threshold-value5", "", "Threshold value5")
	cmd.Flags().StringVar(&bodyTicketID, "ticket-id", "", "Ticket id")
	cmd.Flags().StringVar(&bodyTitle, "title", "", "Title")
	cmd.Flags().BoolVar(&stdinBody, "stdin", false, "Read request body as JSON from stdin")

	return cmd
}
