// Copyright 2026 Damien Stevens and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newCustomvaluesCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "customvalues",
		Short:       "Get, create, and update customvalues",
		Hidden:      true,
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newCustomvaluesCustomValuesGetCmd(flags))
	cmd.AddCommand(newCustomvaluesCustomValuesGetAgentFieldCmd(flags))
	cmd.AddCommand(newCustomvaluesCustomValuesGetAgentFieldsCmd(flags))
	cmd.AddCommand(newCustomvaluesCustomValuesGetContactFieldCmd(flags))
	cmd.AddCommand(newCustomvaluesCustomValuesGetContactFieldsCmd(flags))
	cmd.AddCommand(newCustomvaluesCustomValuesGetContractFieldCmd(flags))
	cmd.AddCommand(newCustomvaluesCustomValuesGetContractFieldsCmd(flags))
	cmd.AddCommand(newCustomvaluesCustomValuesGetCustomFieldsCmd(flags))
	cmd.AddCommand(newCustomvaluesCustomValuesGetCustomerFieldCmd(flags))
	cmd.AddCommand(newCustomvaluesCustomValuesGetCustomerFieldsCmd(flags))
	cmd.AddCommand(newCustomvaluesCustomValuesGetGenericFieldCmd(flags))
	cmd.AddCommand(newCustomvaluesCustomValuesGetGenericFieldsCmd(flags))
	cmd.AddCommand(newCustomvaluesCustomValuesGetHttpfieldCmd(flags))
	cmd.AddCommand(newCustomvaluesCustomValuesGetHttpfieldsCmd(flags))
	cmd.AddCommand(newCustomvaluesCustomValuesGetSlafieldCmd(flags))
	cmd.AddCommand(newCustomvaluesCustomValuesGetSlafieldsCmd(flags))
	cmd.AddCommand(newCustomvaluesCustomValuesGetSnmpfieldCmd(flags))
	cmd.AddCommand(newCustomvaluesCustomValuesGetSnmpfieldsCmd(flags))
	cmd.AddCommand(newCustomvaluesCustomValuesGetTcpfieldCmd(flags))
	cmd.AddCommand(newCustomvaluesCustomValuesGetTcpfieldsCmd(flags))
	cmd.AddCommand(newCustomvaluesCustomValuesGetTicketFieldCmd(flags))
	cmd.AddCommand(newCustomvaluesCustomValuesGetTicketFieldsCmd(flags))
	cmd.AddCommand(newCustomvaluesCustomValuesSetAgentFieldCmd(flags))
	cmd.AddCommand(newCustomvaluesCustomValuesSetAgentFieldAgentfieldCmd(flags))
	cmd.AddCommand(newCustomvaluesCustomValuesSetAgentFieldAgentfield2Cmd(flags))
	cmd.AddCommand(newCustomvaluesCustomValuesSetContactFieldCmd(flags))
	cmd.AddCommand(newCustomvaluesCustomValuesSetContactFieldContactfieldCmd(flags))
	cmd.AddCommand(newCustomvaluesCustomValuesSetContactFieldContactfield2Cmd(flags))
	cmd.AddCommand(newCustomvaluesCustomValuesSetContractFieldCmd(flags))
	cmd.AddCommand(newCustomvaluesCustomValuesSetContractFieldContractfieldCmd(flags))
	cmd.AddCommand(newCustomvaluesCustomValuesSetContractFieldContractfield2Cmd(flags))
	cmd.AddCommand(newCustomvaluesCustomValuesSetCustomerFieldCmd(flags))
	cmd.AddCommand(newCustomvaluesCustomValuesSetCustomerFieldCustomerfieldCmd(flags))
	cmd.AddCommand(newCustomvaluesCustomValuesSetCustomerFieldCustomerfield2Cmd(flags))
	cmd.AddCommand(newCustomvaluesCustomValuesSetGenericFieldCmd(flags))
	cmd.AddCommand(newCustomvaluesCustomValuesSetGenericFieldGenericfieldCmd(flags))
	cmd.AddCommand(newCustomvaluesCustomValuesSetGenericFieldGenericfield2Cmd(flags))
	cmd.AddCommand(newCustomvaluesCustomValuesSetHttpfieldCmd(flags))
	cmd.AddCommand(newCustomvaluesCustomValuesSetHttpfieldHttpfieldCmd(flags))
	cmd.AddCommand(newCustomvaluesCustomValuesSetHttpfieldHttpfield2Cmd(flags))
	cmd.AddCommand(newCustomvaluesCustomValuesSetSlafieldCmd(flags))
	cmd.AddCommand(newCustomvaluesCustomValuesSetSlafieldSlafieldCmd(flags))
	cmd.AddCommand(newCustomvaluesCustomValuesSetSlafieldSlafield2Cmd(flags))
	cmd.AddCommand(newCustomvaluesCustomValuesSetSnmpfieldCmd(flags))
	cmd.AddCommand(newCustomvaluesCustomValuesSetSnmpfieldSnmpfieldCmd(flags))
	cmd.AddCommand(newCustomvaluesCustomValuesSetSnmpfieldSnmpfield2Cmd(flags))
	cmd.AddCommand(newCustomvaluesCustomValuesSetTcpfieldCmd(flags))
	cmd.AddCommand(newCustomvaluesCustomValuesSetTcpfieldTcpfieldCmd(flags))
	cmd.AddCommand(newCustomvaluesCustomValuesSetTcpfieldTcpfield2Cmd(flags))
	cmd.AddCommand(newCustomvaluesCustomValuesSetTicketFieldCmd(flags))
	cmd.AddCommand(newCustomvaluesCustomValuesSetTicketFieldTicketfieldCmd(flags))
	cmd.AddCommand(newCustomvaluesCustomValuesSetTicketFieldTicketfield2Cmd(flags))
	return cmd
}
