// Copyright 2026 Damien Stevens and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package types

import "encoding/json"

type AddressDto struct {
	Apartment   string `json:"apartment"`
	City        string `json:"city"`
	CompanyName string `json:"companyName"`
	ContactName string `json:"contactName"`
	Country     string `json:"country"`
	State       string `json:"state"`
	Street      string `json:"street"`
	Zip         string `json:"zip"`
}

type BaseUpdateQuoteWidgetDto struct {
}

type BatchProductResponseDto struct {
	ExternalIdentifier string `json:"externalIdentifier"`
	Id                 string `json:"id"`
	Mpn                string `json:"mpn"`
	Name               string `json:"name"`
	ProductType        string `json:"productType"`
}

type BatchProductsResponseDto struct {
	Products json.RawMessage `json:"products"`
}

type BulkUpsertProductsDto struct {
	Products json.RawMessage `json:"products"`
}

type CategoryDto struct {
	ExternalIdentifier string `json:"externalIdentifier"`
	Id                 string `json:"id"`
	Name               string `json:"name"`
}

type CategoryResponseDto struct {
	AddingProductByAdminOnly bool            `json:"addingProductByAdminOnly"`
	Addons                   json.RawMessage `json:"addons"`
	BillingCode              float64         `json:"billingCode"`
	CompanyWhitelist         json.RawMessage `json:"companyWhitelist"`
	CostCenterId             string          `json:"costCenterId"`
	DeletedAt                string          `json:"deletedAt"`
	Description              string          `json:"description"`
	Digits                   float64         `json:"digits"`
	EmptyStockHidden         bool            `json:"emptyStockHidden"`
	HideAvailability         bool            `json:"hideAvailability"`
	Id                       string          `json:"id"`
	Image                    json.RawMessage `json:"image"`
	Listed                   bool            `json:"listed"`
	Markup                   float64         `json:"markup"`
	Name                     string          `json:"name"`
	ParentCategoryId         string          `json:"parentCategoryId"`
	QuoteDescription         string          `json:"quoteDescription"`
	RrpDiscount              float64         `json:"rrpDiscount"`
	ShippingTypeId           string          `json:"shippingTypeId"`
	ShortDescription         string          `json:"shortDescription"`
	Taxable                  bool            `json:"taxable"`
	Term                     string          `json:"term"`
	VatRateId                string          `json:"vatRateId"`
	View                     string          `json:"view"`
}

type CompanyDto struct {
	ExternalIdentifier  string          `json:"externalIdentifier"`
	ExternalIdentifiers json.RawMessage `json:"externalIdentifiers"`
	Id                  string          `json:"id"`
	Name                string          `json:"name"`
}

type CompanyResponseDto struct {
	AboutUs                  string          `json:"aboutUs"`
	AccountManagerId         string          `json:"accountManagerId"`
	Address                  json.RawMessage `json:"address"`
	Currency                 string          `json:"currency"`
	CustomFields             json.RawMessage `json:"customFields"`
	DefaultDeliveryAddressId string          `json:"defaultDeliveryAddressId"`
	DeliveryAddresses        json.RawMessage `json:"deliveryAddresses"`
	ExternalIdentifier       string          `json:"externalIdentifier"`
	ExternalIdentifiers      json.RawMessage `json:"externalIdentifiers"`
	Id                       string          `json:"id"`
	Labels                   json.RawMessage `json:"labels"`
	Name                     string          `json:"name"`
	ParentCompanyId          string          `json:"parentCompanyId"`
	QuotePaymentTermId       string          `json:"quotePaymentTermId"`
	Social                   json.RawMessage `json:"social"`
	StickyNote               string          `json:"stickyNote"`
	Telephone                string          `json:"telephone"`
	Type                     string          `json:"type"`
	Website                  string          `json:"website"`
}

type ContactDto struct {
	ExternalIdentifier  string          `json:"externalIdentifier"`
	ExternalIdentifiers json.RawMessage `json:"externalIdentifiers"`
	Id                  string          `json:"id"`
	Name                string          `json:"name"`
}

type ContactResponseDto struct {
	CompanyExtId        string          `json:"companyExtId"`
	CompanyId           string          `json:"companyId"`
	CompanyName         string          `json:"companyName"`
	Deleted             string          `json:"deleted"`
	Email               string          `json:"email"`
	ExternalIdentifier  string          `json:"externalIdentifier"`
	ExternalIdentifiers json.RawMessage `json:"externalIdentifiers"`
	FirstName           string          `json:"firstName"`
	Id                  string          `json:"id"`
	Labels              json.RawMessage `json:"labels"`
	LastName            string          `json:"lastName"`
	MiddleName          string          `json:"middleName"`
	MobilePhone         string          `json:"mobilePhone"`
	Phone               string          `json:"phone"`
}

type CreateCompanyDto struct {
	AboutUs                     string          `json:"aboutUs"`
	AccountManagerExtId         string          `json:"accountManagerExtId"`
	AccountManagerId            string          `json:"accountManagerId"`
	Address                     json.RawMessage `json:"address"`
	AvoidWebsiteLogo            bool            `json:"avoidWebsiteLogo"`
	BlockQuote                  bool            `json:"blockQuote"`
	Currency                    string          `json:"currency"`
	CustomFields                json.RawMessage `json:"customFields"`
	DefaultDeliveryAddressExtId string          `json:"defaultDeliveryAddressExtId"`
	DefaultDeliveryAddressId    string          `json:"defaultDeliveryAddressId"`
	DeliveryAddresses           json.RawMessage `json:"deliveryAddresses"`
	ExternalIdentifier          string          `json:"externalIdentifier"`
	Labels                      json.RawMessage `json:"labels"`
	Name                        string          `json:"name"`
	Number                      string          `json:"number"`
	ParentCompanyExtId          string          `json:"parentCompanyExtId"`
	ParentCompanyId             string          `json:"parentCompanyId"`
	QuotePaymentTermExtId       string          `json:"quotePaymentTermExtId"`
	QuotePaymentTermId          string          `json:"quotePaymentTermId"`
	StickyNote                  string          `json:"stickyNote"`
	TaxId                       string          `json:"taxId"`
	Telephone                   string          `json:"telephone"`
	Type                        string          `json:"type"`
	Website                     string          `json:"website"`
}

type CreateContactDto struct {
	CompanyExtId       string `json:"companyExtId"`
	CompanyId          string `json:"companyId"`
	Email              string `json:"email"`
	ExternalIdentifier string `json:"externalIdentifier"`
	FirstName          string `json:"firstName"`
	IsActive           bool   `json:"isActive"`
	LastName           string `json:"lastName"`
	MiddleName         string `json:"middleName"`
	MobilePhone        string `json:"mobilePhone"`
	Phone              string `json:"phone"`
}

type CreateProductPublicDto struct {
	CategoryId                string          `json:"categoryId"`
	Cost                      float64         `json:"cost"`
	CustomFields              json.RawMessage `json:"customFields"`
	Description               string          `json:"description"`
	DoesNotRequireProcurement bool            `json:"doesNotRequireProcurement"`
	ExternalIdentifier        string          `json:"externalIdentifier"`
	InternalProductId         string          `json:"internalProductId"`
	IsEligibleForRma          bool            `json:"isEligibleForRma"`
	IsSerialized              bool            `json:"isSerialized"`
	Listed                    bool            `json:"listed"`
	Logo                      string          `json:"logo"`
	Margin                    float64         `json:"margin"`
	Markup                    float64         `json:"markup"`
	Mpn                       string          `json:"mpn"`
	Msrp                      float64         `json:"msrp"`
	Name                      string          `json:"name"`
	Price                     float64         `json:"price"`
	ProductType               string          `json:"productType"`
	ShortDescription          string          `json:"shortDescription"`
	Term                      string          `json:"term"`
	Unit                      string          `json:"unit"`
	Vendor                    string          `json:"vendor"`
}

type CreateQuoteDto struct {
	OpportunityId string          `json:"opportunityId"`
	Products      json.RawMessage `json:"products"`
	TemplateId    string          `json:"templateId"`
	Title         string          `json:"title"`
}

type CreateQuoteProductDto struct {
	Id       string  `json:"id"`
	Quantity float64 `json:"quantity"`
}

type CreateQuoteTemplatePublicDto struct {
	AllowAnonymousApproval          bool            `json:"allowAnonymousApproval"`
	AllowRecipientManageDescription bool            `json:"allowRecipientManageDescription"`
	AllowRecipientManageLines       bool            `json:"allowRecipientManageLines"`
	ApprovalEmailTemplate           string          `json:"approvalEmailTemplate"`
	AttachPdf                       bool            `json:"attachPdf"`
	Attachments                     json.RawMessage `json:"attachments"`
	ContractDuration                string          `json:"contractDuration"`
	CoverTemplateId                 string          `json:"coverTemplateId"`
	Currency                        string          `json:"currency"`
	DisplayTableOfContents          bool            `json:"displayTableOfContents"`
	EntityLabels                    json.RawMessage `json:"entityLabels"`
	InsertWidgetsBeforeIndex        float64         `json:"insertWidgetsBeforeIndex"`
	Leasing                         string          `json:"leasing"`
	Name                            string          `json:"name"`
	Notify                          bool            `json:"notify"`
	NotifyOnlyFirst                 bool            `json:"notifyOnlyFirst"`
	PaymentTermId                   string          `json:"paymentTermId"`
	PaymentTypeId                   string          `json:"paymentTypeId"`
	ShowAvailability                bool            `json:"showAvailability"`
	ShowBundleProducts              string          `json:"showBundleProducts"`
	ShowContractItems               bool            `json:"showContractItems"`
	ShowContractTermTotal           bool            `json:"showContractTermTotal"`
	ShowGrandTotal                  bool            `json:"showGrandTotal"`
	ShowProductImage                bool            `json:"showProductImage"`
	ShowSignInForAnonymous          bool            `json:"showSignInForAnonymous"`
	ShowSubtotal                    bool            `json:"showSubtotal"`
	ShowTax                         bool            `json:"showTax"`
	ShowTotal                       bool            `json:"showTotal"`
	ShowTotalDetails                bool            `json:"showTotalDetails"`
	ShowWidgetSubtotals             bool            `json:"showWidgetSubtotals"`
	Styling                         string          `json:"styling"`
	ThankYouPage                    string          `json:"thankYouPage"`
	UseSignatureImage               bool            `json:"useSignatureImage"`
	Widgets                         json.RawMessage `json:"widgets"`
}

type CreateQuoteWidgetTemplatePublicDto struct {
	EntityLabels json.RawMessage `json:"entityLabels"`
	Name         string          `json:"name"`
	Order        float64         `json:"order"`
	Widget       string          `json:"widget"`
}

type DateTypeDto struct {
	Amount float64 `json:"amount"`
	Unit   string  `json:"unit"`
}

type DeliveryAddressDto struct {
	Apartment          string `json:"apartment"`
	City               string `json:"city"`
	CompanyName        string `json:"companyName"`
	ContactName        string `json:"contactName"`
	Country            string `json:"country"`
	ExternalIdentifier string `json:"externalIdentifier"`
	Id                 string `json:"id"`
	Listed             bool   `json:"listed"`
	State              string `json:"state"`
	Street             string `json:"street"`
	Zip                string `json:"zip"`
}

type DiscountGroupResponseDto struct {
	ClassificationIds json.RawMessage `json:"classificationIds"`
	CompanyIds        json.RawMessage `json:"companyIds"`
	Discounts         json.RawMessage `json:"discounts"`
	Id                string          `json:"id"`
	Name              string          `json:"name"`
}

type FieldValueResponseDto struct {
	Deleted            bool    `json:"deleted"`
	DisplayValue       string  `json:"displayValue"`
	ExternalIdentifier string  `json:"externalIdentifier"`
	Id                 string  `json:"id"`
	Order              float64 `json:"order"`
	ParentValue        string  `json:"parentValue"`
}

type FieldValuesResponseDto struct {
	Values json.RawMessage `json:"values"`
}

type IdentifiedCompanyResponseDto struct {
	Address            json.RawMessage `json:"address"`
	CustomFields       json.RawMessage `json:"customFields"`
	ExternalIdentifier string          `json:"externalIdentifier"`
	Id                 string          `json:"id"`
	Labels             json.RawMessage `json:"labels"`
	Name               string          `json:"name"`
	Number             string          `json:"number"`
}

type IdentifiedEntityResponseDto struct {
	CustomFields       json.RawMessage `json:"customFields"`
	ExternalIdentifier string          `json:"externalIdentifier"`
	Id                 string          `json:"id"`
	Labels             json.RawMessage `json:"labels"`
	Name               string          `json:"name"`
}

type IdentifiedOpportunityResponseDto struct {
	CustomFields       json.RawMessage `json:"customFields"`
	Description        string          `json:"description"`
	ExpectedCloseDate  string          `json:"expectedCloseDate"`
	ExternalIdentifier string          `json:"externalIdentifier"`
	Id                 string          `json:"id"`
	Labels             json.RawMessage `json:"labels"`
	Name               string          `json:"name"`
	StartDate          string          `json:"startDate"`
}

type IdentifiedPersonResponseDto struct {
	CustomFields       json.RawMessage `json:"customFields"`
	Email              string          `json:"email"`
	ExternalIdentifier string          `json:"externalIdentifier"`
	Id                 string          `json:"id"`
	Labels             json.RawMessage `json:"labels"`
	Name               string          `json:"name"`
}

type IdentifiedShippingResponseDto struct {
	Cost               float64         `json:"cost"`
	CustomFields       json.RawMessage `json:"customFields"`
	ExternalIdentifier string          `json:"externalIdentifier"`
	Id                 string          `json:"id"`
	Labels             json.RawMessage `json:"labels"`
	Name               string          `json:"name"`
	Price              float64         `json:"price"`
}

type OpportunityResponseDto struct {
	Category                  json.RawMessage `json:"category"`
	CategoryDisplayValue      string          `json:"categoryDisplayValue"`
	CategoryId                string          `json:"categoryId"`
	ClosedAt                  string          `json:"closedAt"`
	Company                   json.RawMessage `json:"company"`
	CompanyId                 string          `json:"companyId"`
	Contact                   json.RawMessage `json:"contact"`
	ContactId                 string          `json:"contactId"`
	CreatedAt                 string          `json:"createdAt"`
	CustomFields              json.RawMessage `json:"customFields"`
	DeletedAt                 string          `json:"deletedAt"`
	Description               string          `json:"description"`
	ExpectedCloseDate         string          `json:"expectedCloseDate"`
	ExternalIdentifier        string          `json:"externalIdentifier"`
	ExternalIdentifiers       json.RawMessage `json:"externalIdentifiers"`
	Id                        string          `json:"id"`
	LastQuoteApprovedAt       string          `json:"lastQuoteApprovedAt"`
	MonthlyChurn              float64         `json:"monthlyChurn"`
	MonthlyProfit             float64         `json:"monthlyProfit"`
	MonthlyRevenue            float64         `json:"monthlyRevenue"`
	Name                      string          `json:"name"`
	OneTimeProfit             float64         `json:"oneTimeProfit"`
	OnetimeRevenue            float64         `json:"onetimeRevenue"`
	Owner                     json.RawMessage `json:"owner"`
	OwnerId                   string          `json:"ownerId"`
	PipelineStage             json.RawMessage `json:"pipelineStage"`
	PipelineStageDisplayValue string          `json:"pipelineStageDisplayValue"`
	PipelineStageId           string          `json:"pipelineStageId"`
	Probability               float64         `json:"probability"`
	SalesCycleDurationDays    float64         `json:"salesCycleDurationDays"`
	Source                    json.RawMessage `json:"source"`
	StageUpdatedAt            string          `json:"stageUpdatedAt"`
	StartDate                 string          `json:"startDate"`
	StatusId                  string          `json:"statusId"`
	UpdatedAt                 string          `json:"updatedAt"`
	UseQuoteTotals            bool            `json:"useQuoteTotals"`
	ValueMonths               float64         `json:"valueMonths"`
	YearlyProfit              float64         `json:"yearlyProfit"`
}

type OwnerDto struct {
	ExternalIdentifier  string          `json:"externalIdentifier"`
	ExternalIdentifiers json.RawMessage `json:"externalIdentifiers"`
	Id                  string          `json:"id"`
	Name                string          `json:"name"`
}

type ParentProductCategoryResponseDto struct {
	Id   string `json:"id"`
	Name string `json:"name"`
}

type PaymentDetailsResponseDto struct {
	Amount float64 `json:"amount"`
	Date   string  `json:"date"`
	Number string  `json:"number"`
	Status string  `json:"status"`
}

type PipelineStageDto struct {
	ExternalIdentifier string `json:"externalIdentifier"`
	Id                 string `json:"id"`
	Name               string `json:"name"`
}

type PricingBookProductPublicDto struct {
	Cost      float64 `json:"cost"`
	Note      string  `json:"note"`
	Price     float64 `json:"price"`
	ProductId string  `json:"productId"`
	ValidFrom string  `json:"validFrom"`
	ValidTo   string  `json:"validTo"`
}

type PricingBookProductResponseDto struct {
	Cost      float64 `json:"cost"`
	Id        string  `json:"id"`
	Note      string  `json:"note"`
	Price     float64 `json:"price"`
	ProductId string  `json:"productId"`
	ValidFrom string  `json:"validFrom"`
	ValidTo   string  `json:"validTo"`
}

type PricingBookResponseDto struct {
	ClassificationIds json.RawMessage `json:"classificationIds"`
	CompanyIds        json.RawMessage `json:"companyIds"`
	Description       string          `json:"description"`
	Id                string          `json:"id"`
	Name              string          `json:"name"`
	Products          json.RawMessage `json:"products"`
	SpecialBidNumber  string          `json:"specialBidNumber"`
	ValidFrom         string          `json:"validFrom"`
	ValidTo           string          `json:"validTo"`
}

type ProductAddonDto struct {
}

type ProductCategoryResponseDto struct {
	Id             string `json:"id"`
	Name           string `json:"name"`
	ParentCategory string `json:"parentCategory"`
}

type ProductInventoryDto struct {
	CostPrice  float64         `json:"costPrice"`
	LocationId json.RawMessage `json:"locationId"`
	Quantity   float64         `json:"quantity"`
}

type ProductResponseDto struct {
	Category                  string          `json:"category"`
	CategoryId                string          `json:"categoryId"`
	Cost                      float64         `json:"cost"`
	CustomFields              json.RawMessage `json:"customFields"`
	Description               string          `json:"description"`
	DoesNotRequireProcurement bool            `json:"doesNotRequireProcurement"`
	Ean                       string          `json:"ean"`
	ExternalIdentifier        string          `json:"externalIdentifier"`
	ExternalIdentifiers       json.RawMessage `json:"externalIdentifiers"`
	Id                        string          `json:"id"`
	InternalProductId         string          `json:"internalProductId"`
	IsEligibleForRma          bool            `json:"isEligibleForRma"`
	IsSerialized              bool            `json:"isSerialized"`
	Labels                    json.RawMessage `json:"labels"`
	Listed                    bool            `json:"listed"`
	Logo                      string          `json:"logo"`
	Markup                    float64         `json:"markup"`
	Mpn                       string          `json:"mpn"`
	Msrp                      float64         `json:"msrp"`
	Name                      string          `json:"name"`
	Price                     float64         `json:"price"`
	ProductType               string          `json:"productType"`
	ShortDescription          string          `json:"shortDescription"`
	Taxes                     json.RawMessage `json:"taxes"`
	Term                      string          `json:"term"`
	Unit                      string          `json:"unit"`
	Vendor                    string          `json:"vendor"`
}

type PutProductInventoriesDto struct {
	Inventories json.RawMessage `json:"inventories"`
}

type QuoteApproverResponseDto struct {
	CustomFields       json.RawMessage `json:"customFields"`
	Date               string          `json:"date"`
	Email              string          `json:"email"`
	ExternalIdentifier string          `json:"externalIdentifier"`
	Id                 string          `json:"id"`
	Labels             json.RawMessage `json:"labels"`
	Name               string          `json:"name"`
}

type QuoteAttachmentResponseDto struct {
	Description string `json:"description"`
	Title       string `json:"title"`
	Type        string `json:"type"`
	Url         string `json:"url"`
}

type QuoteDiscountResponseDto struct {
	Amount          float64 `json:"amount"`
	FinalAmount     float64 `json:"finalAmount"`
	FinalPercentage float64 `json:"finalPercentage"`
	Name            string  `json:"name"`
	Type            string  `json:"type"`
}

type QuoteItemResponseDto struct {
	Category             string          `json:"category"`
	CommitmentTerm       string          `json:"commitmentTerm"`
	Cost                 float64         `json:"cost"`
	DeliveryDate         string          `json:"deliveryDate"`
	Discount             float64         `json:"discount"`
	DistributorProductId string          `json:"distributorProductId"`
	Id                   string          `json:"id"`
	Manufacturer         string          `json:"manufacturer"`
	Markup               float64         `json:"markup"`
	Mpn                  string          `json:"mpn"`
	Name                 string          `json:"name"`
	Price                float64         `json:"price"`
	PricingBook          string          `json:"pricingBook"`
	Product              string          `json:"product"`
	Quantity             float64         `json:"quantity"`
	RequiresProcurement  bool            `json:"requiresProcurement"`
	SetupCost            float64         `json:"setupCost"`
	SetupPrice           float64         `json:"setupPrice"`
	ShortDescription     string          `json:"shortDescription"`
	SpecialBidNumber     string          `json:"specialBidNumber"`
	Supplier             json.RawMessage `json:"supplier"`
	Term                 string          `json:"term"`
	Unit                 string          `json:"unit"`
}

type QuoteLeasingPublicDto struct {
	DownPayment  float64 `json:"downPayment"`
	FinalPayment float64 `json:"finalPayment"`
	Term         string  `json:"term"`
}

type QuotePricingBookResponseDto struct {
	CustomFields       json.RawMessage `json:"customFields"`
	ExternalIdentifier string          `json:"externalIdentifier"`
	Id                 string          `json:"id"`
	Labels             json.RawMessage `json:"labels"`
	Name               string          `json:"name"`
	SpecialBidNumber   string          `json:"specialBidNumber"`
}

type QuoteResponseDto struct {
	ApprovedAt        string          `json:"approvedAt"`
	Approvers         json.RawMessage `json:"approvers"`
	Attachments       json.RawMessage `json:"attachments"`
	Company           string          `json:"company"`
	Contact           string          `json:"contact"`
	ContractDuration  json.RawMessage `json:"contractDuration"`
	ContractEndDate   string          `json:"contractEndDate"`
	ContractStartDate string          `json:"contractStartDate"`
	CreatedAt         string          `json:"createdAt"`
	CreatedBy         string          `json:"createdBy"`
	DeclinedAt        string          `json:"declinedAt"`
	DeletedAt         string          `json:"deletedAt"`
	DeliveryAddress   string          `json:"deliveryAddress"`
	Discount          string          `json:"discount"`
	ExpiredAt         string          `json:"expiredAt"`
	ExpiresAt         string          `json:"expiresAt"`
	FormFields        json.RawMessage `json:"formFields"`
	Id                string          `json:"id"`
	InternalNote      string          `json:"internalNote"`
	Items             json.RawMessage `json:"items"`
	Link              string          `json:"link"`
	Note              string          `json:"note"`
	Number            string          `json:"number"`
	Opportunity       json.RawMessage `json:"opportunity"`
	Owner             string          `json:"owner"`
	PaymentDetails    json.RawMessage `json:"paymentDetails"`
	PaymentTerm       string          `json:"paymentTerm"`
	PoNumber          string          `json:"poNumber"`
	Primary           bool            `json:"primary"`
	SentAt            string          `json:"sentAt"`
	SentBy            string          `json:"sentBy"`
	ShippingType      string          `json:"shippingType"`
	Status            string          `json:"status"`
	Title             string          `json:"title"`
}

type QuoteTemplateResponseDto struct {
	AllowAnonymousApproval          bool            `json:"allowAnonymousApproval"`
	AllowRecipientManageDescription bool            `json:"allowRecipientManageDescription"`
	AllowRecipientManageLines       bool            `json:"allowRecipientManageLines"`
	ApprovalEmailTemplate           string          `json:"approvalEmailTemplate"`
	AttachPdf                       bool            `json:"attachPdf"`
	Attachments                     json.RawMessage `json:"attachments"`
	ContractDuration                json.RawMessage `json:"contractDuration"`
	CoverTemplateId                 string          `json:"coverTemplateId"`
	Currency                        string          `json:"currency"`
	DisplayTableOfContents          bool            `json:"displayTableOfContents"`
	EntityLabels                    json.RawMessage `json:"entityLabels"`
	Id                              string          `json:"id"`
	InsertWidgetsBeforeIndex        float64         `json:"insertWidgetsBeforeIndex"`
	Leasing                         json.RawMessage `json:"leasing"`
	LocalizationId                  string          `json:"localizationId"`
	Name                            string          `json:"name"`
	Notify                          bool            `json:"notify"`
	NotifyOnlyFirst                 bool            `json:"notifyOnlyFirst"`
	Order                           float64         `json:"order"`
	PaymentTermId                   string          `json:"paymentTermId"`
	PaymentTypeId                   string          `json:"paymentTypeId"`
	ShowAvailability                bool            `json:"showAvailability"`
	ShowBundleProducts              json.RawMessage `json:"showBundleProducts"`
	ShowContractItems               bool            `json:"showContractItems"`
	ShowContractTermTotal           bool            `json:"showContractTermTotal"`
	ShowGrandTotal                  bool            `json:"showGrandTotal"`
	ShowMpnOnQuote                  bool            `json:"showMpnOnQuote"`
	ShowProductImage                bool            `json:"showProductImage"`
	ShowSignInForAnonymous          bool            `json:"showSignInForAnonymous"`
	ShowSubtotal                    bool            `json:"showSubtotal"`
	ShowTax                         bool            `json:"showTax"`
	ShowTotal                       bool            `json:"showTotal"`
	ShowTotalDetails                bool            `json:"showTotalDetails"`
	ShowWidgetSubtotals             bool            `json:"showWidgetSubtotals"`
	Styling                         json.RawMessage `json:"styling"`
	ThankYouPage                    string          `json:"thankYouPage"`
	UseSignatureImage               bool            `json:"useSignatureImage"`
	Widgets                         json.RawMessage `json:"widgets"`
}

type QuoteTemplateStylingColorPublicDto struct {
	Heading string `json:"heading"`
	Text    string `json:"text"`
}

type QuoteTemplateStylingFontSizePublicDto struct {
	Heading1        float64 `json:"heading1"`
	Heading2        float64 `json:"heading2"`
	Heading3        float64 `json:"heading3"`
	Heading4        float64 `json:"heading4"`
	Heading5        float64 `json:"heading5"`
	Heading6        float64 `json:"heading6"`
	HeadingTemplate float64 `json:"headingTemplate"`
	Text            float64 `json:"text"`
}

type QuoteTemplateStylingLineHeightPublicDto struct {
	Heading float64 `json:"heading"`
	Text    float64 `json:"text"`
}

type QuoteTemplateStylingMarginPublicDto struct {
	Bottom float64 `json:"bottom"`
	Left   float64 `json:"left"`
	Right  float64 `json:"right"`
	Top    float64 `json:"top"`
}

type QuoteTemplateStylingPublicDto struct {
	Align       json.RawMessage `json:"align"`
	Color       string          `json:"color"`
	FontSize    string          `json:"fontSize"`
	FooterImage string          `json:"footerImage"`
	HeaderImage string          `json:"headerImage"`
	LineHeight  string          `json:"lineHeight"`
	Margin      string          `json:"margin"`
	Spacing     string          `json:"spacing"`
}

type QuoteTemplateStylingSpacingPublicDto struct {
	Heading   float64 `json:"heading"`
	Paragraph float64 `json:"paragraph"`
}

type QuoteWidgetTemplateResponseDto struct {
	EntityLabels    json.RawMessage `json:"entityLabels"`
	Id              string          `json:"id"`
	LocalizationId  string          `json:"localizationId"`
	LocalizationIds json.RawMessage `json:"localizationIds"`
	Name            string          `json:"name"`
	Order           float64         `json:"order"`
	Widget          json.RawMessage `json:"widget"`
}

type RootCategoryResponseDto struct {
	AddingProductByAdminOnly bool            `json:"addingProductByAdminOnly"`
	Addons                   json.RawMessage `json:"addons"`
	BillingCode              float64         `json:"billingCode"`
	Children                 json.RawMessage `json:"children"`
	CompanyWhitelist         json.RawMessage `json:"companyWhitelist"`
	CostCenterId             string          `json:"costCenterId"`
	DeletedAt                string          `json:"deletedAt"`
	Description              string          `json:"description"`
	Digits                   float64         `json:"digits"`
	EmptyStockHidden         bool            `json:"emptyStockHidden"`
	HideAvailability         bool            `json:"hideAvailability"`
	Id                       string          `json:"id"`
	Image                    json.RawMessage `json:"image"`
	Listed                   bool            `json:"listed"`
	Markup                   float64         `json:"markup"`
	Name                     string          `json:"name"`
	ParentCategoryId         string          `json:"parentCategoryId"`
	QuoteDescription         string          `json:"quoteDescription"`
	RrpDiscount              float64         `json:"rrpDiscount"`
	ShippingTypeId           string          `json:"shippingTypeId"`
	ShortDescription         string          `json:"shortDescription"`
	Taxable                  bool            `json:"taxable"`
	Term                     string          `json:"term"`
	VatRateId                string          `json:"vatRateId"`
	View                     string          `json:"view"`
}

type SourceDto struct {
	ExternalIdentifier string `json:"externalIdentifier"`
	Id                 string `json:"id"`
	Name               string `json:"name"`
}

type SyncStateDto struct {
	Error              string `json:"error"`
	ExternalIdentifier string `json:"externalIdentifier"`
	State              string `json:"state"`
}

type TaxResponseDto struct {
	Country   string  `json:"country"`
	Name      string  `json:"name"`
	Price     float64 `json:"price"`
	Quantity  float64 `json:"quantity"`
	StartDate string  `json:"startDate"`
	TaxId     string  `json:"taxId"`
}

type UpdateCompaniesDiscountGroupDto struct {
	CompanyIds json.RawMessage `json:"companyIds"`
}

type UpdateCompaniesDiscountGroupResponseDto struct {
	Message string `json:"message"`
}

type UpdateCompanyDto struct {
	AboutUs                     string          `json:"aboutUs"`
	AccountManagerExtId         string          `json:"accountManagerExtId"`
	AccountManagerId            string          `json:"accountManagerId"`
	Address                     json.RawMessage `json:"address"`
	AvoidWebsiteLogo            bool            `json:"avoidWebsiteLogo"`
	BlockQuote                  bool            `json:"blockQuote"`
	Currency                    string          `json:"currency"`
	CustomFields                json.RawMessage `json:"customFields"`
	DefaultDeliveryAddressExtId string          `json:"defaultDeliveryAddressExtId"`
	DefaultDeliveryAddressId    string          `json:"defaultDeliveryAddressId"`
	DeliveryAddresses           json.RawMessage `json:"deliveryAddresses"`
	ExternalIdentifier          string          `json:"externalIdentifier"`
	Labels                      json.RawMessage `json:"labels"`
	Name                        string          `json:"name"`
	Number                      string          `json:"number"`
	ParentCompanyExtId          string          `json:"parentCompanyExtId"`
	ParentCompanyId             string          `json:"parentCompanyId"`
	QuotePaymentTermExtId       string          `json:"quotePaymentTermExtId"`
	QuotePaymentTermId          string          `json:"quotePaymentTermId"`
	StickyNote                  string          `json:"stickyNote"`
	TaxId                       string          `json:"taxId"`
	Telephone                   string          `json:"telephone"`
	Type                        string          `json:"type"`
	Website                     string          `json:"website"`
}

type UpdateContactDto struct {
	CompanyExtId       string `json:"companyExtId"`
	CompanyId          string `json:"companyId"`
	Email              string `json:"email"`
	ExternalIdentifier string `json:"externalIdentifier"`
	FirstName          string `json:"firstName"`
	IsActive           bool   `json:"isActive"`
	LastName           string `json:"lastName"`
	MiddleName         string `json:"middleName"`
	MobilePhone        string `json:"mobilePhone"`
	Phone              string `json:"phone"`
}

type UpdateDiscountGroupDto struct {
	ClassificationIds json.RawMessage `json:"classificationIds"`
	CompanyIds        json.RawMessage `json:"companyIds"`
	Discounts         json.RawMessage `json:"discounts"`
	Name              string          `json:"name"`
}

type UpdatePricingBookPublicDto struct {
	ClassificationIds json.RawMessage `json:"classificationIds"`
	CompanyIds        json.RawMessage `json:"companyIds"`
	Description       string          `json:"description"`
	Name              string          `json:"name"`
	Products          json.RawMessage `json:"products"`
	SpecialBidNumber  string          `json:"specialBidNumber"`
}

type UpdatePublicFieldDto struct {
	Values json.RawMessage `json:"values"`
}

type UpdatePublicFieldValueDto struct {
	DisplayValue       string `json:"displayValue"`
	ExternalIdentifier string `json:"externalIdentifier"`
	IsDefault          bool   `json:"isDefault"`
}

type UpdateQuoteContentWidgetDto struct {
}

type UpdateQuoteFormWidgetDto struct {
}

type UpdateQuoteHtmlContentWidgetDto struct {
}

type UpdateQuoteImageWidgetDto struct {
}

type UpdateQuoteLeasingSummaryWidgetDto struct {
}

type UpdateQuoteSingleMediaWidgetDto struct {
}

type UpdateQuoteSummaryWidgetDto struct {
}

type UpdateQuoteTemplateItemsWidgetDto struct {
}

type UpdateQuoteTemplatePublicDto struct {
	AllowAnonymousApproval          bool            `json:"allowAnonymousApproval"`
	AllowRecipientManageDescription bool            `json:"allowRecipientManageDescription"`
	AllowRecipientManageLines       bool            `json:"allowRecipientManageLines"`
	ApprovalEmailTemplate           string          `json:"approvalEmailTemplate"`
	AttachPdf                       bool            `json:"attachPdf"`
	Attachments                     json.RawMessage `json:"attachments"`
	ContractDuration                string          `json:"contractDuration"`
	CoverTemplateId                 string          `json:"coverTemplateId"`
	Currency                        string          `json:"currency"`
	DisplayTableOfContents          bool            `json:"displayTableOfContents"`
	EntityLabels                    json.RawMessage `json:"entityLabels"`
	InsertWidgetsBeforeIndex        float64         `json:"insertWidgetsBeforeIndex"`
	Leasing                         string          `json:"leasing"`
	LocalizationId                  string          `json:"localizationId"`
	Name                            string          `json:"name"`
	Notify                          bool            `json:"notify"`
	NotifyOnlyFirst                 bool            `json:"notifyOnlyFirst"`
	Order                           float64         `json:"order"`
	PaymentTermId                   string          `json:"paymentTermId"`
	PaymentTypeId                   string          `json:"paymentTypeId"`
	ShowAvailability                bool            `json:"showAvailability"`
	ShowBundleProducts              string          `json:"showBundleProducts"`
	ShowContractItems               bool            `json:"showContractItems"`
	ShowContractTermTotal           bool            `json:"showContractTermTotal"`
	ShowGrandTotal                  bool            `json:"showGrandTotal"`
	ShowProductImage                bool            `json:"showProductImage"`
	ShowSignInForAnonymous          bool            `json:"showSignInForAnonymous"`
	ShowSubtotal                    bool            `json:"showSubtotal"`
	ShowTax                         bool            `json:"showTax"`
	ShowTotal                       bool            `json:"showTotal"`
	ShowTotalDetails                bool            `json:"showTotalDetails"`
	ShowWidgetSubtotals             bool            `json:"showWidgetSubtotals"`
	Styling                         string          `json:"styling"`
	ThankYouPage                    string          `json:"thankYouPage"`
	UseSignatureImage               bool            `json:"useSignatureImage"`
	Widgets                         json.RawMessage `json:"widgets"`
}

type UpdateQuoteTotalWidgetDto struct {
}

type UpdateQuoteWidgetTemplatePublicDto struct {
	EntityLabels    json.RawMessage `json:"entityLabels"`
	LocalizationId  string          `json:"localizationId"`
	LocalizationIds json.RawMessage `json:"localizationIds"`
	Name            string          `json:"name"`
	Order           float64         `json:"order"`
	Widget          string          `json:"widget"`
}

type UploadedImageDto struct {
}

type UpsertContactDto struct {
	CompanyExtId string `json:"companyExtId"`
	CompanyId    string `json:"companyId"`
	Email        string `json:"email"`
	FirstName    string `json:"firstName"`
	IsActive     bool   `json:"isActive"`
	LastName     string `json:"lastName"`
	MiddleName   string `json:"middleName"`
	MobilePhone  string `json:"mobilePhone"`
	Phone        string `json:"phone"`
}

type UpsertOpportunityDto struct {
	CategoryExtId      string          `json:"categoryExtId"`
	CategoryId         string          `json:"categoryId"`
	CompanyExtId       string          `json:"companyExtId"`
	CompanyId          string          `json:"companyId"`
	ContactExtId       string          `json:"contactExtId"`
	ContactId          string          `json:"contactId"`
	CustomFields       json.RawMessage `json:"customFields"`
	Description        string          `json:"description"`
	ExpectedCloseDate  string          `json:"expectedCloseDate"`
	MonthlyChurn       float64         `json:"monthlyChurn"`
	MonthlyRevenue     float64         `json:"monthlyRevenue"`
	Name               string          `json:"name"`
	OnetimeRevenue     float64         `json:"onetimeRevenue"`
	OwnerExtId         string          `json:"ownerExtId"`
	OwnerId            string          `json:"ownerId"`
	PipelineStageExtId string          `json:"pipelineStageExtId"`
	PipelineStageId    string          `json:"pipelineStageId"`
	Probability        float64         `json:"probability"`
	SourceExtId        string          `json:"sourceExtId"`
	SourceId           string          `json:"sourceId"`
	StartDate          string          `json:"startDate"`
	ValueMonths        float64         `json:"valueMonths"`
}

type UpsertProductDto struct {
	CategoryId                string          `json:"categoryId"`
	Cost                      float64         `json:"cost"`
	CustomFields              json.RawMessage `json:"customFields"`
	Description               string          `json:"description"`
	DoesNotRequireProcurement bool            `json:"doesNotRequireProcurement"`
	ExternalIdentifier        string          `json:"externalIdentifier"`
	InternalProductId         string          `json:"internalProductId"`
	IsEligibleForRma          bool            `json:"isEligibleForRma"`
	IsSerialized              bool            `json:"isSerialized"`
	Listed                    bool            `json:"listed"`
	Logo                      string          `json:"logo"`
	Margin                    float64         `json:"margin"`
	Markup                    float64         `json:"markup"`
	Mpn                       string          `json:"mpn"`
	Msrp                      float64         `json:"msrp"`
	Name                      string          `json:"name"`
	Price                     float64         `json:"price"`
	ProductType               string          `json:"productType"`
	ShortDescription          string          `json:"shortDescription"`
	Term                      string          `json:"term"`
	Unit                      string          `json:"unit"`
	Vendor                    string          `json:"vendor"`
}
