// Copyright 2026 Damien Stevens and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newStorageCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "storage",
		Short:       "Storage pools, statistics, and nodes",
		Hidden:      true,
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newStorageListCmd(flags))
	cmd.AddCommand(newStorageNodesCmd(flags))
	cmd.AddCommand(newStorageStatsCmd(flags))
	cmd.AddCommand(newNovelStorageGrowthCmd(flags))
	return cmd
}
