// Copyright 2026 Damien Stevens and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"os"

	"github.com/spf13/cobra"
)

func newCompaniesUpdateCompanyCmd(flags *rootFlags) *cobra.Command {
	var bodyAddressCity string
	var bodyAddressCountry string
	var bodyAddressPostalCode string
	var bodyAddressStateOrProvince string
	var bodyAddressStreet string
	var bodyAddressStreet2 string
	var bodyBillOnBehalfOfEnabled bool
	var bodyExternalId string
	var bodyId string
	var bodyName string
	var bodyOrderApprovalRequired bool
	var bodyPhone string
	var bodySelfServiceAllowed bool
	var bodyStatus string
	var bodyWebsite string
	var stdinBody bool

	cmd := &cobra.Command{
		Use:         "update-company <companyId>",
		Aliases:     []string{"update"},
		Short:       "Updates an existing Company. ATTENTION - at least one parameter has to be modified.",
		Example:     "  pax8-cli companies update-company f7fc273a-8d86-45c9-a26f-ffd42416adda",
		Annotations: map[string]string{"pp:endpoint": "companies.update-company", "pp:method": "PATCH", "pp:path": "/companies/{companyId}"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) == 0 {
				return cmd.Help()
			}
			if !stdinBody {
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/companies/{companyId}"
			path = replacePathParam(path, "companyId", args[0])
			params := map[string]string{}
			var body map[string]any
			if stdinBody {
				stdinData, err := io.ReadAll(os.Stdin)
				if err != nil {
					return fmt.Errorf("reading stdin: %w", err)
				}
				var jsonBody map[string]any
				if err := json.Unmarshal(stdinData, &jsonBody); err != nil {
					return fmt.Errorf("parsing stdin JSON: %w", err)
				}
				body = jsonBody
			} else {
				body = map[string]any{}
				{
					nestedAddress := map[string]any{}
					if bodyAddressCity != "" {
						nestedAddress["city"] = bodyAddressCity
					}
					if bodyAddressCountry != "" {
						nestedAddress["country"] = bodyAddressCountry
					}
					if bodyAddressPostalCode != "" {
						nestedAddress["postalCode"] = bodyAddressPostalCode
					}
					if bodyAddressStateOrProvince != "" {
						nestedAddress["stateOrProvince"] = bodyAddressStateOrProvince
					}
					if bodyAddressStreet != "" {
						nestedAddress["street"] = bodyAddressStreet
					}
					if bodyAddressStreet2 != "" {
						nestedAddress["street2"] = bodyAddressStreet2
					}
					if len(nestedAddress) > 0 {
						body["address"] = nestedAddress
					}
				}
				if cmd.Flags().Changed("bill-on-behalf-of-enabled") {
					body["billOnBehalfOfEnabled"] = bodyBillOnBehalfOfEnabled
				}
				if bodyExternalId != "" {
					body["externalId"] = bodyExternalId
				}
				if bodyId != "" {
					body["id"] = bodyId
				}
				if bodyName != "" {
					body["name"] = bodyName
				}
				if cmd.Flags().Changed("order-approval-required") {
					body["orderApprovalRequired"] = bodyOrderApprovalRequired
				}
				if bodyPhone != "" {
					body["phone"] = bodyPhone
				}
				if cmd.Flags().Changed("self-service-allowed") {
					body["selfServiceAllowed"] = bodySelfServiceAllowed
				}
				if bodyStatus != "" {
					body["status"] = bodyStatus
				}
				if bodyWebsite != "" {
					body["website"] = bodyWebsite
				}
			}
			data, statusCode, err := c.PatchWithParams(cmd.Context(), path, params, body)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Inspect the mutate response body for a partial-failure-shaped
			// field (e.g. Google Ads `partialFailureError`). Several Google
			// APIs return 200 OK with a partial-failure field when some
			// operations in the batch failed; ignoring it silently swallows
			// real failures. Detection runs before output-mode selection so
			// the exit code is consistent regardless of how stdout is
			// rendered. --dry-run short-circuits because no real request
			// was sent.
			var partialFailure *partialFailureReport
			if !flags.dryRun && statusCode >= 200 && statusCode < 300 {
				partialFailure = detectPartialFailure(data)
				if partialFailure != nil {
					fmt.Fprintf(os.Stderr, "warning: partial failure detected in %s response: %s\n", "companies", partialFailure.Message)
					if len(partialFailure.ResourceNames) > 0 {
						fmt.Fprintf(os.Stderr, "         succeeded: %d operation(s)\n", len(partialFailure.ResourceNames))
					}
				}
			}
			if !flags.dryRun && statusCode >= 200 && statusCode < 300 && (partialFailure == nil || flags.allowPartialFailure) {
				writeMutationResponseToStore(cmd.Context(), "companies", data, "contacts")
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				// Check if response contains an array (directly or wrapped in "data")
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
					} else {
						if partialFailure != nil && !flags.allowPartialFailure {
							return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "companies", partialFailure.Message))
						}
						return nil
					}
				} else {
					var wrapped struct {
						Data []map[string]any `json:"data"`
					}
					if json.Unmarshal(data, &wrapped) == nil && len(wrapped.Data) > 0 {
						if err := printAutoTable(cmd.OutOrStdout(), wrapped.Data); err != nil {
							fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
						} else {
							if partialFailure != nil && !flags.allowPartialFailure {
								return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "companies", partialFailure.Message))
							}
							return nil
						}
					}
				}
			}
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				if flags.quiet {
					if partialFailure != nil && !flags.allowPartialFailure {
						return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "companies", partialFailure.Message))
					}
					return nil
				}
				envelope := map[string]any{
					"action":   "patch",
					"resource": "companies",
					"path":     path,
					"status":   statusCode,
					"success":  statusCode >= 200 && statusCode < 300 && (partialFailure == nil || flags.allowPartialFailure),
				}
				if partialFailure != nil {
					envelope["partial_failure"] = partialFailure
				}
				if flags.dryRun {
					envelope["dry_run"] = true
					envelope["status"] = 0
					envelope["success"] = false
				}
				// Verify-mode synthetic envelope detection runs against RAW data
				// (before --compact/--select filtering) so the sentinel field is
				// guaranteed to be visible even if the operator passes a filter
				// flag that would otherwise strip it. Surfaces a top-level
				// verify_noop signal + flips success to false. Mirrors the dry_run
				// shape above.
				if len(data) > 0 {
					var rawParsed any
					if err := json.Unmarshal(data, &rawParsed); err == nil {
						if m, ok := rawParsed.(map[string]any); ok {
							if v, ok := m["__pp_verify_synthetic__"].(bool); ok && v {
								envelope["verify_noop"] = true
								envelope["success"] = false
							}
						}
					}
				}
				// Apply --compact and --select to the API response before wrapping.
				// --select wins when both are set: explicit field choice trumps the
				// generic high-gravity allow-list. Otherwise --compact still applies
				// when --agent is on but the user did not name fields.
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				if len(filtered) > 0 {
					var parsed any
					if err := json.Unmarshal(filtered, &parsed); err == nil {
						envelope["data"] = parsed
					}
				}
				envelopeJSON, err := json.Marshal(envelope)
				if err != nil {
					return err
				}
				if perr := printOutput(cmd.OutOrStdout(), json.RawMessage(envelopeJSON), true); perr != nil {
					return perr
				}
				if partialFailure != nil && !flags.allowPartialFailure {
					return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "companies", partialFailure.Message))
				}
				return nil
			}
			// Fall-through for mutate paths that did not hit the table or
			// asJSON branches: --quiet, --csv, --plain, and default terminal
			// raw output. printOutputWithFlags renders the body, then the
			// typed partial-failure exit fires unless --allow-partial-failure
			// downgrades it. Without this guard a partial failure would exit
			// 0 for these output modes — the exact silent-swallow regression
			// the surrounding patch is preventing for asJSON / piped output.
			if perr := printOutputWithFlags(cmd.OutOrStdout(), data, flags); perr != nil {
				return perr
			}
			if partialFailure != nil && !flags.allowPartialFailure {
				return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "companies", partialFailure.Message))
			}
			return nil
		},
	}
	cmd.Flags().StringVar(&bodyAddressCity, "address-city", "", "The city")
	cmd.Flags().StringVar(&bodyAddressCountry, "address-country", "", "The ISO 3166-1 alpha-2 code for the country")
	cmd.Flags().StringVar(&bodyAddressPostalCode, "address-postal-code", "", "The postal code")
	cmd.Flags().StringVar(&bodyAddressStateOrProvince, "address-state-or-province", "", "The state or province")
	cmd.Flags().StringVar(&bodyAddressStreet, "address-street", "", "The primary street information")
	cmd.Flags().StringVar(&bodyAddressStreet2, "address-street2", "", "The secondary street information")
	cmd.Flags().BoolVar(&bodyBillOnBehalfOfEnabled, "bill-on-behalf-of-enabled", false, "Value is ```true``` if Pax8 handles billing transactions, value is ```false``` if partner handles billing transactions")
	cmd.Flags().StringVar(&bodyExternalId, "external-id", "", "An external ID that can be assigned to the company for reference")
	cmd.Flags().StringVar(&bodyId, "id", "", "The unique id of the company")
	cmd.Flags().StringVar(&bodyName, "name", "", "The company name")
	cmd.Flags().BoolVar(&bodyOrderApprovalRequired, "order-approval-required", false, "Value is ```true``` if the company's self-service orders require approval, otherwise value is ```false```")
	cmd.Flags().StringVar(&bodyPhone, "phone", "", "The primary phone number of the company")
	cmd.Flags().BoolVar(&bodySelfServiceAllowed, "self-service-allowed", false, "Value is ```true``` if self-service privileges are available to the company, otherwise value is ```false```")
	cmd.Flags().StringVar(&bodyStatus, "status", "", "Company Status")
	cmd.Flags().StringVar(&bodyWebsite, "website", "", "The full URL of the company website")
	cmd.Flags().BoolVar(&stdinBody, "stdin", false, "Read request body as JSON from stdin")

	return cmd
}
