// Copyright 2026 Damien Stevens and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package types

import "encoding/json"

type Acknowledgement struct {
	Message string `json:"message"`
	Success bool   `json:"success"`
}

type AuditEntry struct {
	Description    string `json:"description"`
	EventType      string `json:"eventType"`
	NetworkAddress string `json:"networkAddress"`
	SessionName    string `json:"sessionName"`
	Time           string `json:"time"`
	UserName       string `json:"userName"`
}

type AuditInfo struct {
	EventTypes    json.RawMessage `json:"eventTypes"`
	RetentionDays int             `json:"retentionDays"`
}

type SecurityConfiguration struct {
	Roles json.RawMessage `json:"roles"`
	Users json.RawMessage `json:"users"`
}

type Session struct {
	ActiveConnections        int             `json:"activeConnections"`
	CustomProperties         json.RawMessage `json:"customProperties"`
	GuestLoggedOnUserName    string          `json:"guestLoggedOnUserName"`
	GuestMachineName         string          `json:"guestMachineName"`
	GuestNetworkAddress      string          `json:"guestNetworkAddress"`
	GuestOperatingSystemName string          `json:"guestOperatingSystemName"`
	Host                     string          `json:"host"`
	IsPublic                 bool            `json:"isPublic"`
	LastConnectedEventTime   string          `json:"lastConnectedEventTime"`
	Name                     string          `json:"name"`
	SessionID                string          `json:"sessionID"`
	SessionType              string          `json:"sessionType"`
}

type SessionDetail struct {
	ActiveConnections        int             `json:"activeConnections"`
	Connections              json.RawMessage `json:"connections"`
	CustomProperties         json.RawMessage `json:"customProperties"`
	Events                   json.RawMessage `json:"events"`
	GuestLoggedOnUserName    string          `json:"guestLoggedOnUserName"`
	GuestMachineName         string          `json:"guestMachineName"`
	GuestNetworkAddress      string          `json:"guestNetworkAddress"`
	GuestOperatingSystemName string          `json:"guestOperatingSystemName"`
	Host                     string          `json:"host"`
	IsPublic                 bool            `json:"isPublic"`
	LastConnectedEventTime   string          `json:"lastConnectedEventTime"`
	Name                     string          `json:"name"`
	SessionID                string          `json:"sessionID"`
	SessionType              string          `json:"sessionType"`
}

type SessionEvent struct {
	Data      string `json:"data"`
	EventType string `json:"eventType"`
	Host      string `json:"host"`
	SessionID string `json:"sessionID"`
	Time      string `json:"time"`
}

type SessionGroup struct {
	Name         string `json:"name"`
	SessionCount int    `json:"sessionCount"`
	SessionType  string `json:"sessionType"`
}

type SessionsGetAccessTokenResponse struct {
	AccessToken string `json:"accessToken"`
	Url         string `json:"url"`
}

type User struct {
	DisplayName       string          `json:"displayName"`
	Email             string          `json:"email"`
	IsDisabled        bool            `json:"isDisabled"`
	IsPasswordExpired bool            `json:"isPasswordExpired"`
	SecurityGroups    json.RawMessage `json:"securityGroups"`
	UserName          string          `json:"userName"`
}
