// Copyright 2026 Damien Stevens and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"os"
	"strconv"

	"github.com/spf13/cobra"
)

func newLaunchpointsLaunchpointCmd(flags *rootFlags) *cobra.Command {
	var bodyActiveEnd string
	var bodyActiveStart string
	var bodyAgentID string
	var bodyAlias string
	var bodyConfig string
	var bodyEnabled string
	var bodyEnvironmentID string
	var bodyFreqInterval int
	var bodyFreqType string
	var bodyInspectorID string
	var bodyParentID string
	var bodySecureConfig string
	var bodyVersion string
	var bodyVisible string
	var stdinBody bool

	cmd := &cobra.Command{
		Use:   "launchpoint",
		Short: "Create a launchpoint.",
		// TODO: replace placeholder example values before relying on this for live dogfood.
		Example:     "  liongard-cli launchpoints launchpoint --active-end example-value",
		Annotations: map[string]string{"pp:endpoint": "launchpoints.launchpoint", "pp:method": "POST", "pp:path": "/launchpoints"},
		RunE: func(cmd *cobra.Command, args []string) error {
			// Bare invocation of a command with required input prints help
			// instead of pflag's terse "required flag not set" error. Optional-
			// only read commands fall through so a bare call still executes.
			if cmd.Flags().NFlag() == 0 && len(args) == 0 && !flags.dryRun {
				return cmd.Help()
			}
			if !stdinBody {
				if !cmd.Flags().Changed("active-end") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "active-end")
				}
				if !cmd.Flags().Changed("active-start") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "active-start")
				}
				if !cmd.Flags().Changed("alias") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "alias")
				}
				if !cmd.Flags().Changed("config") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "config")
				}
				if !cmd.Flags().Changed("enabled") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "enabled")
				}
				if !cmd.Flags().Changed("freq-interval") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "freq-interval")
				}
				if !cmd.Flags().Changed("freq-type") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "freq-type")
				}
				if !cmd.Flags().Changed("version") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "version")
				}
				if !cmd.Flags().Changed("visible") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "visible")
				}
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/launchpoints"
			params := map[string]string{}
			var body map[string]any
			if stdinBody {
				stdinData, err := io.ReadAll(os.Stdin)
				if err != nil {
					return fmt.Errorf("reading stdin: %w", err)
				}
				var jsonBody map[string]any
				if err := json.Unmarshal(stdinData, &jsonBody); err != nil {
					return fmt.Errorf("parsing stdin JSON: %w", err)
				}
				body = jsonBody
			} else {
				body = map[string]any{}
				if bodyActiveEnd != "" {
					body["ActiveEnd"] = bodyActiveEnd
				}
				if bodyActiveStart != "" {
					body["ActiveStart"] = bodyActiveStart
				}
				{
					nestedAgent := map[string]any{}
					if bodyAgentID != "" {
						nestedAgent["ID"] = bodyAgentID
					}
					if len(nestedAgent) > 0 {
						body["Agent"] = nestedAgent
					}
				}
				if bodyAlias != "" {
					body["Alias"] = bodyAlias
				}
				if bodyConfig != "" {
					var parsedConfig any
					if err := json.Unmarshal([]byte(bodyConfig), &parsedConfig); err != nil {
						return fmt.Errorf("parsing --config JSON: %w", err)
					}
					body["Config"] = parsedConfig
				}
				if bodyEnabled != "" {
					parsedEnabled, err := strconv.ParseBool(bodyEnabled)
					if err != nil {
						return fmt.Errorf("parsing --enabled as bool: %w", err)
					}
					body["Enabled"] = parsedEnabled
				}
				{
					nestedEnvironment := map[string]any{}
					if bodyEnvironmentID != "" {
						nestedEnvironment["ID"] = bodyEnvironmentID
					}
					if len(nestedEnvironment) > 0 {
						body["Environment"] = nestedEnvironment
					}
				}
				if bodyFreqInterval != 0 {
					body["FreqInterval"] = bodyFreqInterval
				}
				if bodyFreqType != "" {
					body["FreqType"] = bodyFreqType
				}
				{
					nestedInspector := map[string]any{}
					if bodyInspectorID != "" {
						nestedInspector["ID"] = bodyInspectorID
					}
					if len(nestedInspector) > 0 {
						body["Inspector"] = nestedInspector
					}
				}
				if bodyParentID != "" {
					body["ParentID"] = bodyParentID
				}
				if bodySecureConfig != "" {
					var parsedSecureConfig any
					if err := json.Unmarshal([]byte(bodySecureConfig), &parsedSecureConfig); err != nil {
						return fmt.Errorf("parsing --secure-config JSON: %w", err)
					}
					body["SecureConfig"] = parsedSecureConfig
				}
				if bodyVersion != "" {
					body["Version"] = bodyVersion
				}
				if bodyVisible != "" {
					parsedVisible, err := strconv.ParseBool(bodyVisible)
					if err != nil {
						return fmt.Errorf("parsing --visible as bool: %w", err)
					}
					body["Visible"] = parsedVisible
				}
			}
			data, statusCode, err := c.PostWithParams(cmd.Context(), path, params, body)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Inspect the mutate response body for a partial-failure-shaped
			// field (e.g. Google Ads `partialFailureError`). Several Google
			// APIs return 200 OK with a partial-failure field when some
			// operations in the batch failed; ignoring it silently swallows
			// real failures. Detection runs before output-mode selection so
			// the exit code is consistent regardless of how stdout is
			// rendered. --dry-run short-circuits because no real request
			// was sent.
			var partialFailure *partialFailureReport
			if !flags.dryRun && statusCode >= 200 && statusCode < 300 {
				partialFailure = detectPartialFailure(data)
				if partialFailure != nil {
					fmt.Fprintf(os.Stderr, "warning: partial failure detected in %s response: %s\n", "launchpoints", partialFailure.Message)
					if len(partialFailure.ResourceNames) > 0 {
						fmt.Fprintf(os.Stderr, "         succeeded: %d operation(s)\n", len(partialFailure.ResourceNames))
					}
				}
			}
			if !flags.dryRun && statusCode >= 200 && statusCode < 300 && (partialFailure == nil || flags.allowPartialFailure) {
				writeMutationResponseToStore(cmd.Context(), "launchpoints", data, "CreatedBy")
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				// Check if response contains an array (directly or wrapped in "data")
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
					} else {
						if partialFailure != nil && !flags.allowPartialFailure {
							return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "launchpoints", partialFailure.Message))
						}
						return nil
					}
				} else {
					var wrapped struct {
						Data []map[string]any `json:"data"`
					}
					if json.Unmarshal(data, &wrapped) == nil && len(wrapped.Data) > 0 {
						if err := printAutoTable(cmd.OutOrStdout(), wrapped.Data); err != nil {
							fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
						} else {
							if partialFailure != nil && !flags.allowPartialFailure {
								return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "launchpoints", partialFailure.Message))
							}
							return nil
						}
					}
				}
			}
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				if flags.quiet {
					if partialFailure != nil && !flags.allowPartialFailure {
						return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "launchpoints", partialFailure.Message))
					}
					return nil
				}
				envelope := map[string]any{
					"action":   "post",
					"resource": "launchpoints",
					"path":     path,
					"status":   statusCode,
					"success":  statusCode >= 200 && statusCode < 300 && (partialFailure == nil || flags.allowPartialFailure),
				}
				if partialFailure != nil {
					envelope["partial_failure"] = partialFailure
				}
				if flags.dryRun {
					envelope["dry_run"] = true
					envelope["status"] = 0
					envelope["success"] = false
				}
				// Verify-mode synthetic envelope detection runs against RAW data
				// (before --compact/--select filtering) so the sentinel field is
				// guaranteed to be visible even if the operator passes a filter
				// flag that would otherwise strip it. Surfaces a top-level
				// verify_noop signal + flips success to false. Mirrors the dry_run
				// shape above.
				if len(data) > 0 {
					var rawParsed any
					if err := json.Unmarshal(data, &rawParsed); err == nil {
						if m, ok := rawParsed.(map[string]any); ok {
							if v, ok := m["__pp_verify_synthetic__"].(bool); ok && v {
								envelope["verify_noop"] = true
								envelope["success"] = false
							}
						}
					}
				}
				// Apply --compact and --select to the API response before wrapping.
				// --select wins when both are set: explicit field choice trumps the
				// generic high-gravity allow-list. Otherwise --compact still applies
				// when --agent is on but the user did not name fields.
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				if len(filtered) > 0 {
					var parsed any
					if err := json.Unmarshal(filtered, &parsed); err == nil {
						envelope["data"] = parsed
					}
				}
				envelopeJSON, err := json.Marshal(envelope)
				if err != nil {
					return err
				}
				if perr := printOutput(cmd.OutOrStdout(), json.RawMessage(envelopeJSON), true); perr != nil {
					return perr
				}
				if partialFailure != nil && !flags.allowPartialFailure {
					return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "launchpoints", partialFailure.Message))
				}
				return nil
			}
			// Fall-through for mutate paths that did not hit the table or
			// asJSON branches: --quiet, --csv, --plain, and default terminal
			// raw output. printOutputWithFlags renders the body, then the
			// typed partial-failure exit fires unless --allow-partial-failure
			// downgrades it. Without this guard a partial failure would exit
			// 0 for these output modes — the exact silent-swallow regression
			// the surrounding patch is preventing for asJSON / piped output.
			if perr := printOutputWithFlags(cmd.OutOrStdout(), data, flags); perr != nil {
				return perr
			}
			if partialFailure != nil && !flags.allowPartialFailure {
				return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "launchpoints", partialFailure.Message))
			}
			return nil
		},
	}
	cmd.Flags().StringVar(&bodyActiveEnd, "active-end", "", "Active end")
	cmd.Flags().StringVar(&bodyActiveStart, "active-start", "", "Active start")
	cmd.Flags().StringVar(&bodyAgentID, "agent-id", "", "Id")
	cmd.Flags().StringVar(&bodyAlias, "alias", "", "The friendly name of the launchpoint.")
	cmd.Flags().StringVar(&bodyConfig, "config", "", "The inspectors non Secure Configuration details, this is usually URLs or Configuration details")
	cmd.Flags().StringVar(&bodyEnabled, "enabled", "", "Enabled")
	cmd.Flags().StringVar(&bodyEnvironmentID, "environment-id", "", "Id")
	cmd.Flags().IntVar(&bodyFreqInterval, "freq-interval", 0, "Freq interval")
	cmd.Flags().StringVar(&bodyFreqType, "freq-type", "", "Allowed values include 'day', 'hour'")
	cmd.Flags().StringVar(&bodyInspectorID, "inspector-id", "", "Id")
	cmd.Flags().StringVar(&bodyParentID, "parent-id", "", "Parent id")
	cmd.Flags().StringVar(&bodySecureConfig, "secure-config", "", "The inspectors Secure Configuration details, this is usually passwords or Secret Tokens")
	cmd.Flags().StringVar(&bodyVersion, "version", "", "Version")
	cmd.Flags().StringVar(&bodyVisible, "visible", "", "Visible")
	cmd.Flags().BoolVar(&stdinBody, "stdin", false, "Read request body as JSON from stdin")

	return cmd
}
