// Copyright 2026 Damien Stevens and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newLaunchpointsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "launchpoints",
		Short:       "A Launchpoint is a configured Inspection. As an example, if you set up a domain inspector to run on liongard.",
		Hidden:      true,
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newLaunchpointsBulkDeleteCmd(flags))
	cmd.AddCommand(newLaunchpointsBulkRunCmd(flags))
	cmd.AddCommand(newLaunchpointsDeleteCmd(flags))
	cmd.AddCommand(newLaunchpointsGetCmd(flags))
	cmd.AddCommand(newLaunchpointsGetCountCmd(flags))
	cmd.AddCommand(newLaunchpointsLaunchpointCmd(flags))
	cmd.AddCommand(newLaunchpointsLaunchpointsbyIdCmd(flags))
	cmd.AddCommand(newLaunchpointsUpdateCmd(flags))
	cmd.AddCommand(newLaunchpointsUpdateBulkCmd(flags))
	cmd.AddCommand(newLaunchpointsRunCmd(flags))
	cmd.AddCommand(newNovelLaunchpointsRunStaleCmd(flags))
	cmd.AddCommand(newNovelLaunchpointsStaleCmd(flags))
	return cmd
}
