// Copyright 2026 Damien Stevens and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package types

import "encoding/json"

type Media struct {
	Id        int             `json:"id"`
	Slug      string          `json:"slug"`
	SourceUrl string          `json:"source_url"`
	MediaType string          `json:"media_type"`
	MimeType  string          `json:"mime_type"`
	AltText   string          `json:"alt_text"`
	Title     json.RawMessage `json:"title"`
}

type Page struct {
	Id        int             `json:"id"`
	Slug      string          `json:"slug"`
	Status    string          `json:"status"`
	Link      string          `json:"link"`
	Title     json.RawMessage `json:"title"`
	Content   json.RawMessage `json:"content"`
	Template  string          `json:"template"`
	Parent    int             `json:"parent"`
	MenuOrder int             `json:"menu_order"`
	Date      string          `json:"date"`
	Modified  string          `json:"modified"`
}

type Post struct {
	Id         int             `json:"id"`
	Slug       string          `json:"slug"`
	Status     string          `json:"status"`
	Link       string          `json:"link"`
	Title      json.RawMessage `json:"title"`
	Content    json.RawMessage `json:"content"`
	Categories json.RawMessage `json:"categories"`
	Tags       json.RawMessage `json:"tags"`
	Date       string          `json:"date"`
	Modified   string          `json:"modified"`
}

type Settings struct {
	Title       string `json:"title"`
	Description string `json:"description"`
	Url         string `json:"url"`
	Language    string `json:"language"`
}

type Term struct {
	Id          int    `json:"id"`
	Name        string `json:"name"`
	Slug        string `json:"slug"`
	Count       int    `json:"count"`
	Description string `json:"description"`
}

type User struct {
	Id   int    `json:"id"`
	Name string `json:"name"`
	Slug string `json:"slug"`
	Link string `json:"link"`
}
