// Copyright 2026 Damien Stevens and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newConfigurationsListCmd(flags *rootFlags) *cobra.Command {
	var flagFilterId int
	var flagFilterName string
	var flagFilterOrganizationId int
	var flagFilterSerialNumber string
	var flagFilterAssetTag string
	var flagFilterHostname string
	var flagPageNumber int
	var flagPageSize int
	var flagSort string
	var flagAll bool

	cmd := &cobra.Command{
		Use:         "list",
		Short:       "Use stable fields such as organization id, name, hostname, serial number, or asset tag before creating records.",
		Example:     "  itglue-cli configurations list --agent --select name,serial-number,primary-ip,configuration-type-name",
		Annotations: map[string]string{"pp:endpoint": "configurations.list", "pp:method": "GET", "pp:path": "/configurations", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/configurations"
			data, prov, err := resolvePaginatedReadWithStrategy(cmd.Context(), c, flags, "auto", "configurations", path, map[string]string{
				"filter[id]":              formatCLIParamValue(flagFilterId),
				"filter[name]":            formatCLIParamValue(flagFilterName),
				"filter[organization_id]": formatCLIParamValue(flagFilterOrganizationId),
				"filter[serial_number]":   formatCLIParamValue(flagFilterSerialNumber),
				"filter[asset_tag]":       formatCLIParamValue(flagFilterAssetTag),
				"filter[hostname]":        formatCLIParamValue(flagFilterHostname),
				"page[number]":            formatCLIParamValue(flagPageNumber),
				"page[size]":              formatCLIParamValue(flagPageSize),
				"sort":                    formatCLIParamValue(flagSort),
			}, nil, flagAll, "page[number]", "page", "page[size]", "", "", cmd.ErrOrStderr())
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Print provenance to stderr for human-facing output only.
			// Machine-format flags (--json, --csv, --compact, --quiet, --plain,
			// --select) and piped stdout suppress this line; the JSON envelope
			// already carries meta.source for those consumers.
			// SYNC: keep this gate aligned with command_promoted.go.tmpl.
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var countItems []json.RawMessage
				_ = json.Unmarshal(data, &countItems)
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope before passing through flags.
			// --select wins over --compact when both are set; --compact only runs when
			// no explicit fields were requested. Explicit format flags (--csv, --quiet,
			// --plain) opt out of the auto-JSON path so piped consumers that asked for
			// a non-JSON format reach the standard pipeline below.
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			// For all other output modes (table, csv, plain, quiet), use the standard pipeline
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().IntVar(&flagFilterId, "filter-id", 0, "Filter id")
	cmd.Flags().StringVar(&flagFilterName, "filter-name", "", "Exact match where supported by IT Glue.")
	cmd.Flags().IntVar(&flagFilterOrganizationId, "filter-organization-id", 0, "Filter organization id")
	cmd.Flags().StringVar(&flagFilterSerialNumber, "filter-serial-number", "", "Filter serial number")
	cmd.Flags().StringVar(&flagFilterAssetTag, "filter-asset-tag", "", "Filter asset tag")
	cmd.Flags().StringVar(&flagFilterHostname, "filter-hostname", "", "Filter hostname")
	cmd.Flags().IntVar(&flagPageNumber, "page-number", 0, "Page number")
	cmd.Flags().IntVar(&flagPageSize, "page-size", 0, "Page size")
	cmd.Flags().StringVar(&flagSort, "sort", "", "Comma separated sort fields; prefix with - for descending.")
	cmd.Flags().BoolVar(&flagAll, "all", false, "Fetch all pages")

	return cmd
}
