// Copyright 2026 Damien Stevens and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import "testing"

func TestForgottenAssetsFindsArchivedAgent(t *testing.T) {
	dbPath := seedNovelStore(t)
	out := runNovelCmd(t, newNovelForgottenAssetsCmd, "--offline-days", "2", "--db", dbPath)

	var rows []forgottenAssetRow
	mustUnmarshal(t, out, &rows)

	foundArchived := false
	for _, r := range rows {
		switch r.Kind {
		case "archived-agent":
			if r.Name == "glob-old" {
				foundArchived = true
			}
		case "offline-device":
			t.Fatalf("both fixture devices checked in today; none should be offline: %+v", r)
		}
	}
	if !foundArchived {
		t.Fatalf("archived agent glob-old missing from forgotten assets: %+v", rows)
	}
}
