// Copyright 2026 Damien Stevens and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newNovelContactsCmd(flags *rootFlags) *cobra.Command {

	cmd := &cobra.Command{
		Use:         "contacts",
		Short:       "contacts subcommands: bulk-update, funnel, win-back",
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}
	cmd.AddCommand(newNovelContactsBulkUpdateCmd(flags))
	cmd.AddCommand(newNovelContactsFunnelCmd(flags))
	cmd.AddCommand(newNovelContactsWinBackCmd(flags))
	return cmd
}
