// Copyright 2026 Damien Stevens and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"os"

	"github.com/spf13/cobra"
)

func newCompaniesC2cCompaniesCmd(flags *rootFlags) *cobra.Command {
	var bodyGoogleCheckcentralCheckStatus int
	var bodyGoogleEnabled bool
	var bodyGoogleLastBackupAt string
	var bodyGoogleMailboxes int
	var bodyGoogleNotes string
	var bodyMsCheckcentralCheckStatus int
	var bodyMsEnabled bool
	var bodyMsLastBackupAt string
	var bodyMsMailboxes int
	var bodyMsNotes string
	var stdinBody bool

	cmd := &cobra.Command{
		Use:         "companies <id>",
		Aliases:     []string{"update"},
		Short:       "Companies",
		Example:     "  servosity-cli companies c2c companies 550e8400-e29b-41d4-a716-446655440000",
		Annotations: map[string]string{"pp:endpoint": "c2c.companies", "pp:method": "PUT", "pp:path": "/companies/{id}/c2c/"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) == 0 {
				// A missing required positional is a usage error in every output
				// mode (matches command_promoted.go.tmpl). Machine callers
				// (--json/--agent) also get a JSON error envelope on stdout;
				// usageErr sets exit 2.
				if flags.asJSON {
					if printErr := printJSONFiltered(cmd.OutOrStdout(), map[string]any{
						"error": "missing required argument",
						"usage": fmt.Sprintf("%s%s", cmd.CommandPath(), " <id>"),
					}, flags); printErr != nil {
						return printErr
					}
				}
				return usageErr(fmt.Errorf("missing required argument\nUsage: %s%s", cmd.CommandPath(), " <id>"))
			}
			if !stdinBody {
			}
			path := "/companies/{id}/c2c/"
			if len(args) < 1 || args[0] == "" {
				return usageErr(fmt.Errorf("id is required\nUsage: %s <%s>", cmd.CommandPath(), "id"))
			}
			path = replacePathParam(path, "id", args[0])
			c, err := flags.newClient()
			if err != nil {
				return err
			}
			params := map[string]string{}
			var body any
			if stdinBody {
				stdinData, err := io.ReadAll(os.Stdin)
				if err != nil {
					return fmt.Errorf("reading stdin: %w", err)
				}
				var jsonBody map[string]any
				if err := json.Unmarshal(stdinData, &jsonBody); err != nil {
					return fmt.Errorf("parsing stdin JSON: %w", err)
				}
				body = jsonBody
			} else {
				bodyMap := map[string]any{}
				body = bodyMap
				if cmd.Flags().Changed("google-checkcentral-check-status") || bodyGoogleCheckcentralCheckStatus != 0 {
					bodyMap["google_checkcentral_check_status"] = bodyGoogleCheckcentralCheckStatus
				}
				if cmd.Flags().Changed("google-enabled") {
					bodyMap["google_enabled"] = bodyGoogleEnabled
				}
				if cmd.Flags().Changed("google-last-backup-at") || bodyGoogleLastBackupAt != "" {
					bodyMap["google_last_backup_at"] = bodyGoogleLastBackupAt
				}
				if cmd.Flags().Changed("google-mailboxes") || bodyGoogleMailboxes != 0 {
					bodyMap["google_mailboxes"] = bodyGoogleMailboxes
				}
				if cmd.Flags().Changed("google-notes") || bodyGoogleNotes != "" {
					bodyMap["google_notes"] = bodyGoogleNotes
				}
				if cmd.Flags().Changed("ms-checkcentral-check-status") || bodyMsCheckcentralCheckStatus != 0 {
					bodyMap["ms_checkcentral_check_status"] = bodyMsCheckcentralCheckStatus
				}
				if cmd.Flags().Changed("ms-enabled") {
					bodyMap["ms_enabled"] = bodyMsEnabled
				}
				if cmd.Flags().Changed("ms-last-backup-at") || bodyMsLastBackupAt != "" {
					bodyMap["ms_last_backup_at"] = bodyMsLastBackupAt
				}
				if cmd.Flags().Changed("ms-mailboxes") || bodyMsMailboxes != 0 {
					bodyMap["ms_mailboxes"] = bodyMsMailboxes
				}
				if cmd.Flags().Changed("ms-notes") || bodyMsNotes != "" {
					bodyMap["ms_notes"] = bodyMsNotes
				}
			}
			data, statusCode, err := c.PutWithParams(cmd.Context(), path, params, body)
			if err != nil {
				return classifyAPIError(cmd.OutOrStdout(), err, flags)
			}
			// Inspect the mutate response body for a partial-failure-shaped
			// field (e.g. Google Ads `partialFailureError`). Several Google
			// APIs return 200 OK with a partial-failure field when some
			// operations in the batch failed; ignoring it silently swallows
			// real failures. Detection runs before output-mode selection so
			// the exit code is consistent regardless of how stdout is
			// rendered. --dry-run short-circuits because no real request
			// was sent.
			var partialFailure *partialFailureReport
			if !flags.dryRun && statusCode >= 200 && statusCode < 300 {
				partialFailure = detectPartialFailure(data)
				if partialFailure != nil {
					fmt.Fprintf(os.Stderr, "warning: partial failure detected in %s response: %s\n", "c2c", partialFailure.Message)
					if len(partialFailure.ResourceNames) > 0 {
						fmt.Fprintf(os.Stderr, "         succeeded: %d operation(s)\n", len(partialFailure.ResourceNames))
					}
				}
			}
			if !flags.dryRun && statusCode >= 200 && statusCode < 300 && (partialFailure == nil || flags.allowPartialFailure) {
				writeMutationResponseToStore(cmd.Context(), "c2c", data, "")
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				// Check if response contains an array (directly or wrapped in "data")
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
					} else {
						if partialFailure != nil && !flags.allowPartialFailure {
							return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "c2c", partialFailure.Message))
						}
						return nil
					}
				} else {
					var wrapped struct {
						Data []map[string]any `json:"data"`
					}
					if json.Unmarshal(data, &wrapped) == nil && len(wrapped.Data) > 0 {
						if err := printAutoTable(cmd.OutOrStdout(), wrapped.Data); err != nil {
							fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
						} else {
							if partialFailure != nil && !flags.allowPartialFailure {
								return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "c2c", partialFailure.Message))
							}
							return nil
						}
					}
				}
			}
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				if flags.quiet {
					if partialFailure != nil && !flags.allowPartialFailure {
						return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "c2c", partialFailure.Message))
					}
					return nil
				}
				envelope := map[string]any{
					"action":   "put",
					"resource": "c2c",
					"path":     path,
					"status":   statusCode,
					"success":  statusCode >= 200 && statusCode < 300 && (partialFailure == nil || flags.allowPartialFailure),
				}
				if flags.agent {
					envelope["meta"] = map[string]any{"source": "live"}
				}
				if partialFailure != nil {
					envelope["partial_failure"] = partialFailure
				}
				if flags.dryRun {
					envelope["dry_run"] = true
					envelope["status"] = 0
					envelope["success"] = false
				}
				// Verify-mode synthetic envelope detection runs against RAW data
				// (before --compact/--select filtering) so the sentinel field is
				// guaranteed to be visible even if the operator passes a filter
				// flag that would otherwise strip it. Surfaces a top-level
				// verify_noop signal + flips success to false. Mirrors the dry_run
				// shape above.
				if len(data) > 0 {
					var rawParsed any
					if err := json.Unmarshal(data, &rawParsed); err == nil {
						if m, ok := rawParsed.(map[string]any); ok {
							if v, ok := m["__pp_verify_synthetic__"].(bool); ok && v {
								envelope["verify_noop"] = true
								envelope["success"] = false
							}
						}
					}
				}
				// Apply --compact and --select to the API response before wrapping.
				// --select wins when both are set: explicit field choice trumps the
				// generic high-gravity allow-list. Otherwise --compact still applies
				// when --agent is on but the user did not name fields.
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered, nil)
				}
				if len(filtered) > 0 {
					var parsed any
					if err := json.Unmarshal(filtered, &parsed); err == nil {
						if flags.agent {
							envelope["results"] = parsed
						} else {
							envelope["data"] = parsed
						}
					}
				}
				envelopeJSON, err := json.Marshal(envelope)
				if err != nil {
					return err
				}
				resultKey := "data"
				if flags.agent {
					resultKey = "results"
				}
				structured, err := wrapPlatformStructuredOutput(json.RawMessage(envelopeJSON), flags, resultKey, true)
				if err != nil {
					return err
				}
				if perr := printOutput(cmd.OutOrStdout(), structured, true); perr != nil {
					return perr
				}
				if partialFailure != nil && !flags.allowPartialFailure {
					return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "c2c", partialFailure.Message))
				}
				return nil
			}
			// Fall-through for mutate paths that did not hit the table or
			// asJSON branches: --quiet, --csv, --plain, and default terminal
			// raw output. printOutputWithFlags renders the body, then the
			// typed partial-failure exit fires unless --allow-partial-failure
			// downgrades it. Without this guard a partial failure would exit
			// 0 for these output modes — the exact silent-swallow regression
			// the surrounding patch is preventing for asJSON / piped output.
			if perr := printOutputWithFlags(cmd.OutOrStdout(), data, flags); perr != nil {
				return perr
			}
			if partialFailure != nil && !flags.allowPartialFailure {
				return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "c2c", partialFailure.Message))
			}
			return nil
		},
	}
	cmd.Flags().IntVar(&bodyGoogleCheckcentralCheckStatus, "google-checkcentral-check-status", 0, "Google checkcentral check status")
	cmd.Flags().BoolVar(&bodyGoogleEnabled, "google-enabled", false, "Google enabled")
	cmd.Flags().StringVar(&bodyGoogleLastBackupAt, "google-last-backup-at", "", "Google last backup at")
	cmd.Flags().IntVar(&bodyGoogleMailboxes, "google-mailboxes", 0, "Google mailboxes")
	cmd.Flags().StringVar(&bodyGoogleNotes, "google-notes", "", "Google notes")
	cmd.Flags().IntVar(&bodyMsCheckcentralCheckStatus, "ms-checkcentral-check-status", 0, "Ms checkcentral check status")
	cmd.Flags().BoolVar(&bodyMsEnabled, "ms-enabled", false, "Ms enabled")
	cmd.Flags().StringVar(&bodyMsLastBackupAt, "ms-last-backup-at", "", "Ms last backup at")
	cmd.Flags().IntVar(&bodyMsMailboxes, "ms-mailboxes", 0, "Ms mailboxes")
	cmd.Flags().StringVar(&bodyMsNotes, "ms-notes", "", "Ms notes")
	cmd.Flags().BoolVar(&stdinBody, "stdin", false, "Read request body as JSON from stdin")

	return cmd
}
