// Copyright 2026 Damien Stevens and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newDocumentsSectionsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "sections",
		Short:       "List, get, delete, and upload sections for documents",
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newDocumentsSectionsDeleteCmd(flags))
	cmd.AddCommand(newDocumentsSectionsDetailsCmd(flags))
	cmd.AddCommand(newDocumentsSectionsInfoCmd(flags))
	cmd.AddCommand(newDocumentsSectionsListCmd(flags))
	cmd.AddCommand(newDocumentsSectionsUploadCmd(flags))
	cmd.AddCommand(newDocumentsSectionsUploadWithUploadCmd(flags))
	return cmd
}
