// Copyright 2026 Damien Stevens and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newPublicSearchCatalogItemsCmd(flags *rootFlags) *cobra.Command {
	var flagPage string
	var flagPerPage float64
	var flagQuery string
	var flagOrderBy string
	var flagTypes string
	var flagBillingTypes string
	var flagExcludeUuids string
	var flagCategoryId string
	var flagNoCategory bool
	var flagAll bool

	cmd := &cobra.Command{
		Use:         "search-catalog-items",
		Short:       "This method searches for items in your [product catalog](https://support.pandadoc.",
		Example:     "  pandadoc-cli public search-catalog-items",
		Annotations: map[string]string{"pp:endpoint": "public.search-catalog-items", "pp:method": "GET", "pp:path": "/public/v2/product-catalog/items/search", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if cmd.Flags().Changed("order-by") {
				allowedOrderBy := []string{"sku", "-sku", "title", "-title", "price", "-price", "date_modified", "-date_modified"}
				validOrderBy := false
				for _, v := range allowedOrderBy {
					if flagOrderBy == v {
						validOrderBy = true
						break
					}
				}
				if !validOrderBy {
					return fmt.Errorf("invalid value %q for --%s: must be one of %v", flagOrderBy, "order-by", allowedOrderBy)
				}
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/public/v2/product-catalog/items/search"
			data, prov, err := resolvePaginatedReadWithStrategy(cmd.Context(), c, flags, "auto", "public", path, map[string]string{
				"page":          formatCLIParamValue(flagPage),
				"per_page":      formatCLIParamValue(flagPerPage),
				"query":         formatCLIParamValue(flagQuery),
				"order_by":      formatCLIParamValue(flagOrderBy),
				"types":         formatCLIParamValue(flagTypes),
				"billing_types": formatCLIParamValue(flagBillingTypes),
				"exclude_uuids": formatCLIParamValue(flagExcludeUuids),
				"category_id":   formatCLIParamValue(flagCategoryId),
				"no_category":   formatCLIParamValue(flagNoCategory),
			}, nil, flagAll, "page", "page", "per_page", "", "", cmd.ErrOrStderr())
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Print provenance to stderr for human-facing output only.
			// Machine-format flags (--json, --csv, --compact, --quiet, --plain,
			// --select) and piped stdout suppress this line; the JSON envelope
			// already carries meta.source for those consumers.
			// SYNC: keep this gate aligned with command_promoted.go.tmpl.
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var countItems []json.RawMessage
				_ = json.Unmarshal(data, &countItems)
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope before passing through flags.
			// --select wins over --compact when both are set; --compact only runs when
			// no explicit fields were requested. Explicit format flags (--csv, --quiet,
			// --plain) opt out of the auto-JSON path so piped consumers that asked for
			// a non-JSON format reach the standard pipeline below.
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			// For all other output modes (table, csv, plain, quiet), use the standard pipeline
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&flagPage, "page", "", "Page number.")
	cmd.Flags().Float64Var(&flagPerPage, "per-page", 0.0, "Items per page.")
	cmd.Flags().StringVar(&flagQuery, "query", "", "Search query. Searches the following fields: Title, SKU, description, category name, custom fields name and value.")
	cmd.Flags().StringVar(&flagOrderBy, "order-by", "", "Ordering principle for displaying search results. (one of: sku, -sku, title, -title, price, -price, date_modified, -date_modified)")
	cmd.Flags().StringVar(&flagTypes, "types", "", "Filter by catalog item types.")
	cmd.Flags().StringVar(&flagBillingTypes, "billing-types", "", "Filter by billing types.")
	cmd.Flags().StringVar(&flagExcludeUuids, "exclude-uuids", "", "A list of item uuids to be excluded from search.")
	cmd.Flags().StringVar(&flagCategoryId, "category-id", "", "Category id.")
	cmd.Flags().BoolVar(&flagNoCategory, "no-category", false, "No category")
	cmd.Flags().BoolVar(&flagAll, "all", false, "Fetch all pages")

	return cmd
}
