// Copyright 2026 Damien Stevens and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newWorkspacesCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "workspaces",
		Short:       "Get and create workspaces",
		Hidden:      true,
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newWorkspacesCreateCmd(flags))
	cmd.AddCommand(newWorkspacesGetListCmd(flags))
	cmd.AddCommand(newWorkspacesApiKeysCmd(flags))
	cmd.AddCommand(newWorkspacesDeactivateCmd(flags))
	cmd.AddCommand(newWorkspacesMembersCmd(flags))
	return cmd
}
