// Copyright 2026 Damien Stevens and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newAgentsPromotedCmd(flags *rootFlags) *cobra.Command {
	var flagAccountId string
	var flagId string
	var flagHostname string
	var flagIp string
	var flagCreated string
	var flagOs string
	var flagVersion string
	var flagConnectivity string
	var flagPage string
	var flagPageSize int
	var flagSort string

	cmd := &cobra.Command{
		Use:         "agents",
		Short:       "List agents (devices) with inventory and connectivity filters",
		Long:        "List agents (devices) with inventory and connectivity filters",
		Example:     "  rocketcyber-cli agents",
		Annotations: map[string]string{"pp:endpoint": "agents.list", "pp:method": "GET", "pp:path": "/agents", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if cmd.Flags().Changed("connectivity") {
				allowedConnectivity := []string{"online", "offline", "isolated"}
				validConnectivity := false
				for _, v := range allowedConnectivity {
					if flagConnectivity == v {
						validConnectivity = true
						break
					}
				}
				if !validConnectivity {
					return fmt.Errorf("invalid value %q for --%s: must be one of %v", flagConnectivity, "connectivity", allowedConnectivity)
				}
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/agents"
			params := map[string]string{}
			if flagAccountId != "" {
				params["accountId"] = formatCLIParamValue(flagAccountId)
			}
			if flagId != "" {
				params["id"] = formatCLIParamValue(flagId)
			}
			if flagHostname != "" {
				params["hostname"] = formatCLIParamValue(flagHostname)
			}
			if flagIp != "" {
				params["ip"] = formatCLIParamValue(flagIp)
			}
			if flagCreated != "" {
				params["created"] = formatCLIParamValue(flagCreated)
			}
			if flagOs != "" {
				params["os"] = formatCLIParamValue(flagOs)
			}
			if flagVersion != "" {
				params["version"] = formatCLIParamValue(flagVersion)
			}
			if flagConnectivity != "" {
				params["connectivity"] = formatCLIParamValue(flagConnectivity)
			}
			if flagPage != "" {
				params["page"] = formatCLIParamValue(flagPage)
			}
			if flagPageSize != 0 {
				params["pageSize"] = formatCLIParamValue(flagPageSize)
			}
			if flagSort != "" {
				params["sort"] = formatCLIParamValue(flagSort)
			}
			data, prov, err := resolveReadWithStrategy(cmd.Context(), c, flags, "auto", "agents", true, path, params, nil, cmd.ErrOrStderr())
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Print provenance to stderr for human-facing output only.
			// Machine-format flags (--json, --csv, --compact, --quiet, --plain,
			// --select) and piped stdout suppress this line; the JSON envelope
			// already carries meta.source for those consumers.
			// SYNC: keep this gate aligned with command_endpoint.go.tmpl.
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var countItems []json.RawMessage
				if json.Unmarshal(data, &countItems) != nil {
					// Single object, not an array
					countItems = []json.RawMessage{data}
				}
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope. --select wins over
			// --compact when both are set; --compact only runs when no explicit
			// fields were requested. Explicit format flags (--csv, --quiet, --plain)
			// opt out of the auto-JSON path so piped consumers that asked for a
			// non-JSON format reach the standard pipeline below.
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&flagAccountId, "account-id", "", "Filter to a single client account ID")
	cmd.Flags().StringVar(&flagId, "id", "", "Agent ID")
	cmd.Flags().StringVar(&flagHostname, "hostname", "", "Filter by device hostname")
	cmd.Flags().StringVar(&flagIp, "ip", "", "Filter by IPv4 address")
	cmd.Flags().StringVar(&flagCreated, "created", "", "Created-date range as start|end (pipe-separated ISO dates, either side optional)")
	cmd.Flags().StringVar(&flagOs, "os", "", "Filter by operating system platform (e.g. Microsoft, Apple, Linux)")
	cmd.Flags().StringVar(&flagVersion, "version", "", "Filter by OS version")
	cmd.Flags().StringVar(&flagConnectivity, "connectivity", "", "Filter by agent connectivity state (one of: online, offline, isolated)")
	cmd.Flags().StringVar(&flagPage, "page", "", "Page number to fetch")
	cmd.Flags().IntVar(&flagPageSize, "page-size", 0, "Results per page")
	cmd.Flags().StringVar(&flagSort, "sort", "", "Sort as field:direction (e.g. hostname:asc)")

	// Wire sibling endpoints and sub-resources as subcommands
	cmd.AddCommand(newNovelAgentsStaleCmd(flags))

	return cmd
}
