// Copyright 2026 Damien Stevens and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"os"

	"github.com/spf13/cobra"
)

func newCompanyPostCompaniesByParentIdGroupsCmd(flags *rootFlags) *cobra.Command {
	var bodyInfo string
	var bodyAllContactsFlag bool
	var bodyCompanyInfo string
	var bodyCompanyId string
	var bodyCompanyIdentifier string
	var bodyCompanyName string
	var bodyContactIds string
	var bodyDefaultContactFlag bool
	var bodyGroupInfo string
	var bodyGroupId string
	var bodyGroupName string
	var bodyId string
	var bodyRemoveAllContactsFlag bool
	var bodyUnsubscribeFlag bool
	var stdinBody bool

	cmd := &cobra.Command{
		Use:         "post-companies-by-parent-id-groups <parentId>",
		Short:       "Post CompanyGroup",
		Example:     "  connectwise-manage-cli company post-companies-by-parent-id-groups 42",
		Annotations: map[string]string{"pp:endpoint": "company.post-companies-by-parent-id-groups", "pp:method": "POST", "pp:path": "/company/companies/{parentId}/groups"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) == 0 {
				return cmd.Help()
			}
			if !stdinBody {
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/company/companies/{parentId}/groups"
			path = replacePathParam(path, "parentId", args[0])
			params := map[string]string{}
			var body map[string]any
			if stdinBody {
				stdinData, err := io.ReadAll(os.Stdin)
				if err != nil {
					return fmt.Errorf("reading stdin: %w", err)
				}
				var jsonBody map[string]any
				if err := json.Unmarshal(stdinData, &jsonBody); err != nil {
					return fmt.Errorf("parsing stdin JSON: %w", err)
				}
				body = jsonBody
			} else {
				body = map[string]any{}
				if bodyInfo != "" {
					var parsedInfo any
					if err := json.Unmarshal([]byte(bodyInfo), &parsedInfo); err != nil {
						return fmt.Errorf("parsing --info JSON: %w", err)
					}
					body["_info"] = parsedInfo
				}
				if cmd.Flags().Changed("all-contacts-flag") {
					body["allContactsFlag"] = bodyAllContactsFlag
				}
				{
					nestedCompany := map[string]any{}
					if bodyCompanyInfo != "" {
						var parsedCompanyInfo any
						if err := json.Unmarshal([]byte(bodyCompanyInfo), &parsedCompanyInfo); err != nil {
							return fmt.Errorf("parsing --company-info JSON: %w", err)
						}
						nestedCompany["_info"] = parsedCompanyInfo
					}
					if bodyCompanyId != "" {
						nestedCompany["id"] = bodyCompanyId
					}
					if bodyCompanyIdentifier != "" {
						nestedCompany["identifier"] = bodyCompanyIdentifier
					}
					if bodyCompanyName != "" {
						nestedCompany["name"] = bodyCompanyName
					}
					if len(nestedCompany) > 0 {
						body["company"] = nestedCompany
					}
				}
				if bodyContactIds != "" {
					var parsedContactIds any
					if err := json.Unmarshal([]byte(bodyContactIds), &parsedContactIds); err != nil {
						return fmt.Errorf("parsing --contact-ids JSON: %w", err)
					}
					body["contactIds"] = parsedContactIds
				}
				if cmd.Flags().Changed("default-contact-flag") {
					body["defaultContactFlag"] = bodyDefaultContactFlag
				}
				{
					nestedGroup := map[string]any{}
					if bodyGroupInfo != "" {
						var parsedGroupInfo any
						if err := json.Unmarshal([]byte(bodyGroupInfo), &parsedGroupInfo); err != nil {
							return fmt.Errorf("parsing --group-info JSON: %w", err)
						}
						nestedGroup["_info"] = parsedGroupInfo
					}
					if bodyGroupId != "" {
						nestedGroup["id"] = bodyGroupId
					}
					if bodyGroupName != "" {
						nestedGroup["name"] = bodyGroupName
					}
					if len(nestedGroup) > 0 {
						body["group"] = nestedGroup
					}
				}
				if bodyId != "" {
					body["id"] = bodyId
				}
				if cmd.Flags().Changed("remove-all-contacts-flag") {
					body["removeAllContactsFlag"] = bodyRemoveAllContactsFlag
				}
				if cmd.Flags().Changed("unsubscribe-flag") {
					body["unsubscribeFlag"] = bodyUnsubscribeFlag
				}
			}
			data, statusCode, err := c.PostWithParams(cmd.Context(), path, params, body)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Inspect the mutate response body for a partial-failure-shaped
			// field (e.g. Google Ads `partialFailureError`). Several Google
			// APIs return 200 OK with a partial-failure field when some
			// operations in the batch failed; ignoring it silently swallows
			// real failures. Detection runs before output-mode selection so
			// the exit code is consistent regardless of how stdout is
			// rendered. --dry-run short-circuits because no real request
			// was sent.
			var partialFailure *partialFailureReport
			if !flags.dryRun && statusCode >= 200 && statusCode < 300 {
				partialFailure = detectPartialFailure(data)
				if partialFailure != nil {
					fmt.Fprintf(os.Stderr, "warning: partial failure detected in %s response: %s\n", "company", partialFailure.Message)
					if len(partialFailure.ResourceNames) > 0 {
						fmt.Fprintf(os.Stderr, "         succeeded: %d operation(s)\n", len(partialFailure.ResourceNames))
					}
				}
			}
			if !flags.dryRun && statusCode >= 200 && statusCode < 300 && (partialFailure == nil || flags.allowPartialFailure) {
				writeMutationResponseToStore(cmd.Context(), "company", data, "contactIds")
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				// Check if response contains an array (directly or wrapped in "data")
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
					} else {
						if partialFailure != nil && !flags.allowPartialFailure {
							return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "company", partialFailure.Message))
						}
						return nil
					}
				} else {
					var wrapped struct {
						Data []map[string]any `json:"data"`
					}
					if json.Unmarshal(data, &wrapped) == nil && len(wrapped.Data) > 0 {
						if err := printAutoTable(cmd.OutOrStdout(), wrapped.Data); err != nil {
							fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
						} else {
							if partialFailure != nil && !flags.allowPartialFailure {
								return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "company", partialFailure.Message))
							}
							return nil
						}
					}
				}
			}
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				if flags.quiet {
					if partialFailure != nil && !flags.allowPartialFailure {
						return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "company", partialFailure.Message))
					}
					return nil
				}
				envelope := map[string]any{
					"action":   "post",
					"resource": "company",
					"path":     path,
					"status":   statusCode,
					"success":  statusCode >= 200 && statusCode < 300 && (partialFailure == nil || flags.allowPartialFailure),
				}
				if partialFailure != nil {
					envelope["partial_failure"] = partialFailure
				}
				if flags.dryRun {
					envelope["dry_run"] = true
					envelope["status"] = 0
					envelope["success"] = false
				}
				// Verify-mode synthetic envelope detection runs against RAW data
				// (before --compact/--select filtering) so the sentinel field is
				// guaranteed to be visible even if the operator passes a filter
				// flag that would otherwise strip it. Surfaces a top-level
				// verify_noop signal + flips success to false. Mirrors the dry_run
				// shape above.
				if len(data) > 0 {
					var rawParsed any
					if err := json.Unmarshal(data, &rawParsed); err == nil {
						if m, ok := rawParsed.(map[string]any); ok {
							if v, ok := m["__pp_verify_synthetic__"].(bool); ok && v {
								envelope["verify_noop"] = true
								envelope["success"] = false
							}
						}
					}
				}
				// Apply --compact and --select to the API response before wrapping.
				// --select wins when both are set: explicit field choice trumps the
				// generic high-gravity allow-list. Otherwise --compact still applies
				// when --agent is on but the user did not name fields.
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				if len(filtered) > 0 {
					var parsed any
					if err := json.Unmarshal(filtered, &parsed); err == nil {
						envelope["data"] = parsed
					}
				}
				envelopeJSON, err := json.Marshal(envelope)
				if err != nil {
					return err
				}
				if perr := printOutput(cmd.OutOrStdout(), json.RawMessage(envelopeJSON), true); perr != nil {
					return perr
				}
				if partialFailure != nil && !flags.allowPartialFailure {
					return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "company", partialFailure.Message))
				}
				return nil
			}
			// Fall-through for mutate paths that did not hit the table or
			// asJSON branches: --quiet, --csv, --plain, and default terminal
			// raw output. printOutputWithFlags renders the body, then the
			// typed partial-failure exit fires unless --allow-partial-failure
			// downgrades it. Without this guard a partial failure would exit
			// 0 for these output modes — the exact silent-swallow regression
			// the surrounding patch is preventing for asJSON / piped output.
			if perr := printOutputWithFlags(cmd.OutOrStdout(), data, flags); perr != nil {
				return perr
			}
			if partialFailure != nil && !flags.allowPartialFailure {
				return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "company", partialFailure.Message))
			}
			return nil
		},
	}
	cmd.Flags().StringVar(&bodyInfo, "info", "", "Info")
	cmd.Flags().BoolVar(&bodyAllContactsFlag, "all-contacts-flag", false, "All contacts flag")
	cmd.Flags().StringVar(&bodyCompanyInfo, "company-info", "", "Info")
	cmd.Flags().StringVar(&bodyCompanyId, "company-id", "", "Id")
	cmd.Flags().StringVar(&bodyCompanyIdentifier, "company-identifier", "", "Identifier")
	cmd.Flags().StringVar(&bodyCompanyName, "company-name", "", "Name")
	cmd.Flags().StringVar(&bodyContactIds, "contact-ids", "", "Contact ids")
	cmd.Flags().BoolVar(&bodyDefaultContactFlag, "default-contact-flag", false, "Default contact flag")
	cmd.Flags().StringVar(&bodyGroupInfo, "group-info", "", "Info")
	cmd.Flags().StringVar(&bodyGroupId, "group-id", "", "Id")
	cmd.Flags().StringVar(&bodyGroupName, "group-name", "", "Name")
	cmd.Flags().StringVar(&bodyId, "id", "", "Required On Updates;")
	cmd.Flags().BoolVar(&bodyRemoveAllContactsFlag, "remove-all-contacts-flag", false, "Remove all contacts flag")
	cmd.Flags().BoolVar(&bodyUnsubscribeFlag, "unsubscribe-flag", false, "Unsubscribe flag")
	cmd.Flags().BoolVar(&stdinBody, "stdin", false, "Read request body as JSON from stdin")

	return cmd
}
