// Copyright 2026 Damien Stevens and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"os"

	"github.com/spf13/cobra"
)

func newProcurementPostPurchaseordersCmd(flags *rootFlags) *cobra.Command {
	var bodyInfo string
	var bodyBusinessUnitInfo string
	var bodyBusinessUnitId string
	var bodyBusinessUnitName string
	var bodyBusinessUnitId2 string
	var bodyCancelReason string
	var bodyClosedBy string
	var bodyClosedFlag bool
	var bodyCurrencyInfo string
	var bodyCurrencyCurrencyCode string
	var bodyCurrencyCurrencyIdentifier string
	var bodyCurrencyDecimalSeparator string
	var bodyCurrencyDisplayIdFlag bool
	var bodyCurrencyDisplaySymbolFlag bool
	var bodyCurrencyId string
	var bodyCurrencyName string
	var bodyCurrencyNegativeParenthesesFlag bool
	var bodyCurrencyNumberOfDecimals int
	var bodyCurrencyRightAlign bool
	var bodyCurrencySymbol string
	var bodyCurrencyThousandsSeparator string
	var bodyCustomFields string
	var bodyCustomerCity string
	var bodyCustomerCompanyInfo string
	var bodyCustomerCompanyId string
	var bodyCustomerCompanyIdentifier string
	var bodyCustomerCompanyName string
	var bodyCustomerContactInfo string
	var bodyCustomerContactId string
	var bodyCustomerContactName string
	var bodyCustomerCountryInfo string
	var bodyCustomerCountryId string
	var bodyCustomerCountryIdentifier string
	var bodyCustomerCountryName string
	var bodyCustomerExtension string
	var bodyCustomerName string
	var bodyCustomerPhone string
	var bodyCustomerSiteInfo string
	var bodyCustomerSiteId string
	var bodyCustomerSiteName string
	var bodyCustomerSiteName2 string
	var bodyCustomerState string
	var bodyCustomerStreetLine1 string
	var bodyCustomerStreetLine2 string
	var bodyCustomerZip string
	var bodyDateClosed string
	var bodyDropShipCustomerFlag bool
	var bodyEnteredBy string
	var bodyFreightCost float64
	var bodyFreightPackingSlip string
	var bodyFreightTaxTotal float64
	var bodyId string
	var bodyInternalNotes string
	var bodyLocationInfo string
	var bodyLocationId string
	var bodyLocationName string
	var bodyLocationId2 string
	var bodyPoDate string
	var bodyPoNumber string
	var bodySalesTax float64
	var bodyShipmentDate string
	var bodyShipmentMethodInfo string
	var bodyShipmentMethodId string
	var bodyShipmentMethodName string
	var bodyShippingInstructions string
	var bodyStatusInfo string
	var bodyStatusId string
	var bodyStatusName string
	var bodySubTotal float64
	var bodyTaxCodeInfo string
	var bodyTaxCodeId string
	var bodyTaxCodeName string
	var bodyTaxFreightFlag bool
	var bodyTaxPoFlag bool
	var bodyTermsInfo string
	var bodyTermsId string
	var bodyTermsName string
	var bodyTotal float64
	var bodyTrackingNumber string
	var bodyUpdateShipmentInfo bool
	var bodyUpdateVendorOrderNumber bool
	var bodyVendorCompanyInfo string
	var bodyVendorCompanyId string
	var bodyVendorCompanyIdentifier string
	var bodyVendorCompanyName string
	var bodyVendorContactInfo string
	var bodyVendorContactId string
	var bodyVendorContactName string
	var bodyVendorInvoiceDate string
	var bodyVendorInvoiceNumber string
	var bodyVendorOrderNumber string
	var bodyVendorSiteInfo string
	var bodyVendorSiteId string
	var bodyVendorSiteName string
	var bodyWarehouseInfo string
	var bodyWarehouseId string
	var bodyWarehouseLockedFlag bool
	var bodyWarehouseName string
	var bodyWarehouseContactInfo string
	var bodyWarehouseContactId string
	var bodyWarehouseContactName string
	var stdinBody bool

	cmd := &cobra.Command{
		Use:         "post-purchaseorders",
		Short:       "Post PurchaseOrder",
		Example:     "  connectwise-manage-cli procurement post-purchaseorders",
		Annotations: map[string]string{"pp:endpoint": "procurement.post-purchaseorders", "pp:method": "POST", "pp:path": "/procurement/purchaseorders"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if !stdinBody {
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/procurement/purchaseorders"
			params := map[string]string{}
			var body map[string]any
			if stdinBody {
				stdinData, err := io.ReadAll(os.Stdin)
				if err != nil {
					return fmt.Errorf("reading stdin: %w", err)
				}
				var jsonBody map[string]any
				if err := json.Unmarshal(stdinData, &jsonBody); err != nil {
					return fmt.Errorf("parsing stdin JSON: %w", err)
				}
				body = jsonBody
			} else {
				body = map[string]any{}
				if bodyInfo != "" {
					var parsedInfo any
					if err := json.Unmarshal([]byte(bodyInfo), &parsedInfo); err != nil {
						return fmt.Errorf("parsing --info JSON: %w", err)
					}
					body["_info"] = parsedInfo
				}
				{
					nestedBusinessUnit := map[string]any{}
					if bodyBusinessUnitInfo != "" {
						var parsedBusinessUnitInfo any
						if err := json.Unmarshal([]byte(bodyBusinessUnitInfo), &parsedBusinessUnitInfo); err != nil {
							return fmt.Errorf("parsing --business-unit-info JSON: %w", err)
						}
						nestedBusinessUnit["_info"] = parsedBusinessUnitInfo
					}
					if bodyBusinessUnitId != "" {
						nestedBusinessUnit["id"] = bodyBusinessUnitId
					}
					if bodyBusinessUnitName != "" {
						nestedBusinessUnit["name"] = bodyBusinessUnitName
					}
					if len(nestedBusinessUnit) > 0 {
						body["businessUnit"] = nestedBusinessUnit
					}
				}
				if bodyBusinessUnitId2 != "" {
					body["businessUnitId"] = bodyBusinessUnitId2
				}
				if bodyCancelReason != "" {
					body["cancelReason"] = bodyCancelReason
				}
				if bodyClosedBy != "" {
					body["closedBy"] = bodyClosedBy
				}
				if cmd.Flags().Changed("closed-flag") {
					body["closedFlag"] = bodyClosedFlag
				}
				{
					nestedCurrency := map[string]any{}
					if bodyCurrencyInfo != "" {
						var parsedCurrencyInfo any
						if err := json.Unmarshal([]byte(bodyCurrencyInfo), &parsedCurrencyInfo); err != nil {
							return fmt.Errorf("parsing --currency-info JSON: %w", err)
						}
						nestedCurrency["_info"] = parsedCurrencyInfo
					}
					if bodyCurrencyCurrencyCode != "" {
						nestedCurrency["currencyCode"] = bodyCurrencyCurrencyCode
					}
					if bodyCurrencyCurrencyIdentifier != "" {
						nestedCurrency["currencyIdentifier"] = bodyCurrencyCurrencyIdentifier
					}
					if bodyCurrencyDecimalSeparator != "" {
						nestedCurrency["decimalSeparator"] = bodyCurrencyDecimalSeparator
					}
					if cmd.Flags().Changed("currency-display-id-flag") {
						nestedCurrency["displayIdFlag"] = bodyCurrencyDisplayIdFlag
					}
					if cmd.Flags().Changed("currency-display-symbol-flag") {
						nestedCurrency["displaySymbolFlag"] = bodyCurrencyDisplaySymbolFlag
					}
					if bodyCurrencyId != "" {
						nestedCurrency["id"] = bodyCurrencyId
					}
					if bodyCurrencyName != "" {
						nestedCurrency["name"] = bodyCurrencyName
					}
					if cmd.Flags().Changed("currency-negative-parentheses-flag") {
						nestedCurrency["negativeParenthesesFlag"] = bodyCurrencyNegativeParenthesesFlag
					}
					if bodyCurrencyNumberOfDecimals != 0 {
						nestedCurrency["numberOfDecimals"] = bodyCurrencyNumberOfDecimals
					}
					if cmd.Flags().Changed("currency-right-align") {
						nestedCurrency["rightAlign"] = bodyCurrencyRightAlign
					}
					if bodyCurrencySymbol != "" {
						nestedCurrency["symbol"] = bodyCurrencySymbol
					}
					if bodyCurrencyThousandsSeparator != "" {
						nestedCurrency["thousandsSeparator"] = bodyCurrencyThousandsSeparator
					}
					if len(nestedCurrency) > 0 {
						body["currency"] = nestedCurrency
					}
				}
				if bodyCustomFields != "" {
					var parsedCustomFields any
					if err := json.Unmarshal([]byte(bodyCustomFields), &parsedCustomFields); err != nil {
						return fmt.Errorf("parsing --custom-fields JSON: %w", err)
					}
					body["customFields"] = parsedCustomFields
				}
				if bodyCustomerCity != "" {
					body["customerCity"] = bodyCustomerCity
				}
				{
					nestedCustomerCompany := map[string]any{}
					if bodyCustomerCompanyInfo != "" {
						var parsedCustomerCompanyInfo any
						if err := json.Unmarshal([]byte(bodyCustomerCompanyInfo), &parsedCustomerCompanyInfo); err != nil {
							return fmt.Errorf("parsing --customer-company-info JSON: %w", err)
						}
						nestedCustomerCompany["_info"] = parsedCustomerCompanyInfo
					}
					if bodyCustomerCompanyId != "" {
						nestedCustomerCompany["id"] = bodyCustomerCompanyId
					}
					if bodyCustomerCompanyIdentifier != "" {
						nestedCustomerCompany["identifier"] = bodyCustomerCompanyIdentifier
					}
					if bodyCustomerCompanyName != "" {
						nestedCustomerCompany["name"] = bodyCustomerCompanyName
					}
					if len(nestedCustomerCompany) > 0 {
						body["customerCompany"] = nestedCustomerCompany
					}
				}
				{
					nestedCustomerContact := map[string]any{}
					if bodyCustomerContactInfo != "" {
						var parsedCustomerContactInfo any
						if err := json.Unmarshal([]byte(bodyCustomerContactInfo), &parsedCustomerContactInfo); err != nil {
							return fmt.Errorf("parsing --customer-contact-info JSON: %w", err)
						}
						nestedCustomerContact["_info"] = parsedCustomerContactInfo
					}
					if bodyCustomerContactId != "" {
						nestedCustomerContact["id"] = bodyCustomerContactId
					}
					if bodyCustomerContactName != "" {
						nestedCustomerContact["name"] = bodyCustomerContactName
					}
					if len(nestedCustomerContact) > 0 {
						body["customerContact"] = nestedCustomerContact
					}
				}
				{
					nestedCustomerCountry := map[string]any{}
					if bodyCustomerCountryInfo != "" {
						var parsedCustomerCountryInfo any
						if err := json.Unmarshal([]byte(bodyCustomerCountryInfo), &parsedCustomerCountryInfo); err != nil {
							return fmt.Errorf("parsing --customer-country-info JSON: %w", err)
						}
						nestedCustomerCountry["_info"] = parsedCustomerCountryInfo
					}
					if bodyCustomerCountryId != "" {
						nestedCustomerCountry["id"] = bodyCustomerCountryId
					}
					if bodyCustomerCountryIdentifier != "" {
						nestedCustomerCountry["identifier"] = bodyCustomerCountryIdentifier
					}
					if bodyCustomerCountryName != "" {
						nestedCustomerCountry["name"] = bodyCustomerCountryName
					}
					if len(nestedCustomerCountry) > 0 {
						body["customerCountry"] = nestedCustomerCountry
					}
				}
				if bodyCustomerExtension != "" {
					body["customerExtension"] = bodyCustomerExtension
				}
				if bodyCustomerName != "" {
					body["customerName"] = bodyCustomerName
				}
				if bodyCustomerPhone != "" {
					body["customerPhone"] = bodyCustomerPhone
				}
				{
					nestedCustomerSite := map[string]any{}
					if bodyCustomerSiteInfo != "" {
						var parsedCustomerSiteInfo any
						if err := json.Unmarshal([]byte(bodyCustomerSiteInfo), &parsedCustomerSiteInfo); err != nil {
							return fmt.Errorf("parsing --customer-site-info JSON: %w", err)
						}
						nestedCustomerSite["_info"] = parsedCustomerSiteInfo
					}
					if bodyCustomerSiteId != "" {
						nestedCustomerSite["id"] = bodyCustomerSiteId
					}
					if bodyCustomerSiteName != "" {
						nestedCustomerSite["name"] = bodyCustomerSiteName
					}
					if len(nestedCustomerSite) > 0 {
						body["customerSite"] = nestedCustomerSite
					}
				}
				if bodyCustomerSiteName2 != "" {
					body["customerSiteName"] = bodyCustomerSiteName2
				}
				if bodyCustomerState != "" {
					body["customerState"] = bodyCustomerState
				}
				if bodyCustomerStreetLine1 != "" {
					body["customerStreetLine1"] = bodyCustomerStreetLine1
				}
				if bodyCustomerStreetLine2 != "" {
					body["customerStreetLine2"] = bodyCustomerStreetLine2
				}
				if bodyCustomerZip != "" {
					body["customerZip"] = bodyCustomerZip
				}
				if bodyDateClosed != "" {
					body["dateClosed"] = bodyDateClosed
				}
				if cmd.Flags().Changed("drop-ship-customer-flag") {
					body["dropShipCustomerFlag"] = bodyDropShipCustomerFlag
				}
				if bodyEnteredBy != "" {
					body["enteredBy"] = bodyEnteredBy
				}
				if bodyFreightCost != 0.0 {
					body["freightCost"] = bodyFreightCost
				}
				if bodyFreightPackingSlip != "" {
					body["freightPackingSlip"] = bodyFreightPackingSlip
				}
				if bodyFreightTaxTotal != 0.0 {
					body["freightTaxTotal"] = bodyFreightTaxTotal
				}
				if bodyId != "" {
					body["id"] = bodyId
				}
				if bodyInternalNotes != "" {
					body["internalNotes"] = bodyInternalNotes
				}
				{
					nestedLocation := map[string]any{}
					if bodyLocationInfo != "" {
						var parsedLocationInfo any
						if err := json.Unmarshal([]byte(bodyLocationInfo), &parsedLocationInfo); err != nil {
							return fmt.Errorf("parsing --location-info JSON: %w", err)
						}
						nestedLocation["_info"] = parsedLocationInfo
					}
					if bodyLocationId != "" {
						nestedLocation["id"] = bodyLocationId
					}
					if bodyLocationName != "" {
						nestedLocation["name"] = bodyLocationName
					}
					if len(nestedLocation) > 0 {
						body["location"] = nestedLocation
					}
				}
				if bodyLocationId2 != "" {
					body["locationId"] = bodyLocationId2
				}
				if bodyPoDate != "" {
					body["poDate"] = bodyPoDate
				}
				if bodyPoNumber != "" {
					body["poNumber"] = bodyPoNumber
				}
				if bodySalesTax != 0.0 {
					body["salesTax"] = bodySalesTax
				}
				if bodyShipmentDate != "" {
					body["shipmentDate"] = bodyShipmentDate
				}
				{
					nestedShipmentMethod := map[string]any{}
					if bodyShipmentMethodInfo != "" {
						var parsedShipmentMethodInfo any
						if err := json.Unmarshal([]byte(bodyShipmentMethodInfo), &parsedShipmentMethodInfo); err != nil {
							return fmt.Errorf("parsing --shipment-method-info JSON: %w", err)
						}
						nestedShipmentMethod["_info"] = parsedShipmentMethodInfo
					}
					if bodyShipmentMethodId != "" {
						nestedShipmentMethod["id"] = bodyShipmentMethodId
					}
					if bodyShipmentMethodName != "" {
						nestedShipmentMethod["name"] = bodyShipmentMethodName
					}
					if len(nestedShipmentMethod) > 0 {
						body["shipmentMethod"] = nestedShipmentMethod
					}
				}
				if bodyShippingInstructions != "" {
					body["shippingInstructions"] = bodyShippingInstructions
				}
				{
					nestedStatus := map[string]any{}
					if bodyStatusInfo != "" {
						var parsedStatusInfo any
						if err := json.Unmarshal([]byte(bodyStatusInfo), &parsedStatusInfo); err != nil {
							return fmt.Errorf("parsing --status-info JSON: %w", err)
						}
						nestedStatus["_info"] = parsedStatusInfo
					}
					if bodyStatusId != "" {
						nestedStatus["id"] = bodyStatusId
					}
					if bodyStatusName != "" {
						nestedStatus["name"] = bodyStatusName
					}
					if len(nestedStatus) > 0 {
						body["status"] = nestedStatus
					}
				}
				if bodySubTotal != 0.0 {
					body["subTotal"] = bodySubTotal
				}
				{
					nestedTaxCode := map[string]any{}
					if bodyTaxCodeInfo != "" {
						var parsedTaxCodeInfo any
						if err := json.Unmarshal([]byte(bodyTaxCodeInfo), &parsedTaxCodeInfo); err != nil {
							return fmt.Errorf("parsing --tax-code-info JSON: %w", err)
						}
						nestedTaxCode["_info"] = parsedTaxCodeInfo
					}
					if bodyTaxCodeId != "" {
						nestedTaxCode["id"] = bodyTaxCodeId
					}
					if bodyTaxCodeName != "" {
						nestedTaxCode["name"] = bodyTaxCodeName
					}
					if len(nestedTaxCode) > 0 {
						body["taxCode"] = nestedTaxCode
					}
				}
				if cmd.Flags().Changed("tax-freight-flag") {
					body["taxFreightFlag"] = bodyTaxFreightFlag
				}
				if cmd.Flags().Changed("tax-po-flag") {
					body["taxPoFlag"] = bodyTaxPoFlag
				}
				{
					nestedTerms := map[string]any{}
					if bodyTermsInfo != "" {
						var parsedTermsInfo any
						if err := json.Unmarshal([]byte(bodyTermsInfo), &parsedTermsInfo); err != nil {
							return fmt.Errorf("parsing --terms-info JSON: %w", err)
						}
						nestedTerms["_info"] = parsedTermsInfo
					}
					if bodyTermsId != "" {
						nestedTerms["id"] = bodyTermsId
					}
					if bodyTermsName != "" {
						nestedTerms["name"] = bodyTermsName
					}
					if len(nestedTerms) > 0 {
						body["terms"] = nestedTerms
					}
				}
				if bodyTotal != 0.0 {
					body["total"] = bodyTotal
				}
				if bodyTrackingNumber != "" {
					body["trackingNumber"] = bodyTrackingNumber
				}
				if cmd.Flags().Changed("update-shipment-info") {
					body["updateShipmentInfo"] = bodyUpdateShipmentInfo
				}
				if cmd.Flags().Changed("update-vendor-order-number") {
					body["updateVendorOrderNumber"] = bodyUpdateVendorOrderNumber
				}
				{
					nestedVendorCompany := map[string]any{}
					if bodyVendorCompanyInfo != "" {
						var parsedVendorCompanyInfo any
						if err := json.Unmarshal([]byte(bodyVendorCompanyInfo), &parsedVendorCompanyInfo); err != nil {
							return fmt.Errorf("parsing --vendor-company-info JSON: %w", err)
						}
						nestedVendorCompany["_info"] = parsedVendorCompanyInfo
					}
					if bodyVendorCompanyId != "" {
						nestedVendorCompany["id"] = bodyVendorCompanyId
					}
					if bodyVendorCompanyIdentifier != "" {
						nestedVendorCompany["identifier"] = bodyVendorCompanyIdentifier
					}
					if bodyVendorCompanyName != "" {
						nestedVendorCompany["name"] = bodyVendorCompanyName
					}
					if len(nestedVendorCompany) > 0 {
						body["vendorCompany"] = nestedVendorCompany
					}
				}
				{
					nestedVendorContact := map[string]any{}
					if bodyVendorContactInfo != "" {
						var parsedVendorContactInfo any
						if err := json.Unmarshal([]byte(bodyVendorContactInfo), &parsedVendorContactInfo); err != nil {
							return fmt.Errorf("parsing --vendor-contact-info JSON: %w", err)
						}
						nestedVendorContact["_info"] = parsedVendorContactInfo
					}
					if bodyVendorContactId != "" {
						nestedVendorContact["id"] = bodyVendorContactId
					}
					if bodyVendorContactName != "" {
						nestedVendorContact["name"] = bodyVendorContactName
					}
					if len(nestedVendorContact) > 0 {
						body["vendorContact"] = nestedVendorContact
					}
				}
				if bodyVendorInvoiceDate != "" {
					body["vendorInvoiceDate"] = bodyVendorInvoiceDate
				}
				if bodyVendorInvoiceNumber != "" {
					body["vendorInvoiceNumber"] = bodyVendorInvoiceNumber
				}
				if bodyVendorOrderNumber != "" {
					body["vendorOrderNumber"] = bodyVendorOrderNumber
				}
				{
					nestedVendorSite := map[string]any{}
					if bodyVendorSiteInfo != "" {
						var parsedVendorSiteInfo any
						if err := json.Unmarshal([]byte(bodyVendorSiteInfo), &parsedVendorSiteInfo); err != nil {
							return fmt.Errorf("parsing --vendor-site-info JSON: %w", err)
						}
						nestedVendorSite["_info"] = parsedVendorSiteInfo
					}
					if bodyVendorSiteId != "" {
						nestedVendorSite["id"] = bodyVendorSiteId
					}
					if bodyVendorSiteName != "" {
						nestedVendorSite["name"] = bodyVendorSiteName
					}
					if len(nestedVendorSite) > 0 {
						body["vendorSite"] = nestedVendorSite
					}
				}
				{
					nestedWarehouse := map[string]any{}
					if bodyWarehouseInfo != "" {
						var parsedWarehouseInfo any
						if err := json.Unmarshal([]byte(bodyWarehouseInfo), &parsedWarehouseInfo); err != nil {
							return fmt.Errorf("parsing --warehouse-info JSON: %w", err)
						}
						nestedWarehouse["_info"] = parsedWarehouseInfo
					}
					if bodyWarehouseId != "" {
						nestedWarehouse["id"] = bodyWarehouseId
					}
					if cmd.Flags().Changed("warehouse-locked-flag") {
						nestedWarehouse["lockedFlag"] = bodyWarehouseLockedFlag
					}
					if bodyWarehouseName != "" {
						nestedWarehouse["name"] = bodyWarehouseName
					}
					if len(nestedWarehouse) > 0 {
						body["warehouse"] = nestedWarehouse
					}
				}
				{
					nestedWarehouseContact := map[string]any{}
					if bodyWarehouseContactInfo != "" {
						var parsedWarehouseContactInfo any
						if err := json.Unmarshal([]byte(bodyWarehouseContactInfo), &parsedWarehouseContactInfo); err != nil {
							return fmt.Errorf("parsing --warehouse-contact-info JSON: %w", err)
						}
						nestedWarehouseContact["_info"] = parsedWarehouseContactInfo
					}
					if bodyWarehouseContactId != "" {
						nestedWarehouseContact["id"] = bodyWarehouseContactId
					}
					if bodyWarehouseContactName != "" {
						nestedWarehouseContact["name"] = bodyWarehouseContactName
					}
					if len(nestedWarehouseContact) > 0 {
						body["warehouseContact"] = nestedWarehouseContact
					}
				}
			}
			data, statusCode, err := c.PostWithParams(cmd.Context(), path, params, body)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Inspect the mutate response body for a partial-failure-shaped
			// field (e.g. Google Ads `partialFailureError`). Several Google
			// APIs return 200 OK with a partial-failure field when some
			// operations in the batch failed; ignoring it silently swallows
			// real failures. Detection runs before output-mode selection so
			// the exit code is consistent regardless of how stdout is
			// rendered. --dry-run short-circuits because no real request
			// was sent.
			var partialFailure *partialFailureReport
			if !flags.dryRun && statusCode >= 200 && statusCode < 300 {
				partialFailure = detectPartialFailure(data)
				if partialFailure != nil {
					fmt.Fprintf(os.Stderr, "warning: partial failure detected in %s response: %s\n", "procurement", partialFailure.Message)
					if len(partialFailure.ResourceNames) > 0 {
						fmt.Fprintf(os.Stderr, "         succeeded: %d operation(s)\n", len(partialFailure.ResourceNames))
					}
				}
			}
			if !flags.dryRun && statusCode >= 200 && statusCode < 300 && (partialFailure == nil || flags.allowPartialFailure) {
				writeMutationResponseToStore(cmd.Context(), "procurement", data, "customFields")
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				// Check if response contains an array (directly or wrapped in "data")
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
					} else {
						if partialFailure != nil && !flags.allowPartialFailure {
							return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "procurement", partialFailure.Message))
						}
						return nil
					}
				} else {
					var wrapped struct {
						Data []map[string]any `json:"data"`
					}
					if json.Unmarshal(data, &wrapped) == nil && len(wrapped.Data) > 0 {
						if err := printAutoTable(cmd.OutOrStdout(), wrapped.Data); err != nil {
							fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
						} else {
							if partialFailure != nil && !flags.allowPartialFailure {
								return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "procurement", partialFailure.Message))
							}
							return nil
						}
					}
				}
			}
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				if flags.quiet {
					if partialFailure != nil && !flags.allowPartialFailure {
						return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "procurement", partialFailure.Message))
					}
					return nil
				}
				envelope := map[string]any{
					"action":   "post",
					"resource": "procurement",
					"path":     path,
					"status":   statusCode,
					"success":  statusCode >= 200 && statusCode < 300 && (partialFailure == nil || flags.allowPartialFailure),
				}
				if partialFailure != nil {
					envelope["partial_failure"] = partialFailure
				}
				if flags.dryRun {
					envelope["dry_run"] = true
					envelope["status"] = 0
					envelope["success"] = false
				}
				// Verify-mode synthetic envelope detection runs against RAW data
				// (before --compact/--select filtering) so the sentinel field is
				// guaranteed to be visible even if the operator passes a filter
				// flag that would otherwise strip it. Surfaces a top-level
				// verify_noop signal + flips success to false. Mirrors the dry_run
				// shape above.
				if len(data) > 0 {
					var rawParsed any
					if err := json.Unmarshal(data, &rawParsed); err == nil {
						if m, ok := rawParsed.(map[string]any); ok {
							if v, ok := m["__pp_verify_synthetic__"].(bool); ok && v {
								envelope["verify_noop"] = true
								envelope["success"] = false
							}
						}
					}
				}
				// Apply --compact and --select to the API response before wrapping.
				// --select wins when both are set: explicit field choice trumps the
				// generic high-gravity allow-list. Otherwise --compact still applies
				// when --agent is on but the user did not name fields.
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				if len(filtered) > 0 {
					var parsed any
					if err := json.Unmarshal(filtered, &parsed); err == nil {
						envelope["data"] = parsed
					}
				}
				envelopeJSON, err := json.Marshal(envelope)
				if err != nil {
					return err
				}
				if perr := printOutput(cmd.OutOrStdout(), json.RawMessage(envelopeJSON), true); perr != nil {
					return perr
				}
				if partialFailure != nil && !flags.allowPartialFailure {
					return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "procurement", partialFailure.Message))
				}
				return nil
			}
			// Fall-through for mutate paths that did not hit the table or
			// asJSON branches: --quiet, --csv, --plain, and default terminal
			// raw output. printOutputWithFlags renders the body, then the
			// typed partial-failure exit fires unless --allow-partial-failure
			// downgrades it. Without this guard a partial failure would exit
			// 0 for these output modes — the exact silent-swallow regression
			// the surrounding patch is preventing for asJSON / piped output.
			if perr := printOutputWithFlags(cmd.OutOrStdout(), data, flags); perr != nil {
				return perr
			}
			if partialFailure != nil && !flags.allowPartialFailure {
				return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "procurement", partialFailure.Message))
			}
			return nil
		},
	}
	cmd.Flags().StringVar(&bodyInfo, "info", "", "Info")
	cmd.Flags().StringVar(&bodyBusinessUnitInfo, "business-unit-info", "", "Info")
	cmd.Flags().StringVar(&bodyBusinessUnitId, "business-unit-id", "", "Id")
	cmd.Flags().StringVar(&bodyBusinessUnitName, "business-unit-name", "", "Name")
	cmd.Flags().StringVar(&bodyBusinessUnitId2, "business-unit-id-2", "", "Business unit id")
	cmd.Flags().StringVar(&bodyCancelReason, "cancel-reason", "", "Cancel reason")
	cmd.Flags().StringVar(&bodyClosedBy, "closed-by", "", "Closed by")
	cmd.Flags().BoolVar(&bodyClosedFlag, "closed-flag", false, "The closed flag can only be updated via updating the purchase order status to a closed/open status.")
	cmd.Flags().StringVar(&bodyCurrencyInfo, "currency-info", "", "Info")
	cmd.Flags().StringVar(&bodyCurrencyCurrencyCode, "currency-currency-code", "", "Currency code")
	cmd.Flags().StringVar(&bodyCurrencyCurrencyIdentifier, "currency-currency-identifier", "", "Currency identifier")
	cmd.Flags().StringVar(&bodyCurrencyDecimalSeparator, "currency-decimal-separator", "", "Decimal separator")
	cmd.Flags().BoolVar(&bodyCurrencyDisplayIdFlag, "currency-display-id-flag", false, "Display id flag")
	cmd.Flags().BoolVar(&bodyCurrencyDisplaySymbolFlag, "currency-display-symbol-flag", false, "Display symbol flag")
	cmd.Flags().StringVar(&bodyCurrencyId, "currency-id", "", "Id")
	cmd.Flags().StringVar(&bodyCurrencyName, "currency-name", "", "Name")
	cmd.Flags().BoolVar(&bodyCurrencyNegativeParenthesesFlag, "currency-negative-parentheses-flag", false, "Negative parentheses flag")
	cmd.Flags().IntVar(&bodyCurrencyNumberOfDecimals, "currency-number-of-decimals", 0, "Number of decimals")
	cmd.Flags().BoolVar(&bodyCurrencyRightAlign, "currency-right-align", false, "Right align")
	cmd.Flags().StringVar(&bodyCurrencySymbol, "currency-symbol", "", "Symbol")
	cmd.Flags().StringVar(&bodyCurrencyThousandsSeparator, "currency-thousands-separator", "", "Thousands separator")
	cmd.Flags().StringVar(&bodyCustomFields, "custom-fields", "", "Custom fields")
	cmd.Flags().StringVar(&bodyCustomerCity, "customer-city", "", "Customer city")
	cmd.Flags().StringVar(&bodyCustomerCompanyInfo, "customer-company-info", "", "Info")
	cmd.Flags().StringVar(&bodyCustomerCompanyId, "customer-company-id", "", "Id")
	cmd.Flags().StringVar(&bodyCustomerCompanyIdentifier, "customer-company-identifier", "", "Identifier")
	cmd.Flags().StringVar(&bodyCustomerCompanyName, "customer-company-name", "", "Name")
	cmd.Flags().StringVar(&bodyCustomerContactInfo, "customer-contact-info", "", "Info")
	cmd.Flags().StringVar(&bodyCustomerContactId, "customer-contact-id", "", "Id")
	cmd.Flags().StringVar(&bodyCustomerContactName, "customer-contact-name", "", "Name")
	cmd.Flags().StringVar(&bodyCustomerCountryInfo, "customer-country-info", "", "Info")
	cmd.Flags().StringVar(&bodyCustomerCountryId, "customer-country-id", "", "Id")
	cmd.Flags().StringVar(&bodyCustomerCountryIdentifier, "customer-country-identifier", "", "Identifier")
	cmd.Flags().StringVar(&bodyCustomerCountryName, "customer-country-name", "", "Name")
	cmd.Flags().StringVar(&bodyCustomerExtension, "customer-extension", "", "Customer extension")
	cmd.Flags().StringVar(&bodyCustomerName, "customer-name", "", "Customer name")
	cmd.Flags().StringVar(&bodyCustomerPhone, "customer-phone", "", "Customer phone")
	cmd.Flags().StringVar(&bodyCustomerSiteInfo, "customer-site-info", "", "Info")
	cmd.Flags().StringVar(&bodyCustomerSiteId, "customer-site-id", "", "Id")
	cmd.Flags().StringVar(&bodyCustomerSiteName, "customer-site-name", "", "Name")
	cmd.Flags().StringVar(&bodyCustomerSiteName2, "customer-site-name-2", "", "Customer site name")
	cmd.Flags().StringVar(&bodyCustomerState, "customer-state", "", "Customer state")
	cmd.Flags().StringVar(&bodyCustomerStreetLine1, "customer-street-line1", "", "Customer street line1")
	cmd.Flags().StringVar(&bodyCustomerStreetLine2, "customer-street-line2", "", "Customer street line2")
	cmd.Flags().StringVar(&bodyCustomerZip, "customer-zip", "", "Customer zip")
	cmd.Flags().StringVar(&bodyDateClosed, "date-closed", "", "Date closed")
	cmd.Flags().BoolVar(&bodyDropShipCustomerFlag, "drop-ship-customer-flag", false, "Drop ship customer flag")
	cmd.Flags().StringVar(&bodyEnteredBy, "entered-by", "", "Entered by")
	cmd.Flags().Float64Var(&bodyFreightCost, "freight-cost", 0.0, "Freight cost")
	cmd.Flags().StringVar(&bodyFreightPackingSlip, "freight-packing-slip", "", "Freight packing slip")
	cmd.Flags().Float64Var(&bodyFreightTaxTotal, "freight-tax-total", 0.0, "Freight tax total")
	cmd.Flags().StringVar(&bodyId, "id", "", "Id")
	cmd.Flags().StringVar(&bodyInternalNotes, "internal-notes", "", "Internal notes")
	cmd.Flags().StringVar(&bodyLocationInfo, "location-info", "", "Info")
	cmd.Flags().StringVar(&bodyLocationId, "location-id", "", "Id")
	cmd.Flags().StringVar(&bodyLocationName, "location-name", "", "Name")
	cmd.Flags().StringVar(&bodyLocationId2, "location-id-2", "", "Location id")
	cmd.Flags().StringVar(&bodyPoDate, "po-date", "", "Required On Updates;")
	cmd.Flags().StringVar(&bodyPoNumber, "po-number", "", "Required On Updates; Max length: 50;")
	cmd.Flags().Float64Var(&bodySalesTax, "sales-tax", 0.0, "Sales tax")
	cmd.Flags().StringVar(&bodyShipmentDate, "shipment-date", "", "Shipment date")
	cmd.Flags().StringVar(&bodyShipmentMethodInfo, "shipment-method-info", "", "Info")
	cmd.Flags().StringVar(&bodyShipmentMethodId, "shipment-method-id", "", "Id")
	cmd.Flags().StringVar(&bodyShipmentMethodName, "shipment-method-name", "", "Name")
	cmd.Flags().StringVar(&bodyShippingInstructions, "shipping-instructions", "", "Shipping instructions")
	cmd.Flags().StringVar(&bodyStatusInfo, "status-info", "", "Info")
	cmd.Flags().StringVar(&bodyStatusId, "status-id", "", "Id")
	cmd.Flags().StringVar(&bodyStatusName, "status-name", "", "Name")
	cmd.Flags().Float64Var(&bodySubTotal, "sub-total", 0.0, "Sub total")
	cmd.Flags().StringVar(&bodyTaxCodeInfo, "tax-code-info", "", "Info")
	cmd.Flags().StringVar(&bodyTaxCodeId, "tax-code-id", "", "Id")
	cmd.Flags().StringVar(&bodyTaxCodeName, "tax-code-name", "", "Name")
	cmd.Flags().BoolVar(&bodyTaxFreightFlag, "tax-freight-flag", false, "Tax freight flag")
	cmd.Flags().BoolVar(&bodyTaxPoFlag, "tax-po-flag", false, "Tax po flag")
	cmd.Flags().StringVar(&bodyTermsInfo, "terms-info", "", "Info")
	cmd.Flags().StringVar(&bodyTermsId, "terms-id", "", "Id")
	cmd.Flags().StringVar(&bodyTermsName, "terms-name", "", "Name")
	cmd.Flags().Float64Var(&bodyTotal, "total", 0.0, "Total")
	cmd.Flags().StringVar(&bodyTrackingNumber, "tracking-number", "", "Max length: 50;")
	cmd.Flags().BoolVar(&bodyUpdateShipmentInfo, "update-shipment-info", false, "Determines whether or not to update all of the shipment info for each associated line item when new shipment info is")
	cmd.Flags().BoolVar(&bodyUpdateVendorOrderNumber, "update-vendor-order-number", false, "Determines whether or not to update vendor order number for each associated line item when new vendor order number is")
	cmd.Flags().StringVar(&bodyVendorCompanyInfo, "vendor-company-info", "", "Info")
	cmd.Flags().StringVar(&bodyVendorCompanyId, "vendor-company-id", "", "Id")
	cmd.Flags().StringVar(&bodyVendorCompanyIdentifier, "vendor-company-identifier", "", "Identifier")
	cmd.Flags().StringVar(&bodyVendorCompanyName, "vendor-company-name", "", "Name")
	cmd.Flags().StringVar(&bodyVendorContactInfo, "vendor-contact-info", "", "Info")
	cmd.Flags().StringVar(&bodyVendorContactId, "vendor-contact-id", "", "Id")
	cmd.Flags().StringVar(&bodyVendorContactName, "vendor-contact-name", "", "Name")
	cmd.Flags().StringVar(&bodyVendorInvoiceDate, "vendor-invoice-date", "", "Vendor invoice date")
	cmd.Flags().StringVar(&bodyVendorInvoiceNumber, "vendor-invoice-number", "", "Max length: 50;")
	cmd.Flags().StringVar(&bodyVendorOrderNumber, "vendor-order-number", "", "Max length: 50;")
	cmd.Flags().StringVar(&bodyVendorSiteInfo, "vendor-site-info", "", "Info")
	cmd.Flags().StringVar(&bodyVendorSiteId, "vendor-site-id", "", "Id")
	cmd.Flags().StringVar(&bodyVendorSiteName, "vendor-site-name", "", "Name")
	cmd.Flags().StringVar(&bodyWarehouseInfo, "warehouse-info", "", "Info")
	cmd.Flags().StringVar(&bodyWarehouseId, "warehouse-id", "", "Id")
	cmd.Flags().BoolVar(&bodyWarehouseLockedFlag, "warehouse-locked-flag", false, "Locked flag")
	cmd.Flags().StringVar(&bodyWarehouseName, "warehouse-name", "", "Name")
	cmd.Flags().StringVar(&bodyWarehouseContactInfo, "warehouse-contact-info", "", "Info")
	cmd.Flags().StringVar(&bodyWarehouseContactId, "warehouse-contact-id", "", "Id")
	cmd.Flags().StringVar(&bodyWarehouseContactName, "warehouse-contact-name", "", "Name")
	cmd.Flags().BoolVar(&stdinBody, "stdin", false, "Read request body as JSON from stdin")

	return cmd
}
