// Copyright 2026 Damien Stevens and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"os"

	"github.com/spf13/cobra"
)

func newServicePostTicketsByParentIdTasksCmd(flags *rootFlags) *cobra.Command {
	var bodyInfo string
	var bodyChildScheduleAction string
	var bodyChildTicketId string
	var bodyClosedFlag bool
	var bodyCodeInfo string
	var bodyCodeId string
	var bodyCodeName string
	var bodyId string
	var bodyMemberInfo string
	var bodyMemberDailyCapacity float64
	var bodyMemberId string
	var bodyMemberIdentifier string
	var bodyMemberName string
	var bodyNotes string
	var bodyPriority int
	var bodyResolution string
	var bodyScheduleInfo string
	var bodyScheduleDescription string
	var bodyScheduleId string
	var bodySummary string
	var bodyTicketId string
	var stdinBody bool

	cmd := &cobra.Command{
		Use:         "post-tickets-by-parent-id-tasks <parentId>",
		Short:       "Post Task",
		Example:     "  connectwise-manage-cli service post-tickets-by-parent-id-tasks 42",
		Annotations: map[string]string{"pp:endpoint": "service.post-tickets-by-parent-id-tasks", "pp:method": "POST", "pp:path": "/service/tickets/{parentId}/tasks"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) == 0 {
				return cmd.Help()
			}
			if !stdinBody {
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/service/tickets/{parentId}/tasks"
			path = replacePathParam(path, "parentId", args[0])
			params := map[string]string{}
			var body map[string]any
			if stdinBody {
				stdinData, err := io.ReadAll(os.Stdin)
				if err != nil {
					return fmt.Errorf("reading stdin: %w", err)
				}
				var jsonBody map[string]any
				if err := json.Unmarshal(stdinData, &jsonBody); err != nil {
					return fmt.Errorf("parsing stdin JSON: %w", err)
				}
				body = jsonBody
			} else {
				body = map[string]any{}
				if bodyInfo != "" {
					var parsedInfo any
					if err := json.Unmarshal([]byte(bodyInfo), &parsedInfo); err != nil {
						return fmt.Errorf("parsing --info JSON: %w", err)
					}
					body["_info"] = parsedInfo
				}
				if bodyChildScheduleAction != "" {
					body["childScheduleAction"] = bodyChildScheduleAction
				}
				if bodyChildTicketId != "" {
					body["childTicketId"] = bodyChildTicketId
				}
				if cmd.Flags().Changed("closed-flag") {
					body["closedFlag"] = bodyClosedFlag
				}
				{
					nestedCode := map[string]any{}
					if bodyCodeInfo != "" {
						var parsedCodeInfo any
						if err := json.Unmarshal([]byte(bodyCodeInfo), &parsedCodeInfo); err != nil {
							return fmt.Errorf("parsing --code-info JSON: %w", err)
						}
						nestedCode["_info"] = parsedCodeInfo
					}
					if bodyCodeId != "" {
						nestedCode["id"] = bodyCodeId
					}
					if bodyCodeName != "" {
						nestedCode["name"] = bodyCodeName
					}
					if len(nestedCode) > 0 {
						body["code"] = nestedCode
					}
				}
				if bodyId != "" {
					body["id"] = bodyId
				}
				{
					nestedMember := map[string]any{}
					if bodyMemberInfo != "" {
						var parsedMemberInfo any
						if err := json.Unmarshal([]byte(bodyMemberInfo), &parsedMemberInfo); err != nil {
							return fmt.Errorf("parsing --member-info JSON: %w", err)
						}
						nestedMember["_info"] = parsedMemberInfo
					}
					if bodyMemberDailyCapacity != 0.0 {
						nestedMember["dailyCapacity"] = bodyMemberDailyCapacity
					}
					if bodyMemberId != "" {
						nestedMember["id"] = bodyMemberId
					}
					if bodyMemberIdentifier != "" {
						nestedMember["identifier"] = bodyMemberIdentifier
					}
					if bodyMemberName != "" {
						nestedMember["name"] = bodyMemberName
					}
					if len(nestedMember) > 0 {
						body["member"] = nestedMember
					}
				}
				if bodyNotes != "" {
					body["notes"] = bodyNotes
				}
				if bodyPriority != 0 {
					body["priority"] = bodyPriority
				}
				if bodyResolution != "" {
					body["resolution"] = bodyResolution
				}
				{
					nestedSchedule := map[string]any{}
					if bodyScheduleInfo != "" {
						var parsedScheduleInfo any
						if err := json.Unmarshal([]byte(bodyScheduleInfo), &parsedScheduleInfo); err != nil {
							return fmt.Errorf("parsing --schedule-info JSON: %w", err)
						}
						nestedSchedule["_info"] = parsedScheduleInfo
					}
					if bodyScheduleDescription != "" {
						nestedSchedule["description"] = bodyScheduleDescription
					}
					if bodyScheduleId != "" {
						nestedSchedule["id"] = bodyScheduleId
					}
					if len(nestedSchedule) > 0 {
						body["schedule"] = nestedSchedule
					}
				}
				if bodySummary != "" {
					body["summary"] = bodySummary
				}
				if bodyTicketId != "" {
					body["ticketId"] = bodyTicketId
				}
			}
			data, statusCode, err := c.PostWithParams(cmd.Context(), path, params, body)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Inspect the mutate response body for a partial-failure-shaped
			// field (e.g. Google Ads `partialFailureError`). Several Google
			// APIs return 200 OK with a partial-failure field when some
			// operations in the batch failed; ignoring it silently swallows
			// real failures. Detection runs before output-mode selection so
			// the exit code is consistent regardless of how stdout is
			// rendered. --dry-run short-circuits because no real request
			// was sent.
			var partialFailure *partialFailureReport
			if !flags.dryRun && statusCode >= 200 && statusCode < 300 {
				partialFailure = detectPartialFailure(data)
				if partialFailure != nil {
					fmt.Fprintf(os.Stderr, "warning: partial failure detected in %s response: %s\n", "service", partialFailure.Message)
					if len(partialFailure.ResourceNames) > 0 {
						fmt.Fprintf(os.Stderr, "         succeeded: %d operation(s)\n", len(partialFailure.ResourceNames))
					}
				}
			}
			if !flags.dryRun && statusCode >= 200 && statusCode < 300 && (partialFailure == nil || flags.allowPartialFailure) {
				writeMutationResponseToStore(cmd.Context(), "service", data, "")
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				// Check if response contains an array (directly or wrapped in "data")
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
					} else {
						if partialFailure != nil && !flags.allowPartialFailure {
							return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "service", partialFailure.Message))
						}
						return nil
					}
				} else {
					var wrapped struct {
						Data []map[string]any `json:"data"`
					}
					if json.Unmarshal(data, &wrapped) == nil && len(wrapped.Data) > 0 {
						if err := printAutoTable(cmd.OutOrStdout(), wrapped.Data); err != nil {
							fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
						} else {
							if partialFailure != nil && !flags.allowPartialFailure {
								return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "service", partialFailure.Message))
							}
							return nil
						}
					}
				}
			}
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				if flags.quiet {
					if partialFailure != nil && !flags.allowPartialFailure {
						return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "service", partialFailure.Message))
					}
					return nil
				}
				envelope := map[string]any{
					"action":   "post",
					"resource": "service",
					"path":     path,
					"status":   statusCode,
					"success":  statusCode >= 200 && statusCode < 300 && (partialFailure == nil || flags.allowPartialFailure),
				}
				if partialFailure != nil {
					envelope["partial_failure"] = partialFailure
				}
				if flags.dryRun {
					envelope["dry_run"] = true
					envelope["status"] = 0
					envelope["success"] = false
				}
				// Verify-mode synthetic envelope detection runs against RAW data
				// (before --compact/--select filtering) so the sentinel field is
				// guaranteed to be visible even if the operator passes a filter
				// flag that would otherwise strip it. Surfaces a top-level
				// verify_noop signal + flips success to false. Mirrors the dry_run
				// shape above.
				if len(data) > 0 {
					var rawParsed any
					if err := json.Unmarshal(data, &rawParsed); err == nil {
						if m, ok := rawParsed.(map[string]any); ok {
							if v, ok := m["__pp_verify_synthetic__"].(bool); ok && v {
								envelope["verify_noop"] = true
								envelope["success"] = false
							}
						}
					}
				}
				// Apply --compact and --select to the API response before wrapping.
				// --select wins when both are set: explicit field choice trumps the
				// generic high-gravity allow-list. Otherwise --compact still applies
				// when --agent is on but the user did not name fields.
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				if len(filtered) > 0 {
					var parsed any
					if err := json.Unmarshal(filtered, &parsed); err == nil {
						envelope["data"] = parsed
					}
				}
				envelopeJSON, err := json.Marshal(envelope)
				if err != nil {
					return err
				}
				if perr := printOutput(cmd.OutOrStdout(), json.RawMessage(envelopeJSON), true); perr != nil {
					return perr
				}
				if partialFailure != nil && !flags.allowPartialFailure {
					return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "service", partialFailure.Message))
				}
				return nil
			}
			// Fall-through for mutate paths that did not hit the table or
			// asJSON branches: --quiet, --csv, --plain, and default terminal
			// raw output. printOutputWithFlags renders the body, then the
			// typed partial-failure exit fires unless --allow-partial-failure
			// downgrades it. Without this guard a partial failure would exit
			// 0 for these output modes — the exact silent-swallow regression
			// the surrounding patch is preventing for asJSON / piped output.
			if perr := printOutputWithFlags(cmd.OutOrStdout(), data, flags); perr != nil {
				return perr
			}
			if partialFailure != nil && !flags.allowPartialFailure {
				return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "service", partialFailure.Message))
			}
			return nil
		},
	}
	cmd.Flags().StringVar(&bodyInfo, "info", "", "Info")
	cmd.Flags().StringVar(&bodyChildScheduleAction, "child-schedule-action", "", "Child schedule action")
	cmd.Flags().StringVar(&bodyChildTicketId, "child-ticket-id", "", "Child ticket id")
	cmd.Flags().BoolVar(&bodyClosedFlag, "closed-flag", false, "Closed flag")
	cmd.Flags().StringVar(&bodyCodeInfo, "code-info", "", "Info")
	cmd.Flags().StringVar(&bodyCodeId, "code-id", "", "Id")
	cmd.Flags().StringVar(&bodyCodeName, "code-name", "", "Name")
	cmd.Flags().StringVar(&bodyId, "id", "", "Id")
	cmd.Flags().StringVar(&bodyMemberInfo, "member-info", "", "Info")
	cmd.Flags().Float64Var(&bodyMemberDailyCapacity, "member-daily-capacity", 0.0, "Daily capacity")
	cmd.Flags().StringVar(&bodyMemberId, "member-id", "", "Id")
	cmd.Flags().StringVar(&bodyMemberIdentifier, "member-identifier", "", "Identifier")
	cmd.Flags().StringVar(&bodyMemberName, "member-name", "", "Name")
	cmd.Flags().StringVar(&bodyNotes, "notes", "", "Notes")
	cmd.Flags().IntVar(&bodyPriority, "priority", 0, "Priority")
	cmd.Flags().StringVar(&bodyResolution, "resolution", "", "Resolution")
	cmd.Flags().StringVar(&bodyScheduleInfo, "schedule-info", "", "Info")
	cmd.Flags().StringVar(&bodyScheduleDescription, "schedule-description", "", "Description")
	cmd.Flags().StringVar(&bodyScheduleId, "schedule-id", "", "Id")
	cmd.Flags().StringVar(&bodySummary, "summary", "", "Summary")
	cmd.Flags().StringVar(&bodyTicketId, "ticket-id", "", "Ticket id")
	cmd.Flags().BoolVar(&stdinBody, "stdin", false, "Read request body as JSON from stdin")

	return cmd
}
