// Copyright 2026 Damien Stevens and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package types

type Datacenter struct {
	Name string `json:"name"`
}

type Subscription struct {
	Id          string `json:"id"`
	CompanyName string `json:"companyName"`
}
