// Copyright 2026 Damien Stevens and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newCompaniesLocationsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "locations",
		Short:       "Get, create, update, and delete locations for companies",
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newCompaniesLocationsCompanyChildCreateEntityCmd(flags))
	cmd.AddCommand(newCompaniesLocationsCompanyChildDeleteEntityCmd(flags))
	cmd.AddCommand(newCompaniesLocationsCompanyChildPatchEntityCmd(flags))
	cmd.AddCommand(newCompaniesLocationsCompanyChildQueryCmd(flags))
	cmd.AddCommand(newCompaniesLocationsCompanyChildQueryEntityInformationCmd(flags))
	cmd.AddCommand(newCompaniesLocationsCompanyChildQueryFieldDefinitionsCmd(flags))
	cmd.AddCommand(newCompaniesLocationsCompanyChildQueryItemCmd(flags))
	cmd.AddCommand(newCompaniesLocationsCompanyChildQueryUserDefinedFieldDefinitionsCmd(flags))
	cmd.AddCommand(newCompaniesLocationsCompanyChildUpdateEntityCmd(flags))
	return cmd
}
