// Copyright 2026 Damien Stevens and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newProjectsChargesCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "charges",
		Short:       "Get, create, update, and delete charges for projects",
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newProjectsChargesProjectChildCreateEntityCmd(flags))
	cmd.AddCommand(newProjectsChargesProjectChildDeleteEntityCmd(flags))
	cmd.AddCommand(newProjectsChargesProjectChildPatchEntityCmd(flags))
	cmd.AddCommand(newProjectsChargesProjectChildQueryCmd(flags))
	cmd.AddCommand(newProjectsChargesProjectChildQueryEntityInformationCmd(flags))
	cmd.AddCommand(newProjectsChargesProjectChildQueryFieldDefinitionsCmd(flags))
	cmd.AddCommand(newProjectsChargesProjectChildQueryItemCmd(flags))
	cmd.AddCommand(newProjectsChargesProjectChildQueryUserDefinedFieldDefinitionsCmd(flags))
	cmd.AddCommand(newProjectsChargesProjectChildUpdateEntityCmd(flags))
	return cmd
}
