// Copyright 2026 Damien Stevens and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"os"

	"github.com/spf13/cobra"
)

func newTicketsCreateEntityCmd(flags *rootFlags) *cobra.Command {
	var bodyApiVendorID string
	var bodyAssignedResourceID string
	var bodyAssignedResourceRoleID string
	var bodyBillingCodeID string
	var bodyChangeApprovalBoard int
	var bodyChangeApprovalStatus int
	var bodyChangeApprovalType int
	var bodyChangeInfoField1 string
	var bodyChangeInfoField2 string
	var bodyChangeInfoField3 string
	var bodyChangeInfoField4 string
	var bodyChangeInfoField5 string
	var bodyCompanyID string
	var bodyCompanyLocationID string
	var bodyCompletedByResourceID string
	var bodyCompletedDate string
	var bodyConfigurationItemID string
	var bodyContactID string
	var bodyContractID string
	var bodyContractServiceBundleID string
	var bodyContractServiceID string
	var bodyCreateDate string
	var bodyCreatedByContactID string
	var bodyCreatorResourceID string
	var bodyCreatorType int
	var bodyCurrentServiceThermometerRating int
	var bodyDescription string
	var bodyDueDateTime string
	var bodyEstimatedHours float64
	var bodyExternalID string
	var bodyFirstResponseAssignedResourceID string
	var bodyFirstResponseDateTime string
	var bodyFirstResponseDueDateTime string
	var bodyFirstResponseInitiatingResourceID string
	var bodyHoursToBeScheduled float64
	var bodyId string
	var bodyImpersonatorCreatorResourceID string
	var bodyIsAssignedToComanaged bool
	var bodyIsVisibleToComanaged bool
	var bodyIssueType int
	var bodyLastActivityDate string
	var bodyLastActivityPersonType int
	var bodyLastActivityResourceID string
	var bodyLastCustomerNotificationDateTime string
	var bodyLastCustomerVisibleActivityDateTime string
	var bodyLastTrackedModificationDateTime string
	var bodyMonitorID string
	var bodyMonitorTypeID string
	var bodyOpportunityID string
	var bodyOrganizationalLevelAssociationID string
	var bodyPreviousServiceThermometerRating int
	var bodyPriority int
	var bodyProblemTicketId string
	var bodyProjectID string
	var bodyPurchaseOrderNumber string
	var bodyQueueID string
	var bodyResolution string
	var bodyResolutionPlanDateTime string
	var bodyResolutionPlanDueDateTime string
	var bodyResolvedDateTime string
	var bodyResolvedDueDateTime string
	var bodyRmaStatus int
	var bodyRmaType int
	var bodyRmmAlertID string
	var bodyServiceLevelAgreementHasBeenMet bool
	var bodyServiceLevelAgreementID string
	var bodyServiceLevelAgreementPausedNextEventHours float64
	var bodyServiceThermometerTemperature int
	var bodySource int
	var bodyStatus int
	var bodySubIssueType int
	var bodyTicketCategory int
	var bodyTicketNumber string
	var bodyTicketType int
	var bodyTitle string
	var bodyUserDefinedFields string
	var stdinBody bool

	cmd := &cobra.Command{
		Use:         "create-entity",
		Aliases:     []string{"create"},
		Short:       "Create entity",
		Example:     "  autotask-cli tickets create-entity",
		Annotations: map[string]string{"pp:endpoint": "tickets.create-entity", "pp:method": "POST", "pp:path": "/Tickets"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if !stdinBody {
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/Tickets"
			params := map[string]string{}
			var body map[string]any
			if stdinBody {
				stdinData, err := io.ReadAll(os.Stdin)
				if err != nil {
					return fmt.Errorf("reading stdin: %w", err)
				}
				var jsonBody map[string]any
				if err := json.Unmarshal(stdinData, &jsonBody); err != nil {
					return fmt.Errorf("parsing stdin JSON: %w", err)
				}
				body = jsonBody
			} else {
				body = map[string]any{}
				if bodyApiVendorID != "" {
					body["apiVendorID"] = bodyApiVendorID
				}
				if bodyAssignedResourceID != "" {
					body["assignedResourceID"] = bodyAssignedResourceID
				}
				if bodyAssignedResourceRoleID != "" {
					body["assignedResourceRoleID"] = bodyAssignedResourceRoleID
				}
				if bodyBillingCodeID != "" {
					body["billingCodeID"] = bodyBillingCodeID
				}
				if bodyChangeApprovalBoard != 0 {
					body["changeApprovalBoard"] = bodyChangeApprovalBoard
				}
				if bodyChangeApprovalStatus != 0 {
					body["changeApprovalStatus"] = bodyChangeApprovalStatus
				}
				if bodyChangeApprovalType != 0 {
					body["changeApprovalType"] = bodyChangeApprovalType
				}
				if bodyChangeInfoField1 != "" {
					body["changeInfoField1"] = bodyChangeInfoField1
				}
				if bodyChangeInfoField2 != "" {
					body["changeInfoField2"] = bodyChangeInfoField2
				}
				if bodyChangeInfoField3 != "" {
					body["changeInfoField3"] = bodyChangeInfoField3
				}
				if bodyChangeInfoField4 != "" {
					body["changeInfoField4"] = bodyChangeInfoField4
				}
				if bodyChangeInfoField5 != "" {
					body["changeInfoField5"] = bodyChangeInfoField5
				}
				if bodyCompanyID != "" {
					body["companyID"] = bodyCompanyID
				}
				if bodyCompanyLocationID != "" {
					body["companyLocationID"] = bodyCompanyLocationID
				}
				if bodyCompletedByResourceID != "" {
					body["completedByResourceID"] = bodyCompletedByResourceID
				}
				if bodyCompletedDate != "" {
					body["completedDate"] = bodyCompletedDate
				}
				if bodyConfigurationItemID != "" {
					body["configurationItemID"] = bodyConfigurationItemID
				}
				if bodyContactID != "" {
					body["contactID"] = bodyContactID
				}
				if bodyContractID != "" {
					body["contractID"] = bodyContractID
				}
				if bodyContractServiceBundleID != "" {
					body["contractServiceBundleID"] = bodyContractServiceBundleID
				}
				if bodyContractServiceID != "" {
					body["contractServiceID"] = bodyContractServiceID
				}
				if bodyCreateDate != "" {
					body["createDate"] = bodyCreateDate
				}
				if bodyCreatedByContactID != "" {
					body["createdByContactID"] = bodyCreatedByContactID
				}
				if bodyCreatorResourceID != "" {
					body["creatorResourceID"] = bodyCreatorResourceID
				}
				if bodyCreatorType != 0 {
					body["creatorType"] = bodyCreatorType
				}
				if bodyCurrentServiceThermometerRating != 0 {
					body["currentServiceThermometerRating"] = bodyCurrentServiceThermometerRating
				}
				if bodyDescription != "" {
					body["description"] = bodyDescription
				}
				if bodyDueDateTime != "" {
					body["dueDateTime"] = bodyDueDateTime
				}
				if bodyEstimatedHours != 0.0 {
					body["estimatedHours"] = bodyEstimatedHours
				}
				if bodyExternalID != "" {
					body["externalID"] = bodyExternalID
				}
				if bodyFirstResponseAssignedResourceID != "" {
					body["firstResponseAssignedResourceID"] = bodyFirstResponseAssignedResourceID
				}
				if bodyFirstResponseDateTime != "" {
					body["firstResponseDateTime"] = bodyFirstResponseDateTime
				}
				if bodyFirstResponseDueDateTime != "" {
					body["firstResponseDueDateTime"] = bodyFirstResponseDueDateTime
				}
				if bodyFirstResponseInitiatingResourceID != "" {
					body["firstResponseInitiatingResourceID"] = bodyFirstResponseInitiatingResourceID
				}
				if bodyHoursToBeScheduled != 0.0 {
					body["hoursToBeScheduled"] = bodyHoursToBeScheduled
				}
				if bodyId != "" {
					body["id"] = bodyId
				}
				if bodyImpersonatorCreatorResourceID != "" {
					body["impersonatorCreatorResourceID"] = bodyImpersonatorCreatorResourceID
				}
				if cmd.Flags().Changed("is-assigned-to-comanaged") {
					body["isAssignedToComanaged"] = bodyIsAssignedToComanaged
				}
				if cmd.Flags().Changed("is-visible-to-comanaged") {
					body["isVisibleToComanaged"] = bodyIsVisibleToComanaged
				}
				if bodyIssueType != 0 {
					body["issueType"] = bodyIssueType
				}
				if bodyLastActivityDate != "" {
					body["lastActivityDate"] = bodyLastActivityDate
				}
				if bodyLastActivityPersonType != 0 {
					body["lastActivityPersonType"] = bodyLastActivityPersonType
				}
				if bodyLastActivityResourceID != "" {
					body["lastActivityResourceID"] = bodyLastActivityResourceID
				}
				if bodyLastCustomerNotificationDateTime != "" {
					body["lastCustomerNotificationDateTime"] = bodyLastCustomerNotificationDateTime
				}
				if bodyLastCustomerVisibleActivityDateTime != "" {
					body["lastCustomerVisibleActivityDateTime"] = bodyLastCustomerVisibleActivityDateTime
				}
				if bodyLastTrackedModificationDateTime != "" {
					body["lastTrackedModificationDateTime"] = bodyLastTrackedModificationDateTime
				}
				if bodyMonitorID != "" {
					body["monitorID"] = bodyMonitorID
				}
				if bodyMonitorTypeID != "" {
					body["monitorTypeID"] = bodyMonitorTypeID
				}
				if bodyOpportunityID != "" {
					body["opportunityID"] = bodyOpportunityID
				}
				if bodyOrganizationalLevelAssociationID != "" {
					body["organizationalLevelAssociationID"] = bodyOrganizationalLevelAssociationID
				}
				if bodyPreviousServiceThermometerRating != 0 {
					body["previousServiceThermometerRating"] = bodyPreviousServiceThermometerRating
				}
				if bodyPriority != 0 {
					body["priority"] = bodyPriority
				}
				if bodyProblemTicketId != "" {
					body["problemTicketId"] = bodyProblemTicketId
				}
				if bodyProjectID != "" {
					body["projectID"] = bodyProjectID
				}
				if bodyPurchaseOrderNumber != "" {
					body["purchaseOrderNumber"] = bodyPurchaseOrderNumber
				}
				if bodyQueueID != "" {
					body["queueID"] = bodyQueueID
				}
				if bodyResolution != "" {
					body["resolution"] = bodyResolution
				}
				if bodyResolutionPlanDateTime != "" {
					body["resolutionPlanDateTime"] = bodyResolutionPlanDateTime
				}
				if bodyResolutionPlanDueDateTime != "" {
					body["resolutionPlanDueDateTime"] = bodyResolutionPlanDueDateTime
				}
				if bodyResolvedDateTime != "" {
					body["resolvedDateTime"] = bodyResolvedDateTime
				}
				if bodyResolvedDueDateTime != "" {
					body["resolvedDueDateTime"] = bodyResolvedDueDateTime
				}
				if bodyRmaStatus != 0 {
					body["rmaStatus"] = bodyRmaStatus
				}
				if bodyRmaType != 0 {
					body["rmaType"] = bodyRmaType
				}
				if bodyRmmAlertID != "" {
					body["rmmAlertID"] = bodyRmmAlertID
				}
				if cmd.Flags().Changed("service-level-agreement-has-been-met") {
					body["serviceLevelAgreementHasBeenMet"] = bodyServiceLevelAgreementHasBeenMet
				}
				if bodyServiceLevelAgreementID != "" {
					body["serviceLevelAgreementID"] = bodyServiceLevelAgreementID
				}
				if bodyServiceLevelAgreementPausedNextEventHours != 0.0 {
					body["serviceLevelAgreementPausedNextEventHours"] = bodyServiceLevelAgreementPausedNextEventHours
				}
				if bodyServiceThermometerTemperature != 0 {
					body["serviceThermometerTemperature"] = bodyServiceThermometerTemperature
				}
				if bodySource != 0 {
					body["source"] = bodySource
				}
				if bodyStatus != 0 {
					body["status"] = bodyStatus
				}
				if bodySubIssueType != 0 {
					body["subIssueType"] = bodySubIssueType
				}
				if bodyTicketCategory != 0 {
					body["ticketCategory"] = bodyTicketCategory
				}
				if bodyTicketNumber != "" {
					body["ticketNumber"] = bodyTicketNumber
				}
				if bodyTicketType != 0 {
					body["ticketType"] = bodyTicketType
				}
				if bodyTitle != "" {
					body["title"] = bodyTitle
				}
				if bodyUserDefinedFields != "" {
					var parsedUserDefinedFields any
					if err := json.Unmarshal([]byte(bodyUserDefinedFields), &parsedUserDefinedFields); err != nil {
						return fmt.Errorf("parsing --user-defined-fields JSON: %w", err)
					}
					body["userDefinedFields"] = parsedUserDefinedFields
				}
			}
			data, statusCode, err := c.PostWithParams(cmd.Context(), path, params, body)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Inspect the mutate response body for a partial-failure-shaped
			// field (e.g. Google Ads `partialFailureError`). Several Google
			// APIs return 200 OK with a partial-failure field when some
			// operations in the batch failed; ignoring it silently swallows
			// real failures. Detection runs before output-mode selection so
			// the exit code is consistent regardless of how stdout is
			// rendered. --dry-run short-circuits because no real request
			// was sent.
			var partialFailure *partialFailureReport
			if !flags.dryRun && statusCode >= 200 && statusCode < 300 {
				partialFailure = detectPartialFailure(data)
				if partialFailure != nil {
					fmt.Fprintf(os.Stderr, "warning: partial failure detected in %s response: %s\n", "tickets", partialFailure.Message)
					if len(partialFailure.ResourceNames) > 0 {
						fmt.Fprintf(os.Stderr, "         succeeded: %d operation(s)\n", len(partialFailure.ResourceNames))
					}
				}
			}
			if !flags.dryRun && statusCode >= 200 && statusCode < 300 && (partialFailure == nil || flags.allowPartialFailure) {
				writeMutationResponseToStore(cmd.Context(), "tickets", data, "")
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				// Check if response contains an array (directly or wrapped in "data")
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
					} else {
						if partialFailure != nil && !flags.allowPartialFailure {
							return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "tickets", partialFailure.Message))
						}
						return nil
					}
				} else {
					var wrapped struct {
						Data []map[string]any `json:"data"`
					}
					if json.Unmarshal(data, &wrapped) == nil && len(wrapped.Data) > 0 {
						if err := printAutoTable(cmd.OutOrStdout(), wrapped.Data); err != nil {
							fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
						} else {
							if partialFailure != nil && !flags.allowPartialFailure {
								return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "tickets", partialFailure.Message))
							}
							return nil
						}
					}
				}
			}
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				if flags.quiet {
					if partialFailure != nil && !flags.allowPartialFailure {
						return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "tickets", partialFailure.Message))
					}
					return nil
				}
				envelope := map[string]any{
					"action":   "post",
					"resource": "tickets",
					"path":     path,
					"status":   statusCode,
					"success":  statusCode >= 200 && statusCode < 300 && (partialFailure == nil || flags.allowPartialFailure),
				}
				if partialFailure != nil {
					envelope["partial_failure"] = partialFailure
				}
				if flags.dryRun {
					envelope["dry_run"] = true
					envelope["status"] = 0
					envelope["success"] = false
				}
				// Verify-mode synthetic envelope detection runs against RAW data
				// (before --compact/--select filtering) so the sentinel field is
				// guaranteed to be visible even if the operator passes a filter
				// flag that would otherwise strip it. Surfaces a top-level
				// verify_noop signal + flips success to false. Mirrors the dry_run
				// shape above.
				if len(data) > 0 {
					var rawParsed any
					if err := json.Unmarshal(data, &rawParsed); err == nil {
						if m, ok := rawParsed.(map[string]any); ok {
							if v, ok := m["__pp_verify_synthetic__"].(bool); ok && v {
								envelope["verify_noop"] = true
								envelope["success"] = false
							}
						}
					}
				}
				// Apply --compact and --select to the API response before wrapping.
				// --select wins when both are set: explicit field choice trumps the
				// generic high-gravity allow-list. Otherwise --compact still applies
				// when --agent is on but the user did not name fields.
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				if len(filtered) > 0 {
					var parsed any
					if err := json.Unmarshal(filtered, &parsed); err == nil {
						envelope["data"] = parsed
					}
				}
				envelopeJSON, err := json.Marshal(envelope)
				if err != nil {
					return err
				}
				if perr := printOutput(cmd.OutOrStdout(), json.RawMessage(envelopeJSON), true); perr != nil {
					return perr
				}
				if partialFailure != nil && !flags.allowPartialFailure {
					return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "tickets", partialFailure.Message))
				}
				return nil
			}
			// Fall-through for mutate paths that did not hit the table or
			// asJSON branches: --quiet, --csv, --plain, and default terminal
			// raw output. printOutputWithFlags renders the body, then the
			// typed partial-failure exit fires unless --allow-partial-failure
			// downgrades it. Without this guard a partial failure would exit
			// 0 for these output modes — the exact silent-swallow regression
			// the surrounding patch is preventing for asJSON / piped output.
			if perr := printOutputWithFlags(cmd.OutOrStdout(), data, flags); perr != nil {
				return perr
			}
			if partialFailure != nil && !flags.allowPartialFailure {
				return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "tickets", partialFailure.Message))
			}
			return nil
		},
	}
	cmd.Flags().StringVar(&bodyApiVendorID, "api-vendor-id", "", "Api vendor id")
	cmd.Flags().StringVar(&bodyAssignedResourceID, "assigned-resource-id", "", "Assigned resource id")
	cmd.Flags().StringVar(&bodyAssignedResourceRoleID, "assigned-resource-role-id", "", "Assigned resource role id")
	cmd.Flags().StringVar(&bodyBillingCodeID, "billing-code-id", "", "Billing code id")
	cmd.Flags().IntVar(&bodyChangeApprovalBoard, "change-approval-board", 0, "Change approval board")
	cmd.Flags().IntVar(&bodyChangeApprovalStatus, "change-approval-status", 0, "Change approval status")
	cmd.Flags().IntVar(&bodyChangeApprovalType, "change-approval-type", 0, "Change approval type")
	cmd.Flags().StringVar(&bodyChangeInfoField1, "change-info-field1", "", "Change info field1")
	cmd.Flags().StringVar(&bodyChangeInfoField2, "change-info-field2", "", "Change info field2")
	cmd.Flags().StringVar(&bodyChangeInfoField3, "change-info-field3", "", "Change info field3")
	cmd.Flags().StringVar(&bodyChangeInfoField4, "change-info-field4", "", "Change info field4")
	cmd.Flags().StringVar(&bodyChangeInfoField5, "change-info-field5", "", "Change info field5")
	cmd.Flags().StringVar(&bodyCompanyID, "company-id", "", "Company id")
	cmd.Flags().StringVar(&bodyCompanyLocationID, "company-location-id", "", "Company location id")
	cmd.Flags().StringVar(&bodyCompletedByResourceID, "completed-by-resource-id", "", "Completed by resource id")
	cmd.Flags().StringVar(&bodyCompletedDate, "completed-date", "", "Completed date")
	cmd.Flags().StringVar(&bodyConfigurationItemID, "configuration-item-id", "", "Configuration item id")
	cmd.Flags().StringVar(&bodyContactID, "contact-id", "", "Contact id")
	cmd.Flags().StringVar(&bodyContractID, "contract-id", "", "Contract id")
	cmd.Flags().StringVar(&bodyContractServiceBundleID, "contract-service-bundle-id", "", "Contract service bundle id")
	cmd.Flags().StringVar(&bodyContractServiceID, "contract-service-id", "", "Contract service id")
	cmd.Flags().StringVar(&bodyCreateDate, "create-date", "", "Create date")
	cmd.Flags().StringVar(&bodyCreatedByContactID, "created-by-contact-id", "", "Created by contact id")
	cmd.Flags().StringVar(&bodyCreatorResourceID, "creator-resource-id", "", "Creator resource id")
	cmd.Flags().IntVar(&bodyCreatorType, "creator-type", 0, "Creator type")
	cmd.Flags().IntVar(&bodyCurrentServiceThermometerRating, "current-service-thermometer-rating", 0, "Current service thermometer rating")
	cmd.Flags().StringVar(&bodyDescription, "description", "", "Description")
	cmd.Flags().StringVar(&bodyDueDateTime, "due-date-time", "", "Due date time")
	cmd.Flags().Float64Var(&bodyEstimatedHours, "estimated-hours", 0.0, "Estimated hours")
	cmd.Flags().StringVar(&bodyExternalID, "external-id", "", "External id")
	cmd.Flags().StringVar(&bodyFirstResponseAssignedResourceID, "first-response-assigned-resource-id", "", "First response assigned resource id")
	cmd.Flags().StringVar(&bodyFirstResponseDateTime, "first-response-date-time", "", "First response date time")
	cmd.Flags().StringVar(&bodyFirstResponseDueDateTime, "first-response-due-date-time", "", "First response due date time")
	cmd.Flags().StringVar(&bodyFirstResponseInitiatingResourceID, "first-response-initiating-resource-id", "", "First response initiating resource id")
	cmd.Flags().Float64Var(&bodyHoursToBeScheduled, "hours-to-be-scheduled", 0.0, "Hours to be scheduled")
	cmd.Flags().StringVar(&bodyId, "id", "", "Id")
	cmd.Flags().StringVar(&bodyImpersonatorCreatorResourceID, "impersonator-creator-resource-id", "", "Impersonator creator resource id")
	cmd.Flags().BoolVar(&bodyIsAssignedToComanaged, "is-assigned-to-comanaged", false, "Is assigned to comanaged")
	cmd.Flags().BoolVar(&bodyIsVisibleToComanaged, "is-visible-to-comanaged", false, "Is visible to comanaged")
	cmd.Flags().IntVar(&bodyIssueType, "issue-type", 0, "Issue type")
	cmd.Flags().StringVar(&bodyLastActivityDate, "last-activity-date", "", "Last activity date")
	cmd.Flags().IntVar(&bodyLastActivityPersonType, "last-activity-person-type", 0, "Last activity person type")
	cmd.Flags().StringVar(&bodyLastActivityResourceID, "last-activity-resource-id", "", "Last activity resource id")
	cmd.Flags().StringVar(&bodyLastCustomerNotificationDateTime, "last-customer-notification-date-time", "", "Last customer notification date time")
	cmd.Flags().StringVar(&bodyLastCustomerVisibleActivityDateTime, "last-customer-visible-activity-date-time", "", "Last customer visible activity date time")
	cmd.Flags().StringVar(&bodyLastTrackedModificationDateTime, "last-tracked-modification-date-time", "", "Last tracked modification date time")
	cmd.Flags().StringVar(&bodyMonitorID, "monitor-id", "", "Monitor id")
	cmd.Flags().StringVar(&bodyMonitorTypeID, "monitor-type-id", "", "Monitor type id")
	cmd.Flags().StringVar(&bodyOpportunityID, "opportunity-id", "", "Opportunity id")
	cmd.Flags().StringVar(&bodyOrganizationalLevelAssociationID, "organizational-level-association-id", "", "Organizational level association id")
	cmd.Flags().IntVar(&bodyPreviousServiceThermometerRating, "previous-service-thermometer-rating", 0, "Previous service thermometer rating")
	cmd.Flags().IntVar(&bodyPriority, "priority", 0, "Priority")
	cmd.Flags().StringVar(&bodyProblemTicketId, "problem-ticket-id", "", "Problem ticket id")
	cmd.Flags().StringVar(&bodyProjectID, "project-id", "", "Project id")
	cmd.Flags().StringVar(&bodyPurchaseOrderNumber, "purchase-order-number", "", "Purchase order number")
	cmd.Flags().StringVar(&bodyQueueID, "queue-id", "", "Queue id")
	cmd.Flags().StringVar(&bodyResolution, "resolution", "", "Resolution")
	cmd.Flags().StringVar(&bodyResolutionPlanDateTime, "resolution-plan-date-time", "", "Resolution plan date time")
	cmd.Flags().StringVar(&bodyResolutionPlanDueDateTime, "resolution-plan-due-date-time", "", "Resolution plan due date time")
	cmd.Flags().StringVar(&bodyResolvedDateTime, "resolved-date-time", "", "Resolved date time")
	cmd.Flags().StringVar(&bodyResolvedDueDateTime, "resolved-due-date-time", "", "Resolved due date time")
	cmd.Flags().IntVar(&bodyRmaStatus, "rma-status", 0, "Rma status")
	cmd.Flags().IntVar(&bodyRmaType, "rma-type", 0, "Rma type")
	cmd.Flags().StringVar(&bodyRmmAlertID, "rmm-alert-id", "", "Rmm alert id")
	cmd.Flags().BoolVar(&bodyServiceLevelAgreementHasBeenMet, "service-level-agreement-has-been-met", false, "Service level agreement has been met")
	cmd.Flags().StringVar(&bodyServiceLevelAgreementID, "service-level-agreement-id", "", "Service level agreement id")
	cmd.Flags().Float64Var(&bodyServiceLevelAgreementPausedNextEventHours, "service-level-agreement-paused-next-event-hours", 0.0, "Service level agreement paused next event hours")
	cmd.Flags().IntVar(&bodyServiceThermometerTemperature, "service-thermometer-temperature", 0, "Service thermometer temperature")
	cmd.Flags().IntVar(&bodySource, "source", 0, "Source")
	cmd.Flags().IntVar(&bodyStatus, "status", 0, "Status")
	cmd.Flags().IntVar(&bodySubIssueType, "sub-issue-type", 0, "Sub issue type")
	cmd.Flags().IntVar(&bodyTicketCategory, "ticket-category", 0, "Ticket category")
	cmd.Flags().StringVar(&bodyTicketNumber, "ticket-number", "", "Ticket number")
	cmd.Flags().IntVar(&bodyTicketType, "ticket-type", 0, "Ticket type")
	cmd.Flags().StringVar(&bodyTitle, "title", "", "Title")
	cmd.Flags().StringVar(&bodyUserDefinedFields, "user-defined-fields", "", "User defined fields")
	cmd.Flags().BoolVar(&stdinBody, "stdin", false, "Read request body as JSON from stdin")

	return cmd
}
