// Copyright 2026 Damien Stevens and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newQuoteDiscountGroupCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "quote-discount-group",
		Short:       "Manage quote discount group",
		Hidden:      true,
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newQuoteDiscountGroupDiscountGroupPublicCreateCmd(flags))
	cmd.AddCommand(newQuoteDiscountGroupDiscountGroupPublicGetAllCmd(flags))
	cmd.AddCommand(newQuoteDiscountGroupDiscountGroupPublicGetByIdCmd(flags))
	cmd.AddCommand(newQuoteDiscountGroupDiscountGroupPublicUpdateCmd(flags))
	cmd.AddCommand(newQuoteDiscountGroupCompaniesCmd(flags))
	return cmd
}
