// Copyright 2026 Damien Stevens and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newSecretsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "secrets",
		Short:       "List, get, create, update, and delete secrets",
		Hidden:      true,
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newSecretsCreateCmd(flags))
	cmd.AddCommand(newSecretsDeleteCmd(flags))
	cmd.AddCommand(newSecretsGetCmd(flags))
	cmd.AddCommand(newSecretsListCmd(flags))
	cmd.AddCommand(newSecretsUpdateCmd(flags))
	return cmd
}
