// Copyright 2026 Damien Stevens and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newScriptsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "scripts",
		Short:       "Get, create, update, and delete scripts",
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newScriptsScriptsCmd(flags))
	cmd.AddCommand(newScriptsScriptsEndpointCmd(flags))
	cmd.AddCommand(newScriptsScriptsPkCmd(flags))
	cmd.AddCommand(newScriptsScriptsPk2Cmd(flags))
	cmd.AddCommand(newScriptsScriptsPk3Cmd(flags))
	cmd.AddCommand(newScriptsScriptsSnippetsCmd(flags))
	cmd.AddCommand(newScriptsScriptsSnippets2Cmd(flags))
	cmd.AddCommand(newScriptsScriptsSnippets3Cmd(flags))
	cmd.AddCommand(newScriptsScriptsSnippets4Cmd(flags))
	cmd.AddCommand(newScriptsScriptsSnippets5Cmd(flags))
	cmd.AddCommand(newScriptsDownloadCmd(flags))
	cmd.AddCommand(newScriptsTestCmd(flags))
	return cmd
}
