// Copyright 2026 Damien Stevens and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newSoftwareCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "software",
		Short:       "Get, create, and update software",
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newSoftwareSoftwareCmd(flags))
	cmd.AddCommand(newSoftwareSoftwareAgentidCmd(flags))
	cmd.AddCommand(newSoftwareSoftwareAgentid2Cmd(flags))
	cmd.AddCommand(newSoftwareSoftwareAgentid3Cmd(flags))
	cmd.AddCommand(newSoftwareSoftwareChocosCmd(flags))
	cmd.AddCommand(newSoftwareSoftwareEndpointCmd(flags))
	cmd.AddCommand(newSoftwareSoftwareEndpoint2Cmd(flags))
	cmd.AddCommand(newSoftwareUninstallCmd(flags))
	cmd.AddCommand(newNovelSoftwareFindCmd(flags))
	return cmd
}
